### ISSUE TITLE
text color

### ISSUE THREAD

**Issue by pholyheang** [nativewind/nativewind#1000]
**Describe the bug**
Default Text color on Androd version 10 show white color not black

**Comment by marklawlor** [comment]
I do not understand this issue. NativeWind doesn't change the default text color except when no initial color is provide transition or animation. Please provide a reproduction

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
