### ISSUE TITLE
using custom border width and border color hurt the performance

### ISSUE THREAD

**Issue by C0DE-L00P** [nativewind/nativewind#1005]
**Describe the bug**
```
<TouchableOpacity 
    onPress={() => {
      carouselRef?.current?.scrollToNext();
      scrollViewRef.current?.scrollTo({y: 0, animated: true});
    }} 
    className='absolute bottom-4 right-4 bg-white p-4 rounded-full border-[2px] border-primary' >
    <Icons.IcArrow className="text-primary rotate-180" width={24} height={24}/>
  </TouchableOpacity>

```
This code was pain to performance in old android devices (Mine was on Android Nougat 24 Sdk). after trial and error, I figure out that the cause was "border-2" and "border-primary", when I take them off and use normal styles it worked butter smooth

You can recreate the problem if you run this code on old android phone with 3gb ram at most

      <View className='px-4'>
          <Text className="font-bold text-xl mb-2">
            Bedrooms
          </Text>
          <View className='flex flex-row flex-wrap gap-1'>
            {[1,2,3,4,5,6].map(num=> (
              <TouchableOpacity style={{}} className={`self-center p-2 rounded-full aspect-square w-[34px] border-2 ${filter.bedrooms == num? 'bg-primary':'border-dark'}`} onPress={()=> setFilter(prev=> ({...prev, bedrooms: num}))}  key={'bed-'+num}>
                <Text className={`text-center text-xs ${filter.bedrooms == num? 'text-white':'text-dark'}`}>{num}</Text>
              </TouchableOpacity>
            ))}
          </View>
        </View>

**Expected behavior**
scrolling should be fine and the now lag in performance

**Expo Snack**

**Screenshots**
![image](https://github.com/user-attachments/assets/5003301b-1548-4c75-a408-1f0389e5eef0)

**Comment by manssorr** [comment]
Thanks for share, is this open-source project? @C0DE-L00P

**Comment by marklawlor** [comment]
I'm unable to reproduce the problem with the information provided. `border-{n}` are the least intensive styles that NativeWind uses (there is no polyfill and they are compiled as static). There's no difference in how they are processed to `bg-white`. The fact that you isolated the issue to just these styles makes it clear that there is something else causing this issue.

My guess is multiple rerenders causing repaints, but without a full reproduction I cannot provide any assistance.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
