### ISSUE TITLE
[4.1] EAS iOS App Store build failing in `Run FastLane` - SHA-1 for file global.css.ios.js is not computed

### ISSUE THREAD

**Issue by valtism** [nativewind/nativewind#1009]
**Describe the bug**
After updating to v4.1.1, running `eas build --platform iOS` is now failing due to an error in the Run Fastlane command.

The error is:

```
❌ error: SHA-1 for file /Users/expo/workingdir/build/global.css.ios.js (/Users/expo/workingdir/build/global.css.ios.js) is not computed.

❌ Metro encountered an error:
SHA-1 for file /Users/expo/workingdir/build/global.css.ios.js (/Users/expo/workingdir/build/global.css.ios.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
Learn more: https://docs.expo.dev/build-reference/troubleshooting
```

**To Reproduce**

Unsure of how to exactly reproduce this, but it was working fine on v4.0.36

Hopefully this helps with some debugging, or others with similar issues can chime in.

metro.config.js

```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require("nativewind/metro");

// eslint-disable-next-line no-undef
const config = getDefaultConfig(__dirname);

config.transformer = {
  ...config.transformer,
  babelTransformerPath: require.resolve("react-native-svg-transformer/expo"),
};
config.resolver = {
  ...config.resolver,
  assetExts: config.resolver.assetExts.filter((ext) => ext !== "svg"),
  sourceExts: [...config.resolver.sourceExts, "svg"],
};

module.exports = withNativeWind(config, {
  input: "./global.css",
  inlineRem: 16,
});
```

global.css

```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

tailwind.config.js

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontSize: {
        sm: ["0.8125rem", { lineHeight: "1.25rem" }],
      },
    },
  },
  plugins: [],
};
```

**Comment by askasp** [comment]
I have exactly the same problem. Which package did you upgrade to 4.11?

**Comment by valtism** [comment]
@askasp nativewind, hence posting in this repo

**Comment by Eighke** [comment]
Got the same issue. 

What is strange is that I didn't upgrade anything. I just rebuild an old version and it fail, when it was working 2 months ago.

**Comment by Eighke** [comment]
Ok to confirm, I just build a second app that is release 2 weeks ago. And the build also fail with the same message.

I suppose it's a dependency that got updated.

**Comment by valtism** [comment]
I was able to roll back to 1.0.36 and it worked again

**Comment by Eighke** [comment]
I'm already on the 4.0.36, if it's a dependency it may solve by itself.

> I was able to roll back to 1.0.36 and it worked again

Maybe it's already fixed, I just rerun a build. I'll let you know.

**Comment by CodeWithShreyans** [comment]
same here, rollback to 4.0.36 fixed it

**Comment by bhaveymunjal** [comment]
nativewind version 4.0.35 worked for me. Got the solution from [here](https://github.com/nativewind/nativewind/issues/591#issuecomment-2228362168)

**Comment by b1ngx** [comment]
same with android

**Comment by Eighke** [comment]
> nativewind version 4.0.35 worked for me. Got the solution from [here](https://github.com/nativewind/nativewind/issues/591#issuecomment-2228362168)

From what I can read, it is a cache issue with EAS. So what I did to use `clear-cache`:

```
eas build --platform ios --clear-cache
```

And it fixed the issue. Rollback will probably just invalidated the cache automatically, that why it also work.

**Comment by valtism** [comment]
@Eighke It may have worked for you because a new version was just released and from the commits that looks like it may have fixed the issue. I'll try upgrading and testing on my CI now

**Comment by Eighke** [comment]
@valtism I'm still using the 4.0.36 since the beginning, I never updated to 4.1.

**Comment by valtism** [comment]
Can confirm that this is fixed on 4.1.4. Thanks @marklawlor!

**Comment by pvinis** [comment]
I'm on 4.1.18, and I cleared the cache on eas, and I still get this.
```
❌ Metro encountered an error:
SHA-1 for file /Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
Learn more: https://docs.expo.dev/build-reference/troubleshooting
```

**Comment by dipakparmar** [comment]
> I'm on 4.1.18, and I cleared the cache on eas, and I still get this.
> 
> ```
> ❌ Metro encountered an error:
> SHA-1 for file /Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js is not computed.
>          Potential causes:
>            1) You have symlinks in your project - watchman does not follow symlinks.
>            2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
> Learn more: https://docs.expo.dev/build-reference/troubleshooting
> ```

getting the same on `4.1.19`

**Comment by marklawlor** [comment]
I cannot troubleshoot an issue with just an error message. 

If you still have an issue, then you have a different issue then the one reported here. You need to create a new issue with a reproduction repro.

**Comment by pvinis** [comment]
@marklawlor, repro here: https://github.com/pvinis/nw-eas-repro

as i was making it, there must be the expo-updates package stage.

Right above the error we posted above, there is a line `Generate updates resources for expo-updates`. Builds were green, and as soon as I added expo-updates back, it failed. So I guess there is some issue there.

You could use my repo, or maybe just set up a repo with nativewind and expo-updates, and see it fail.

**Comment by MrPiao** [comment]
I'm also running into this, although the file that my error message is complaining about is slightly different:

> ❌  error: SHA-1 for file /Users/expo/workingdir/build/apps/expo/node_modules/react-native-css-interop/.cache/ios.js is not computed.

**The key here seems to be the presence of `expo-updates`.** Since @pvinis mentioned the `expo-updates` package above, I tried removing it from my `package.json`, and voila, the build succeeded.

**Comment by MrPiao** [comment]
Looks to be related to https://github.com/nativewind/nativewind/issues/1158

**Comment by pvinis** [comment]
right. unfortunately removing expo-updates is not really a viable solution for everyone.

I just don't know if it's the fault is on expo-updates side or nativewind side.

**Comment by DevDK12** [comment]
I was able to solve it by downgrading nativewind to 4.0.36
