### ISSUE TITLE
Conversion using Vars function failed in version 4.0.36

### ISSUE THREAD

**Issue by tipbsy** [nativewind/nativewind#1011]
Expo SDK 51
nativewind 4.0.36
Use the vars function to convert to an empty object as the result

code
import { vars } from 'nativewind';
console.log('====================')
console.log("Vars", vars({ '--brand-color': 'red'}));

 LOG  ====================
 LOG  Vars {}

**Comment by marklawlor** [comment]
`vars` returns an empty object. The information for the variables are stored internally and the object is simply the key to a `WeakMap`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by tipbsy** [comment]
Thank you, this is my question
