### ISSUE TITLE
SyntaxError: Invalid state

### ISSUE THREAD

**Issue by maukoese** [nativewind/nativewind#1014]
Last thing I remember doing before this error was removing some classes. I have no idea what is causing this issue. Any assistance will be really appreciated.

![Screenshot 2024-08-30 at 10 58 10](https://github.com/user-attachments/assets/e0ac7572-d294-4150-929f-b8b1b4b27f65)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
