### ISSUE TITLE
 [Error: InternalError Metro has encountered an error: Invalid state

### ISSUE THREAD

**Issue by maukoese** [nativewind/nativewind#1017]
This issue persists in v4, it goes away when I comment out the line importing the global css file.

It's. the same issue I raised earlier [1014](https://github.com/nativewind/nativewind/issues/1014)

Any help would really really be appreciated.

![Screenshot 2024-08-31 at 15 21 51](https://github.com/user-attachments/assets/a599b024-ac69-4155-9a36-543679ab999a)

**Comment by marklawlor** [comment]
We cannot provide assistance with only screenshots. We would need a reproduction repo so we can actually the code and see what the problem is.

Please only create 1 issue.

**Comment by maukoese** [comment]
This is a project that has been running for more than 6months, can't quite reproduce it at this point. Screenshots are meant to show you exact errors appearing in my setup. Perhaps someone else has or will experience the same issue and assist.

As for having two issues, that is the instruction from the tag that was added to the other issue, that said if issue persists in v4 I reopen and link to the previous.
