### ISSUE TITLE
v4.1.1: Cannot find module .../node_modules/nativewind/dist/metro/transformer.js

### ISSUE THREAD

**Issue by Darren120** [nativewind/nativewind#1031]
After attempting to upgrade, the build runs, but when trying to launch the app i get Cannot find module .../node_modules/nativewind/dist/metro/transformer.js

metro.config.js
```
const { getDefaultConfig } = require('expo/metro-config')
const { withNativeWind } = require('nativewind/metro')

const createConfig = () => {
  const config = getDefaultConfig(__dirname)

  const { transformer, resolver } = config

  config.transformer = {
    ...transformer,
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  }
  config.resolver = {
    ...resolver,
    assetExts: resolver.assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...resolver.sourceExts, 'svg'],
  }
  return config
}

const config = createConfig()
module.exports = withNativeWind(config, { input: './app.css' })

```

 "nativewind": "4.1.1",
"tailwindcss": "^3.4.10",
 "expo": "^51.0.18",
    "@expo/metro-config": "~0.18.1",

**Comment by marklawlor** [comment]
Did you reset your Metro cache? The Metro transformer was removed in `4.1`

**Comment by Darren120** [comment]
> Did you reset your Metro cache? The Metro transformer was removed in `4.1`

thanks that worked, was also getting getFlag undefined err but upgraded to 4.1.4 and it fixed
