### ISSUE TITLE
pe/ps can not work in expo

### ISSUE THREAD

**Issue by Jianlong-Nie** [nativewind/nativewind#1036]
**Describe the bug**
pe/ps can not work in expo

**Reproduction**
  ```
<View className="flex pe-2.5">
          <ProfileImage
            initUserDisplayInfo={otherUser}
            key={otherUser?.userId}
            override={imageUrl}
            profileNavigation={false}
            type="thumbnail"
          />
        </View>
```

it can work fine in 4.0.36,but after i upgraded to 4.1.6.it can not work 

**version 4.0.36**
<img width="400" alt="4.0.36" src="https://github.com/user-attachments/assets/533afb82-20fa-4103-8a94-f1e2039e9f8a">

**version 4.1.6**
<img width="384" alt="image" src="https://github.com/user-attachments/assets/a6f6368b-e34b-4375-b928-bfb65e65739e">

**Comment by danstepanov** [comment]
Closing until there is a proper repro https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue
