### ISSUE TITLE
text-color class is not working

### ISSUE THREAD

**Issue by mohamedamara1** [nativewind/nativewind#1046]
**Describe the bug**
text-red-500 is not working

**Reproduction**
I used the expo template of tabs, removed all additional code and left only the root _layout and index.tsx, installed nativewind V4 (    "nativewind": "^4.0.1",) followed the setup steps on the docs
I'm trying to set the text color to red for the 'Tab one' string but it's not working

**Expected behavior**
text should be in red

**Additional context**
![image](https://github.com/user-attachments/assets/c0e815b1-69af-49ec-b308-810bec0bcf42)

Looks like #892 is a related issue

**Comment by shovel-kun** [comment]
@mohamedamara1 have you told your `tailwind.config.cs` where your screens and components live? 

By default it points to:
```js
  content: ['./app/**/*.{ts,tsx}', './components/**/*.{ts,tsx}'],
``

**Comment by mohamedamara1** [comment]
Yes I have done that
`  content: ["./src/**/**/*.{js,jsx,ts,tsx}"]
`
I have a top level src folder, inside of it I have the app folder and components folder

**Comment by mohamedamara1** [comment]
I found the issue, I was using the View and Text from the Themed.tsx component and it looks like it didn't pass the className prop down. I changed the import to use the ones from 'react-native' and it's working now
