### ISSUE TITLE
Is nativewind automatically applying media queries for mobile?

### ISSUE THREAD

**Issue by Vimiso** [nativewind/nativewind#1047]
Take the given example:

<img width="603" alt="Screenshot 2024-09-06 at 15 20 58" src="https://github.com/user-attachments/assets/75482050-c275-4e89-bb88-b53718972c34">

In web this gives:
<img width="596" alt="Screenshot 2024-09-06 at 15 21 26" src="https://github.com/user-attachments/assets/74e7e2ca-e253-406e-9d1b-7b9a75f2c6ae">

But on mobile:
<img width="352" alt="Screenshot 2024-09-06 at 15 21 57" src="https://github.com/user-attachments/assets/bb375644-180d-4169-a3d0-f16e976188ac">

So my question is: are all flex, grid or justified item widths somehow ignored and therefore automatically stacked on mobile?

**Comment by tamagokun** [comment]
grid styles are currently web only.

**Comment by danstepanov** [comment]
1) please try using v4.1 of NativeWind
2) Please provide a reproduction of the issue using one of the following templates:

**StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
**Create Expo Stack template**:
`npx create-expo-stack@latest --nativewind`
`npx create-expo-stack@latest --nativewind --expo-router`

Closing this issue until these point are addressed

**Comment by marklawlor** [comment]
NativeWind only supports the same styles of your version of React Native. Sometimes we can convert something to a support style (e.g viewport units) but we cannot implement layouts that are not supported. Hence grid will not work as React Native does not support grid
