### ISSUE TITLE
Enabled and disabled not working in web with Pressable

### ISSUE THREAD

**Issue by Vimiso** [nativewind/nativewind#1049]
```
"tailwindcss": "^3.4.10",
"nativewind": "^4.0.1",
```

Disabled state of pressable on mobile:
<img width="236" alt="Screenshot 2024-09-07 at 03 56 50" src="https://github.com/user-attachments/assets/5ced49f6-1f38-41f1-b577-8bf8cc9a530e">

Disabled state of pressable on web:
<img width="245" alt="Screenshot 2024-09-07 at 03 57 09" src="https://github.com/user-attachments/assets/7171dbcc-f12c-46bc-b57f-d70f4e573d84">

You can see it stays the same. Styles used are:
```
'hover:bg-stone-600',
'rounded border border-stone-600',
'transition-colors',
'py-2 px-4',
'text-center',
'font-noto',
'active:border-fuchsia-600',
'enabled:opacity-100',
'disabled:opacity-50',
```

Component:
```jsx
<Pressable className={ styles[style].join(' ') } onPress={ resolveOnPress } disabled={ disabled }>
```

**Comment by danstepanov** [comment]
1) please try using v4.1 of NativeWind
2) Please provide a reproduction of the issue using one of the following templates:

**StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
**Create Expo Stack template**:
npx create-expo-stack@latest --nativewind
npx create-expo-stack@latest --nativewind --expo-router

**Comment by marklawlor** [comment]
This is an upstream issue with React Native Web. It does not disable pointer events on the `<Pressable />`

**Comment by Vimiso** [comment]
Yeah it would seem so. I opted against using tailwind modifiers in the end and hooked into button props overriding classes with `twMerge`.
