### ISSUE TITLE
Expo + Nativewind - can't import module 'global.css' since nativewind v4.1.2

### ISSUE THREAD

**Issue by Bohdan-Tereta** [nativewind/nativewind#1053]
My layout file in ReactNative (Expo) project has this line: 
`import '../global.css';` - file is there under the path and it was working fine before nativewind 4.1.2
after 4.1.2 I get `node_modules/expo-router/node/render.js ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ 100.0% (1266/1266)Error: Unable to resolve module ../global.css from /tmp/workspace/apps/beyond-frontend/app/_layout.tsx: ../global.css could not be found within the project...` error
same happens in 4.1.6 as well
when I revert to 4.1.1 everything is OK

**Comment by marklawlor** [comment]
Hi, unfortunately we cannot provide assistance from an error message alone - we need a reproduction repo to be able to assist you.

I'm going to close this issue, when you have a reproduction repo please create a new issue.
