### ISSUE TITLE
v2: Display of rounded-full views with borders does not appear on Android 8 and lower

### ISSUE THREAD

**Issue by thomasrebam** [nativewind/nativewind#1055]
**Describe the bug**
With Android 8 and lower, when displaying a view with "rounded-full", the view does not appear on the screen.
Phone specification : 
- Android version : 8.0.0
- Model : Samsung Experience 9.0

**Reproduction**
Using the rounded-full prop, along with border-1 prop, we cannot see the border of the view.

```
import { View } from "react-native";

export default function Home() {
  return (
    <View className="flex-1 bg-white items-center justify-center">
      <View className="bg-white h-[20px] w-[20px] rounded-full border-1 border-black" />
    </View>
  );
}
```

<img width="474" alt="Capture d’écran 2024-09-10 à 17 30 13" src="https://github.com/user-attachments/assets/55dd8dd4-5a3e-47ef-bf63-92f0d55bd501">

Whereas, with a given value in pixels for the rounded parameter, the border indeed displays : 
```
import { View } from "react-native";

export default function Home() {
  return (
    <View className="flex-1 bg-white items-center justify-center">
      <View className="bg-white h-[20px] w-[20px] rounded-[20px] border-1 border-black" />
    </View>
  );
}
```

<img width="474" alt="Capture d’écran 2024-09-10 à 17 30 39" src="https://github.com/user-attachments/assets/770d1e04-e3aa-4155-a457-c56e0df68479">

Note : rounded full sets the borderRadius to 9999px (see picture below). 
<img width="260" alt="Capture d’écran 2024-09-10 à 17 32 47" src="https://github.com/user-attachments/assets/e2e64e1c-d5c8-4e13-9111-840eaf5daa1a">
After testing with inline style, it appears that setting borderRadius to 9999 does not make the view disappear : 

```
import { View } from "react-native";

export default function Home() {
  return (
    <View
      style={{
        flex: 1,
        backgroundColor: "white",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <View
        style={{
          backgroundColor: "white",
          height: 20,
          width: 20,
          borderRadius: 9999,
          borderWidth: 1,
          borderColor: "black",
        }}
      />
    </View>
  );
}
```

<img width="476" alt="Capture d’écran 2024-09-10 à 17 51 04" src="https://github.com/user-attachments/assets/6c2f4739-5f54-4032-97d1-949a33abbda9">

**Expected behavior**
I would expect to see the rounded view with the rounded-full configuration.
I don't know if it is worth solving the issue, as it concerns older devices, but I think it might be worth exposing a warning, some comment, or some documentation about the fact that rounded-full may not be fully functional for all Android phones versions.

**Additional context**
From what I found, the issue probably comes from OpenGLRenderer, as it raises an error, and as its configuration changes after Android 8 ([see documentation here](https://source.android.com/docs/core/graphics/renderer?hl=en)), which matches the Android versions on which the issue occur.
`2024-09-10 17:40:45.803 24517-24650 OpenGLRenderer          com.my.app                   W  Shape too large to be rendered into a texture (8792x17518, max=8192x8192)`

**Comment by marklawlor** [comment]
As Android 8 is well past end-of-life I'm not going to action this issue. If a user does discover this via the search they should just opt to use inline styles for this specific instance.
