### ISSUE TITLE
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

### ISSUE THREAD

**Issue by hossain45** [nativewind/nativewind#1058]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

_Originally posted by @danstepanov in https://github.com/nativewind/nativewind/issues/838#issuecomment-2325377888_

After a fresh install using [https://www.nativewind.dev/v4/getting-started/expo-router](url)

I still get the same error:

**Comment by marklawlor** [comment]
You get this error when the project is incorrectly setup. We cannot advise you on your code if you don't share your repro.

Closing issue due to lack of information
