### ISSUE TITLE
use nativewind programmatically 

### ISSUE THREAD

**Issue by alidcast** [nativewind/nativewind#1066]
the same way you're calling tailwind cli programmatically, so that you can add functionality on top, is there a way to call nativewind programmatically? 

for example, if writing a React Native app with Clojurescript, the babel plugins don't work as well, so I'd be great to be able to call Tailwind via a macro, pass the required styles, and inject the respective variable, etc. 

let me know if this use-case is workable and could be supported; thank you.

**Comment by marklawlor** [comment]
React Native only officially supports Metro as a bundler, so NativeWind only supports Metro. Other uses we will not provide support for.

But your talking about Babel, the compiler that Metro uses. I'm assuming your toolchain is to compile Clojurescript to JavaScript and then pass that to the Metro bundler. In that case, you just need to ensure:

**jsxTransform**

NativeWind needs the `jsxImportSource` to be set to `nativewind`. By default we use Babel for this, but this isn't a "babel" feature. All JavaScript compilers support setting the `jsxImportSource` (its one of the requirements of supporting React) so I would assume the Clojurescript compiler also supports it. Alturnatively, you could not compile the React (e.g how TypeScript works) and allow Metro to do a Babel pass over your output to change the `jsxImportSource`.

** Style injection **

 This is performed in Metro as part of resolver and not part of code compilation. You just need to ensure that your compiled Clojurescript has the JS statement `import "<your css file>"` in it. When Metro tries to resolve this file, this is when we inject our style. So its part of the bundler, not the compiler.
