### ISSUE TITLE
react-native-css-interop generates enormous cache files that significantly slow down app load

### ISSUE THREAD

**Issue by evelant** [nativewind/nativewind#1071]
**Describe the bug**
Using the tailwind.config.js from gluestack-ui-v2 `node_modules/react-native-css-interop/.cache/android.js` is a 4.3MB minified js file that takes ~250ms to load on app start. That is a significant chunk of load time.

Is this intended or expected behavior? Does it come with a runtime performance penalty beyond the loading of the large file?

If this is expected behavior maybe a warning should be added to the docs.

**Reproduction**
https://github.com/evelant/css-interop-large-cache-example

```
npm install
npx expo export -p android
```

observe that `node_modules/react-native-css-interop/.cache/android.js` is very large and that it slows down app load significantly

**Expected behavior**
Nativewind adds little/no overhead to app loading and runtime

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by marklawlor** [comment]
Why do you have a `safelist` generating every possible style combination?

```
safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark)/,
    },
  ],
```

**Comment by evelant** [comment]
I'm actually not sure, that's the recommended config generated by gluestack-ui-v2. Is that what's causing the enormous file generation?

**Comment by marklawlor** [comment]
Its mostly NativeWind's fault, as the output file isn't very optimised. But the `safelist` forces `14,000` styles to be generated which isn't helping.

@Viraj-10 Does Gluestack require all these styles to be generated?

**Comment by Viraj-10** [comment]
@evelant  @marklawlor, We are working on this problem by writing tailwind-plugin.

**Use Case:**
We're working on a solution where we need to apply state-based styling to our components. Currently, in NativeWind, this is achievable using conditional `className` assignments.

**Example:**
```jsx
<Modal className={isOpen ? "bg-transparent" : "bg-primary"} />
```

However, in Tailwind, it's possible to handle this with `data-*` attributes for cleaner state management:

**Example:**
```jsx
<Modal className="bg-transparent data-[open=true]:bg-primary" />
```

To bring this functionality to NativeWind, we've written a Higher-Order Component (HOC) that provides developers with a familiar `data-*` attribute API. This HOC attaches and detaches `className` values based on the component's state. 

Currently, we remove the `data-*` portion of the className and convert:
```css
data-[open=true]:bg-primary
```
into:
```css
bg-primary
```

However, this means that `bg-primary` won't be injected by default, so we require the use of a safelist to ensure the class is applied.

In the future, we plan to submit a pull request (PR) to officially support `data-*` attributes in NativeWind.

@evelant this is more of gluestack-ui problem than nativewind. you can open a issue on gluestack-ui repo we can follow up there.

**Comment by marklawlor** [comment]
Continuing conversation here: https://github.com/gluestack/gluestack-ui/issues/2472

I'll be performing a number of PRs over the next week to reduce the output size from NativeWind's end, but I'll work with Gluestack to reduce the number of classes they need.
