### ISSUE TITLE
[v4.1.9] Stuck on SplashScreen

### ISSUE THREAD

**Issue by mrzachnugent** [nativewind/nativewind#1072]
## Description
Upon starting a new expo-go project with NativeWind version 4.1.9, the app gets stuck on the SplashScreen. I also got the same thing with v4.1.8, and I got it work with v4.1.7.

## Reproduction
Clone the following reproduction repo, and run `npm i && npm run dev`: https://github.com/mrzachnugent/nativewind-repro-4.1.9 

### Expected behavior
The app should not get stuck on the SplashScreen.

**Comment by danstepanov** [comment]
successfully reproduced

**Comment by unbelivr** [comment]
Every new 4.1.x version breaks something or everything. I know v4 is still unstable and not ready for production, so wouldn't it be better to release as beta just not to make people confused by such usage of semver?

**Comment by marklawlor** [comment]
Fixed in `4.1.10`

`4.0` and `4.1` are both beta. If you don't like the `4.1` then lock your versions using `~` instead of `^`. We used a new minor for this reason
