### ISSUE TITLE
Incorrect Copy-Paste Behavior for `nativewind-env.d.ts` File

### ISSUE THREAD

**Issue by shaikahmadnawaz** [nativewind/nativewind#1077]
**Describe the bug**  
When I use the clipboard icon to copy the contents of the `nativewind-env.d.ts` file, the pasted result is incorrect. Instead of the expected content, I receive a distorted version of the file.

![{CC9BF154-D746-4681-906E-133B04548CF8}](https://github.com/user-attachments/assets/e4cc3ca0-e506-4c7e-a731-3caad2d41d08)

**Steps to Reproduce**  
1. Copy the contents of the `nativewind-env.d.ts` file using the clipboard icon.
2. Paste the copied content and review the result.

![image](https://github.com/user-attachments/assets/bbc475b2-9f4c-4804-bb95-6136ec9f05e4)

**Expected Behavior**  
After copying and pasting, I expect the content to match the original file, specifically:  
```
/// <reference types="nativewind/types" />
```

**Comment by FleetAdmiralJakob** [comment]
Hi, I tried to reproduce your issue. Unfortunately, I wasn't able to do so. Could you please specify the operating system you are using, maybe it's a VSCode extension too that is causing the issue (try using VSCode without extensions).

**Comment by danstepanov** [comment]
I'm also unable to recreate this issue, closing
