### ISSUE TITLE
Building Responsive Display for Mobile Device

### ISSUE THREAD

**Issue by ChubbyArse** [nativewind/nativewind#1078]
I've begun a React Native (Expo, NativeWind) project and I'm beginning to look at tailoring the components and tried using the responsive syntax from tailwind to get images to look bigger on iPads compared to iPhones:

```
<Image
        className="h-10 w-10 md:h-20 md:w-20"
        source={{ uri: imageUrl }}
        resizeMode="contain"
      />
```

I'm using:
```
    "nativewind": "^2.0.11",
    "tailwindcss": "^3.3.2",
```

However, I don't get any difference in display on the different devices.

I looked at the [Responsive](https://www.nativewind.dev/core-concepts/responsive-design) section on the NativeWind page and read that the default theme doesn't support mobile viewports. I'm new to all this and I don't understand the implication of this. 

Do I need to write a theme that does use breakpoints (and where to I start with this)? Is there something I'm missing?

**Comment by danstepanov** [comment]
We don't yet have a variant of the tailwind system (`sm`, `md`, `lg`, `xl`, etc) which maps to device dimensions. Therefore, unless you overwrite the default breakpoint values for these yourself, you'll be using the breakpoint values set by Tailwind. We do plan to implement our own variant of these values as we see it as a fairly core part of the mobile design experience.

In the meantime, [here's a link to documentation for how you can currently set custom breakpoints.](https://tailwindcss.com/docs/screens) Hope this helps.

**Comment by ChubbyArse** [comment]
Many thanks for the response. I upgraded to v4 and added custom breakpoints from here: https://gist.github.com/cvan/47455a4f8aaa22e73e54253954635dc5

Everything working as expected now. 👍

**Comment by pedrocarlos-ti** [comment]
Hi @ChubbyArse 👋🏻 

After almost 06 months, did you figure out how to implement in both viewport?

**Comment by raam-coder** [comment]
> Many thanks for the response. I upgraded to v4 and added custom breakpoints from here: https://gist.github.com/cvan/47455a4f8aaa22e73e54253954635dc5
> 
> Everything working as expected now. 👍


You add 300px for small but we have devices 280 also how it works,

And also i want to ask that it will worked surely?
