### ISSUE TITLE
Two Issues (explained further in description) with Nativewind v4

### ISSUE THREAD

**Issue by XavierToresLopez** [nativewind/nativewind#1087]
**Reproduction Link:** https://github.com/XavierToresLopez/className-Issues

**Describe the bug**
There are currently two issues I've shown here. The first is related to how className seems to not be recognized by some external libraries, in this case, LinearGradient. The second issue shows how, although core components show the new Nativewind props, they aren't properly recognized. In this example, the core component TextInput is used with the "placeholderClassName" prop. The reproduction shows how the prop is fully ignored/unrecognized. 

**Reproduction**
I've used the `npx create-expo-stack@latest --nativewind` method to create a reproduction environment with comments that show how to test and see the issues as well.

**Expected behavior**
Issue 1: The LinearGradient component should be recognizing and applying the styles passed to it via className, but instead it just disappears (because it doesn't recognize that a width and height are being passed to it). However, when applying the exact same styles using the built-in style prop, it functions properly and displays my text with a gradient on it.

Issue 2: The placeholderClassName prop should be properly passing styles to the placeholder in the TextInput, but instead it ignores or does not recognize the styles passed. However, when using other props, such as "placeholderTextColor", the styles apply properly.

**Comment by elalami-m** [comment]
I'm facing the same problem

**Comment by danstepanov** [comment]
I'll take a look on Monday

**Comment by marklawlor** [comment]
Use `placeholder:` instead of `placeholderClassName`. Also [Text Input](https://reactnative.dev/docs/textinput) only has a [placeholderTextColor](https://reactnative.dev/docs/textinput#placeholdertextcolor) prop, so `placeholder:` only works for `color` styles. 

This might change in the future, as some internal work will allow for `placeholder:` to work for any style
