### ISSUE TITLE
Inconsistent Style Application: `w-` Width and Incompatibility with Certain Components (e.g., LinearGradient)

### ISSUE THREAD

**Issue by elalami-m** [nativewind/nativewind#1088]
Here's the bug report in the requested format:

---

**Describe the bug**
NativeWind classes aren't applying the expected styles. For example, using the `w-40` class (which corresponds to a width of 160 pixels) doesn't result in the same width as setting an inline style with `width: 160px`. Additionally, some components, such as `LinearGradient`, do not seem to work with NativeWind at all.

**Reproduction**
Please see our contribution guide: https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

Reproduction templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**
NativeWind classes should apply styles consistently. For example, `w-40` should always set the width to 160 pixels, just like setting `width: 160px` inline. Furthermore, NativeWind should be compatible with all components, including `LinearGradient`.

**Additional context**
Some components may require inline styles or custom handling, which could limit the flexibility and ease of using NativeWind.

**Comment by ioss** [comment]
I guess you did not change the value for rem from 14 to 16? So `w-40` in tailwind is `10rem`, which would be `140px` – does it match a component with `style={{ width: 140 }}`? You can change the `rem` size, see https://www.nativewind.dev/v4/tailwind/typography/font-size.

Also you need to enhance most ThirdParty components with remap/cssinterop (see https://www.nativewind.dev/v4/api/css-interop)

**Comment by danstepanov** [comment]
Yea so @ioss is referring to how [rem scaling is handled by NativeWind](https://www.nativewind.dev/v4/tailwind/typography/font-size#rem-scaling). Our documentation highlights how this impacts font sizing but it may also apply to properties like width (I'll clarify with Mark tomorrow).

The suggestion to use `cssInterop` is correct.
