### ISSUE TITLE
Tailwind imports interpreted as decorators

### ISSUE THREAD

**Issue by believer** [nativewind/nativewind#1089]
**Describe the bug**

When updating to a version after `4.0.36` we get an error that Tailwind imports, for example `@tailwind base`, are JavaScript decorators. We use [NX](https://nx.dev/) so it might be something related with that. All versions before and equal to `4.0.36` have worked fine.

**Reproduction**

A reproduction of the error: https://github.com/believer/nativewind-nx. This is a [simple setup of React Native with NX](https://nx.dev/recipes/react/react-native) and then following the instructions  of [adding Nativewind with framework-less](https://www.nativewind.dev/v4/getting-started/react-native).

**Additional context**

<img width="381" alt="Screenshot 2024-09-18 at 08 14 41" src="https://github.com/user-attachments/assets/c1cc1258-403e-47fe-9b4b-ee1cf8b27543">

**Comment by marklawlor** [comment]
It appears you are overriding the NativeWind metro config with a custom config. Does the app work if you just use the NativeWind metro config without the custom config?

**Comment by believer** [comment]
I've tried a bunch of different ways of configuring it, but there's always some error 😅 The weird thing is that the exact same reproduction configuration works fine with `4.0.36`.

## Only NativeWind metro config

```js
module.exports = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})
```

**Result:**

It throws on the first import whatever it is, it just happened to be the CSS file here.

```
Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/rickard/happynrwl/apps/mobile/src/main.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
> 1 | import "../global.css";
    | ^
  2 | import { AppRegistry } from "react-native";
  3 | import App from "./app/App";
  4 |
```

## NativeWind with withNxMetro wrapping

```js
const defaultConfig = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})

module.exports = withNxMetro(defaultConfig)
```

**Result:**

```
SyntaxError: /Users/rickard/happynrwl/apps/mobile/global.css: Support for the experimental syntax 'decorators' isn't currently enabled (1:1):

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.
```

## NativeWind as final export

```js
const defaultConfig = getDefaultConfig(__dirname)

module.exports = withNativeWind(withNxMetro(defaultConfig), {
  input: 'global.css',
})
```

**Result:**

```
Unable to resolve module ./src/main from /Users/rickard/happynrwl/apps/mobile/.: 

None of these files exist:
  * src/main(.ios.css|.native.css|.css)
  * src/main
```

## Only withNxMetro

```js
module.exports = withNxMetro(getDefaultConfig(__dirname));
```

**Result:**

This works if I remove the `global.css` import.

**Comment by believer** [comment]
I've tried a bunch of different ways of configuring it, but there's always some error 😅 The weird thing is that the exact same reproduction configuration works fine with `4.0.36`.

## Only NativeWind metro config

```js
module.exports = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})
```

**Result:**

It throws on the first import whatever it is, it just happened to be the CSS file here.

```
Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/rickard/happynrwl/apps/mobile/src/main.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
> 1 | import "../global.css";
    | ^
  2 | import { AppRegistry } from "react-native";
  3 | import App from "./app/App";
  4 |
```

## NativeWind with withNxMetro wrapping

```js
const defaultConfig = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})

module.exports = withNxMetro(defaultConfig)
```

**Result:**

```
SyntaxError: /Users/rickard/happynrwl/apps/mobile/global.css: Support for the experimental syntax 'decorators' isn't currently enabled (1:1):

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.
```

## NativeWind as final export

```js
const defaultConfig = getDefaultConfig(__dirname)

module.exports = withNativeWind(withNxMetro(defaultConfig), {
  input: 'global.css',
})
```

**Result:**

```
Unable to resolve module ./src/main from /Users/rickard/happynrwl/apps/mobile/.: 

None of these files exist:
  * src/main(.ios.css|.native.css|.css)
  * src/main
```

## Only withNxMetro

```js
module.exports = withNxMetro(getDefaultConfig(__dirname));
```

**Result:**

This works if I remove the `global.css` import.

**Comment by believer** [comment]
I've tried a bunch of different ways of configuring it, but there's always some error 😅 The weird thing is that the exact same reproduction configuration works fine with `4.0.36`.

## Only NativeWind metro config

```js
module.exports = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})
```

**Result:**

It throws on the first import whatever it is, it just happened to be the CSS file here.

```
Unable to resolve module @babel/runtime/helpers/interopRequireDefault from /Users/rickard/happynrwl/apps/mobile/src/main.tsx: @babel/runtime/helpers/interopRequireDefault could not be found within the project or in these directories:
  ../../node_modules
> 1 | import "../global.css";
    | ^
  2 | import { AppRegistry } from "react-native";
  3 | import App from "./app/App";
  4 |
```

## NativeWind with withNxMetro wrapping

```js
const defaultConfig = withNativeWind(getDefaultConfig(__dirname), {
  input: 'global.css',
})

module.exports = withNxMetro(defaultConfig)
```

**Result:**

```
SyntaxError: /Users/rickard/happynrwl/apps/mobile/global.css: Support for the experimental syntax 'decorators' isn't currently enabled (1:1):

> 1 | @tailwind base;
    | ^
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |

Add @babel/plugin-proposal-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-proposal-decorators) to the 'plugins' section of your Babel config to enable transformation.
If you want to leave it as-is, add @babel/plugin-syntax-decorators (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-decorators) to the 'plugins' section to enable parsing.
```

## NativeWind as final export

```js
const defaultConfig = getDefaultConfig(__dirname)

module.exports = withNativeWind(withNxMetro(defaultConfig), {
  input: 'global.css',
})
```

**Result:**

```
Unable to resolve module ./src/main from /Users/rickard/happynrwl/apps/mobile/.: 

None of these files exist:
  * src/main(.ios.css|.native.css|.css)
  * src/main
```

## Only withNxMetro

```js
module.exports = withNxMetro(getDefaultConfig(__dirname));
```

**Result:**

This works if I remove the `global.css` import.

**Comment by marklawlor** [comment]
NativeWind changed how it works with Metro between `4.0` and `4.1`

> NativeWind as final export

This one looks correct but are you sure you haven't done something else?

```
Unable to resolve module ./src/main from /Users/rickard/happynrwl/apps/mobile/.: 

None of these files exist:
  * src/main(.ios.css|.native.css|.css)
  * src/main
 ```

Why is this only looking for the `.css` extension? It looks like the extensions config has been completely removed? NativeWind appends `.css` to it, so if you only have `.css` then it was empty?

**Comment by believer** [comment]
You are correct, I tried to make as minimal examples as possible and removed the extension's config, which broke it. I get a new error with this example:

```js
module.exports = withNativeWind(
  withNxMetro(mergeConfig(defaultConfig, customConfig), {
    debug: true,
    extensions: ['css'],
    watchFolders: [],
  }),
  { input: 'global.css' },
)
```

```
error Cannot read properties of undefined (reading 'sourceExts').
TypeError: Cannot read properties of undefined (reading 'sourceExts')
```

I've tracked this down to `withNxMetro` returning a `Promise<Config>`. If I resolve this promise inside the source code of `withNativeWind` everything starts working. Should NativeWind handle promises, or is this something that should be fixed in NX?

**Comment by marklawlor** [comment]
I'm happy to accept a PR. In the meantime you can just resolve the promise outside of `withNativeWind`

**Comment by believer** [comment]
Thanks for the help!

**Comment by xgenem** [comment]
Encountered the same issue today!

**Comment by believer** [comment]
My solution was to resolve the promise from `withNxMetro`:

```ts
async function createConfig() {
  const nxConfig = await withNxMetro(mergeConfig(defaultConfig, customConfig), {
    debug: false,
    extensions: [],
    watchFolders: []
  })

  return withNativeWind(nxConfig, {
    input: 'global.css'
  })
}

module.exports = createConfig()
```

**Comment by xgenem** [comment]
Still hasn't gotten over this issue.

```js
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config')
const {withNativeWind} = require('nativewind/metro')

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
module.exports = withNativeWind(getDefaultConfig(__dirname), {input: './global.css'})

```

Please help?

**Comment by marklawlor** [comment]
@xgenem We cannot help if you do not provide a full reproduction. If you still have this issue, then the cause is elsewhere - but if you don't provide those files we can't provide you with any answers.

Please create a new issue with a full reproduction so we can run the code and find you a solution.

**Comment by marklawlor** [comment]
@YanceyOfficial The direct comment above yours. I cannot help if you do not provide any information.

> We cannot help if you do not provide a full reproduction. If you still have this issue, then the cause is elsewhere - but if you don't provide those files we can't provide you with any answers.
> 
> Please create a new issue with a full reproduction so we can run the code and find you a solution.

**Comment by xgenem** [comment]
> Please create a new issue with a full reproduction so we can run the code and find you a solution.

It's hard to provide full reproduction when the issue happens on your own project, or a project which you're under an NDA.

In the end you have no other choice but to give up. ¯\\\_(ツ)\_/¯ 

Can't blame you guys though. I'll try again in the future.

**Comment by marklawlor** [comment]
@xgenem The first step of troubleshooting is always isolation. For your own sanity, you should be starting with a new template project and slowly adding things until you have a minimal reproductive example.

If you perform troubleshooting in this manner you don't have to break any NDA. I don't want your companies code - and I doubt your use of NX is under NDA.

Just showing me an error message is the equivalent of calling a mechanic and telling them your car is making sounds. They can't fix a car over the phone in the same way I can't fix a problem without code

**Comment by xgenem** [comment]
@marklawlor I know and exactly did that. It did not have the same issue. But when I tried to divide & conquer as well for the project, it still has that error. The error message is the same as above (from OP).

**Comment by xgenem** [comment]
@marklawlor I tried again after upgrading React Native to 0.75.4. Didn't initially work with v2 but v4 works. Thanks a lot for your help.

**Comment by chris-amaya** [comment]
Hello @believer, would it be possible for you to make the project public again (if you still have it)? I’m facing the same issue and would really appreciate the chance to look into it. I’m at a bit of a loss on how to solve it

**Comment by chris-amaya** [comment]
@marklawlor hello Mark, here's a simple NX project, i'm following literally the same steps as @believer and i'm receving the same error. the thing is, i did what he suggested and it's not working for me.


[Github Repository](https://github.com/chris-amaya/final)

**Comment by believer** [comment]
I can't access the repository, but I can take a look as well once it's public!

**Comment by chris-amaya** [comment]
thank you, it's public now! @believer @marklawlor

**Comment by believer** [comment]
The path to your `global.css` is not correct in `metro.config.js`. Updating it fixes the error!

```javascript
// Before
return withNativeWind(nxConfig, {
  input: 'global.css',
})

// After
return withNativeWind(nxConfig, {
  input: './src/app/global.css',
})
```

**Comment by chris-amaya** [comment]
thank you so much! it's working now!

**Comment by r3gisrc** [comment]
Than you @believer , you saved my day !
