### ISSUE TITLE
React Native 0.75.3 global.css.ios.js not found problem in real device

### ISSUE THREAD

**Issue by tunahan-guler** [nativewind/nativewind#1094]
When i starting app in simulator everything is working fine but when i start in my real device react native gives  
"error SHA-1 for file /Users/mscteknoloji/Desktop/cdles_mobile/global.css.ios.js is not computed."
error.
How can i fix it.

Note:When i remove import './global.css'; from App.tsx there is no problem.

    "nativewind": "^4.0.1",
    "tailwindcss": "^3.4.11"
    "react-native": "0.75.3",

**Comment by marklawlor** [comment]
Please follow the issue template provide a reproduction repro. Saying what versions you are using isn't helpful as you are using a version range, I don't actually know if you are using `4.0` or `4.1`. Both are in that range but internally operate very differently. You might also have things in your `metro.condig.js` that affect production builds.

I'm closing this issue but your welcome to create new issue with a reproduction repro.
