### ISSUE TITLE
spin animation not working

### ISSUE THREAD

**Issue by ImamJanjua** [nativewind/nativewind#1095]
So I am trying to add a spin animation to an svg icon similar as I have done with tailwind but the animation is doing nothing. I am using version nativewind": "^4.1.6

<img width="802" alt="Screenshot 2024-09-21 at 17 34 14" src="https://github.com/user-attachments/assets/8e0dfdcf-3555-483d-9eae-a5d015fcf740">

**Comment by marklawlor** [comment]
I cannot provide assistance via a screenshot. There are many reasons why this may not be working (eg bad configuration) but I do not have enough information to provide any answers.

I'm closing this issue. Please create a new issue with a reproduction
