### ISSUE TITLE
[v4.1.10]: Pressable styles not applied when using style callback function

### ISSUE THREAD

**Issue by ConnorLanglois** [nativewind/nativewind#1105]
**Describe the bug**
React Native allows using a callback function for the style prop of the Pressable component, such as this:
```js
<Pressable
  style={({ pressed }) => pressed ? { backgroundColor: 'red' } : { backgroundColor: 'white' }}
>
  <Text>This should be red when pressed</Text>
</Pressable>
```
This feature doesn't work as of NativeWind 4.1.10. The callback function isn't called at all, and thus the styles that would be returned from that function aren't applied. This bug was previously reported in issue #847 (closed due to issue-wipe-pre-v4).
The effects of this bug are also reported in the open issue #1039, thus demonstrating that third-party libs are impacted by this.

Thank you for the work that you all do!

**Reproduction**

Look at the `App.tsx` file in the below repos:

Bug in NativeWind 4.1.10: https://github.com/ConnorLanglois/nativewind-pressable-bug
Correct behavior when not using NativeWind: https://github.com/ConnorLanglois/nativewind-pressable-without-nativewind

**Expected behavior**
Pressable style callback applies styles correctly as is the normal React Native behavior.

**Comment by marklawlor** [comment]
NativeWind doesn't support style callback functions, you should use style modifiers instead `<Pressable className="bg-white active:bg-red-500" />`

**Comment by ConnorLanglois** [comment]
Hi Mark,

Thanks for the reply. Is this is technical limitation of how NativeWind works? The active situation is that third party libs break in subtle but noticeable ways because they rely on this api surface. Appreciate your work. Once the new docs are written it would be nice to have a section for limitations and pitfalls/surprises.

**Comment by Akuma-U1** [comment]
Agreed @ConnorLanglois. Maybe some additional`cssInterop` options and parameters we can add to allow for wrapped third party functions to actually handle style callback functions?

**Comment by marklawlor** [comment]
This fix is for the compiler to detect class names that are invalid with a style functions and warn the user if they try and use them. E.g animation/transitions cannot be used, as well as `em` units and `%` values on some styles. These styles change functionality based upon other styles, and it's impossible for us to calculate their values if they are a function.

This is possible but it takes time and there a higher priorities to work on right now.

If you need a component that uses a style function, I would disable the interop for that component (use the prop `cssInterop={false}` or disable it for the file `/** jsxImportSource react */` (needs to be first line in file)

**Comment by Akuma-U1** [comment]
Thanks @marklawlor ! Will try and report findings.
