### ISSUE TITLE
Allow a more programmatic way to implement dark mode

### ISSUE THREAD

**Issue by Grsz** [nativewind/nativewind#1106]
**Describe the bug**
While it's understandable that this library is trying to replicate tailwind as much as possible, having to specify the dark variant every single place where a color is used is quite repetitive, and error prone.

Tailwind allows this issue to be solved by:
You can define your colors in your CSS file like this:
```
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {

  :root {
    --color-primary: 247 147 34;
    --color-text: 33 33 33;
    --color-success: 0 200 81;
    --color-info: 51 181 229;
    --color-warn: 255 187 51;
    --color-error: 254 78 78;
  }

  :root[class~="dark"] {
    --color-primary: 247 147 34;
    --color-text: 33 33 33;
    --color-success: 0 200 81;
    --color-info: 51 181 229;
    --color-warn: 255 187 51;
    --color-error: 254 78 78;
  }
}
```
and then use this config in your tailwind.config.js:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  theme: {
    colors: {
      primary: "rgb(var(--color-primary) / <alpha-value>)",
      text: "rgb(var(--color-text) / <alpha-value>)",
      success: "rgb(var(--color-success) / <alpha-value>)",
      info: "rgb(var(--color-info) / <alpha-value>)",
      warn: "rgb(var(--color-warn) / <alpha-value>)",
      error: "rgb(var(--color-error) / <alpha-value>)",
      transparent: "transparent",
      current: "currentColor",
    },
}
```
([source](https://stackoverflow.com/a/74574410/9307392))

**Reproduction**
Not something that can be reproduced.

Please provide a reproduction of the issue using one of the following templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**
A solution where color scheme can be accessed in the config, so conditionally specifying values, or a custom implementation where variables can be used as theme values.

**Comment by ConnorLanglois** [comment]
The way you described above is how NativeWind v4 works. Your thoughts are also the ones I had, and luckily they added this in v4

**Comment by danstepanov** [comment]
Please try v4.1 via the `next` dist tag

**Comment by marklawlor** [comment]
I'll add support for `:root[class~="dark"]` because I've seen people use this, but its a bad selector. `:root[class~=dark]` will match `class="not-dark"`. Just use `.dark:root`
