### ISSUE TITLE
[4.1] Shadow style not applied with platform

### ISSUE THREAD

**Issue by martinezguillaume** [nativewind/nativewind#1107]
**Describe the bug**
The `shadow` classname is not working with platform declaration like `ios:shadow-black`

**Reproduction**
You can reproduce very easily with a view
```tsx
  <View className="size-10 shadow-xl ios:shadow-yellow android:shadow-blue" />
```

**Expected behavior**
Shadow color should work with styling per platform

(Was working on `v4.0.1`)

**Comment by danstepanov** [comment]
@martinezguillaume please provide a repro via either[ Create Expo Stack](https://rn.new) or [Stack Blitz](https://nativewind.dev/repro)
