### ISSUE TITLE
the development server returned response error code:500

### ISSUE THREAD

**Issue by Toye101** [nativewind/nativewind#1108]
**Describe the bug**

**Reproduction**
Please see our contribution guide: https://github.com/nativewind/nativewind/blob/main/contributing.md#opening-an-issue

Please provide a reproduction of the issue using one of the following templates:
- **StackBlitz template**: https://stackblitz.com/edit/nativewind-test?view=editor
- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind`
  - `npx create-expo-stack@latest --nativewind --expo-router`

**Expected behavior**

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by Toye101** [comment]
pls how should i fix it

**Comment by marklawlor** [comment]
I cannot provide assistance without you providing any information. If you'd like me to help, you need to provide some information.
