### ISSUE TITLE
vars not working

### ISSUE THREAD

**Issue by oiqgj** [nativewind/nativewind#1113]
I am using Expo Router, and when trying to apply vars as suggested in the documentation, I am encountering an unexpected error.

![image](https://github.com/user-attachments/assets/39e46294-4659-4ffb-bbb4-739122283c1a)
![image](https://github.com/user-attachments/assets/b34c930a-5b10-47c2-b41c-ae792d10bc8d)

**Comment by oiqgj** [comment]
I found that it works correctly on the web. However, on mobile devices, using vars returns an empty object and doesn't update the colors in :root as expected.

Could this be an issue specific to mobile environments or something related to the handling of CSS variables in the mobile context?

**Comment by oiqgj** [comment]
Sorry, the problem was actually between the chair and the keyboard

**Comment by JuliusSchumacher** [comment]
@oiqgj Mind explaining what you did wrong, and how you fixed it? I'm suspecting I'm having the same issue!

**Comment by oiqgj** [comment]
My issue was caused by the values I was passing to vars, like {" :root": {"--variable": "0 0 0"}}
I'm doing it like this now:
![image](https://github.com/user-attachments/assets/bc5f07f4-ef71-4add-9752-fbfb41f7a1de)

**Comment by oiqgj** [comment]
feel free to hit me up on discord (oiqgjoiqgj) if you need more details, I’ll be happy to help!

**Comment by AshciR** [comment]
> I'm trying to figure this out too. I'm using Gluestack and trying to access the colours it defines in gluestack-ui-provider/config which is in the form `export const config = { light: vars({ "--color-primary-0": "179 179 179",`
> 
> On web I can simply import config and reference it, config[colorScheme]["--color-primary-0"]. But on native it returns an empty object.

@DrMoshtael I'm running into the same issue. I get an empty object

**Comment by AshciR** [comment]
I noticed 
```
export { cssInterop, remapProps, useColorScheme, useUnstableNativeVariable, vars, } from "../web/api";
```

in `node_modules/react-native-css-interop/dist/runtime/native/index.js`

I would not expect the native version to export from the web api

**Comment by rohankm** [comment]
facing same problem here

**Comment by shubhenduyednap** [comment]
I'm running into the same issue. I get an empty object

**Comment by mordonez-me** [comment]
Looks like this is not working in native, I am having the same problem, ok in web, empty object in native.

**Comment by antoinersw** [comment]
It would be nice if we could have a clear documentation for theming for mobile builder

**Comment by tselmek** [comment]
Running into the same issue, has anyone found a solution or a workaround?

This issue https://github.com/nativewind/nativewind/issues/1027 seems to imply that the object is not human-interactible, thus explaining why we can't log the values. Is there a way to debug it?
