### ISSUE TITLE
Styles aren't being applied when using function syntax on Pressable component

### ISSUE THREAD

**Issue by TowhidKashem** [nativewind/nativewind#1128]
**Describe the bug**
When using the [Pressable](https://reactnative.dev/docs/pressable) component from react native you can show a pressed color like so:

```
      <Pressable
        onPress={() => {
          setTimesPressed(current => current + 1);
        }}
        style={({pressed}) => [
          {
            backgroundColor: pressed ? 'rgb(210, 230, 255)' : 'white',
          },
          styles.wrapperCustom,
        ]}>
        .....
        </Pressable>
```

But this isn't working when nativewind is installed. I'm not sure what's to blame, whether it's the babel plugin, nativewind itself or something else but it started happening after I followed the instructions for installing nativewind.

**Comment by marklawlor** [comment]
NativeWInd doesn't support function style callbacks. Use the `active:` modifier instead

**Comment by TowhidKashem** [comment]
> NativeWInd doesn't support function style callbacks. Use the `active:` modifier instead

I meant I have that bit of code in a component on my codebase already, I thought nativewind wouldn't affect existing code using inline styles like that. But now that stopped working after installing nativewind.

**Comment by marklawlor** [comment]
NativeWind works at the `jsx` level, so its applied to all components. If you wish to disable it for a specific component you can pass the prop `<Pressable cssInterop={false} />`

**Comment by TowhidKashem** [comment]
> NativeWind works at the `jsx` level, so its applied to all components. If you wish to disable it for a specific component you can pass the prop `<Pressable cssInterop={false} />`

perfect, just what I needed. Thanks!
