### ISSUE TITLE
Variable color is not working when inside react navigation in version 4.1.12.

### ISSUE THREAD

**Issue by tunahan-guler** [nativewind/nativewind#1130]
I extended the textColors in the tailwind.config.js for NativeWind, where I have `primary: "red"` and `"variable-primary": 'var(--color-text-primary)'`. The primary `color: "red"` works everywhere, both inside and outside the navigation, but the color I set as a variable only works outside the navigation. Below is the project repository.

The issue occurred after upgrading to Version` 4.1.12`

Here is the repo [link.](https://github.com/tunahan-guler/mob2)

**Comment by tunahan-guler** [comment]
> And sometimes i get this error when change className attributes.
>
> <img width="309" alt="Screenshot 2024-10-10 at 11 35 58" src="https://github.com/user-attachments/assets/ba18c7fc-eb8d-4bd7-93ad-904a88c6081f">

This is the another issue.

**Comment by sakhnyuk** [comment]
Same issue

**Comment by marklawlor** [comment]
Variable issue fixed in `4.1.13`. I'm not sure about that other issue, I was unable to reproduce it. Can you please create another issue with a reproduction if your able to isolate it
