### ISSUE TITLE
Broken monorepo after upgrading to 4.1.11 (or later) from 4.1.10

### ISSUE THREAD

**Issue by Jonatthu** [nativewind/nativewind#1132]
The next configuration used to work in 4.1.10 but broken after any version from 4.1.11 to 4.1.15
```
const { theme } = require('../../packages/react-native/src/base.tailwindcss.js');

/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		'./src/*.{js,jsx,ts,tsx}',
		'./src/**/*.{js,jsx,ts,tsx}',
		'../../packages/react-native/src/**/*.{js,jsx,ts,tsx}',
	],
	presets: [require('nativewind/preset')],
	darkMode: 'media',
	theme: {
		...theme,
		extend: {
			...theme.extend,
		},
	},
	plugins: [],
};

```

**Comment by marklawlor** [comment]
If your monorepo is broken I need a reproduction with your monorepro structure and lockfiles. Providing a single config file provides no information about your monorepro.

**Comment by hassankhan** [comment]
@marklawlor I have a sample nx monorepo containing an Expo app using Expo Router. I tried to add NativeWind to it in [this branch](https://github.com/twodoorsdev/kittygram/tree/experiment/add-nativewind) by following the instructions from NativeWind v4 documentation.

**Comment by Alimobasheri** [comment]
I was able to fully integrate NativeWind into our Nx monorepo which uses pnpm, using the following configs:

`metro.config.js`:
```js
const { withNxMetro } = require('@nx/expo');
const { getDefaultConfig } = require('@expo/metro-config');
const { mergeConfig } = require('metro-config');
const { withNativeWind } = require('nativewind/metro');

const defaultConfig = getDefaultConfig(__dirname);
const { assetExts, sourceExts } = defaultConfig.resolver;

/**
 * Metro configuration
 * https://reactnative.dev/docs/metro
 *
 * @type {import('metro-config').MetroConfig}
 */
const customConfig = {
  cacheVersion: 'palm-mobile',
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: assetExts.filter((ext) => ext !== 'svg'),
    sourceExts: [...sourceExts, 'cjs', 'mjs', 'svg'],
  },
};

async function createConfig() {
  const nxConfig = await withNxMetro(mergeConfig(defaultConfig, customConfig), {
    debug: false,
    extensions: [],
    watchFolders: [],
  });

  const nativeWindConfig = withNativeWind(nxConfig, {
    input: './src/global.css',
  });
  nativeWindConfig.resetCache = true;
  return nativeWindConfig;
}

module.exports = createConfig();
```

`tailwind.config.js`:
```js
const { createGlobPatternsForDependencies } = require('@nx/react/tailwind');
const { join } = require('path');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    join(
      __dirname,
      '{src,pages,components,app}/**/*!(*.stories|*.spec).{ts,tsx,html}'
    ),
    ...createGlobPatternsForDependencies(__dirname),
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

`.babelrc.js`:
```js
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ['babel-preset-expo', { jsxImportSource: 'nativewind' }],
      'nativewind/babel',
    ]
  };
};
```

I hope this can help you, as it took me a lot of time to find these fixes :)

**Comment by jrusso1020** [comment]
@Alimobasheri I validated your changes also seem to fix it for me!

**Comment by danstepanov** [comment]
going to close this as there seems to be a solution. @marklawlor and I will revisit tomorrow to determine whether we should make adjustments to the docs or NativeWind itself

**Comment by RussMax783** [comment]
Hey @Alimobasheri I've been running into the same exact thing and have implemented those adjustments but am still running into a couple things. I'm curious as to where you put those files in respects the your nx project. Did everything go at the root directory or did you put them in the app/project level?

**Comment by Alimobasheri** [comment]
@RussMax783 All of these are put in `app/project` level. What's your issue? Probably it could be a different issue.

**Comment by RussMax783** [comment]
Thanks for the response! I think the main difference is that you're using the expo babel config and my app was created a while ago with create-react-native-app so its using:
```
presets: [
  ['module:@react-native/babel-preset', {useTransformReactJSX: true}],
],
```
which i'm pretty sure is the issue. I'll have to try switching over to see if makes a difference.

**Comment by kirstilynn** [comment]
@Alimobasheri I have the same working configuration and have noticed on my eas build commands the styles don't get generated and it seems to be related to the `createGlobPatternsForDependencies` failing. If I do an OTA, it fixes my styles. Under the `Bundle JavaScript` step in my initial expo build I see the error:

```
WARNING: There was an error creating glob patterns, returning an empty array
[readCachedProjectGraph] ERROR: No cached ProjectGraph is available.
If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.
If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
```

Curious if you have run into this issue as well or if I have some missing configuration somewhere. Thanks!

**Comment by Alimobasheri** [comment]
Hi @kirstilynn, apologies for the delayed response. I haven’t encountered this specific issue because I was never able to get my online EAS builds to work due to other errors. However, I did manage to get local Android builds working by adding custom scripts to the post-install and pre-install steps, though this was unrelated to NX project graphs.

I’m glad you were able to resolve the issue! I know NX + React Native can be quite frustrating, and I’ve recently come to the conclusion that this combination might not be worth the trouble.

**Comment by iranaahsanali** [comment]
@RussMax783 Have you found any solution? 

I am facing same problem, which you faced before.

**Comment by rawr-code** [comment]
@iranaahsanali I already solved it https://github.com/nativewind/nativewind/discussions/542#discussioncomment-14598923
