### ISSUE TITLE
No overload matches this call.

### ISSUE THREAD

**Issue by Malberee** [nativewind/nativewind#1134]
On the version react-native@0.74.5 there is a type error when running the command `tsc --noEmit`. on react-native@0.74.1 there is no such error. I have the file nativewind-env.d.ts, the problem is not in it and it seems not in the version of nativewind, I tried both 4.0.36 and 4.1.14.
![image](https://github.com/user-attachments/assets/d9dde104-ad9c-40da-86b5-1f94756f824a)

**Comment by danstepanov** [comment]
closing as there is no repro https://nativewind.dev/issue
