### ISSUE TITLE
mix-blend not working

### ISSUE THREAD

**Issue by flikQ** [nativewind/nativewind#1146]
Have their been reports of the mix-blend feature (which is stated as fully supported) not working?

Not a lot more info to offer other than using any of the mix blend methods does nothing.

I am on v4.1.10 right now.

Have tested in 4.1.16 as well and no change.

**Comment by marklawlor** [comment]
Sorry the docs were published early. Mix blend will be supported shortly after React Native adds support in 0.76

**Comment by flikQ** [comment]
Ah understood, thanks for the clarification.
