### ISSUE TITLE
flex-1 not working on keyboard avodingview

### ISSUE THREAD

**Issue by umardev500** [nativewind/nativewind#1148]
```jsx
<KeyboardAvoidingView
      behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
      className="bg-red-200 flex-1">
      <View style={styles.inner}>
        <Text style={styles.header}>Header</Text>
        <TextInput placeholder="Usernamsde" style={styles.textInput} />
        <View style={styles.btnContainer}>
          <Button title="Submit" onPress={() => null} />
        </View>
      </View>
    </KeyboardAvoidingView>
```

if i use flex-1 in KeyboardAvoidingView its just fine make it full height but why the content is not scroll up?
if i use style props it's worked

**Comment by marklawlor** [comment]
`flex-1` sets multiple styles, it is shorthand for `flexGrow`/`flexShrink`/`flexBasis`. How flex styles behave is context dependant (e.g what are its parent styles). You need to isolate which of these 3 styles are causing your issue.

As you only provided a code snippet and not a reproduction, I cannot provide any more information than general advise.

If you would like further support please create a new issue and follow the issue template by providing a reproduction repro.
