### ISSUE TITLE
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. SHA-1 for file /home/expo/workingdir/build/node_modules/nativewind/node_modules/react-native-css-interop/.cache/android.js is not computed.

### ISSUE THREAD

**Issue by samuelvertello** [nativewind/nativewind#1155]
Error: @build-script-error-begin
Error loading assets JSON from Metro. Ensure you've followed all expo-updates installation steps correctly. SHA-1 for file /home/expo/workingdir/build/node_modules/nativewind/node_modules/react-native-css-interop/.cache/android.js is not computed.
Potential causes:
1) You have symlinks in your project - watchman does not follow symlinks.
2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
@build-script-error-end
    at createManifestForBuildAsync (/home/expo/workingdir/build/node_modules/expo-updates/utils/build/createManifestForBuildAsync.js:44:15)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 0)
    at /home/expo/workingdir/build/node_modules/expo-updates/utils/build/createUpdatesResources.js:26:5
> Task :app:createReleaseUpdatesResources
FAILED
FAILURE:
Build failed with an exception.
* What went wrong:
Execution failed for task ':app:createReleaseUpdatesResources'.
>
Process 'command 'node'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 8m 44s

I came across this error below when I tried to build my expo project with EAS. I have already cleared the metro cache, deleted the node_modules folder and reinstalled the dependencies. And it was working before, because I had already built my project in EAS.

dependency versions:
nativewind: 4.1.17
expo: 51.0.38
tailwind: 3.4.4

**Comment by MrPiao** [comment]
Related to #1158

**Comment by TCGXR** [comment]
Hi,
same here:

windows, react native without Expo
"nativewind": "^4.1.21",
"tailwindcss": "^3.4.14"

https://github.com/TCGXR-ORG/ERROR_1167.git

Task :app:createBundleReleaseJsAndAssets
debug Reading Metro config from C:\Dev\tcgxr_app\react_app\metro.config.js
warning: the transform cache was reset.
Welcome to Metro v0.80.12
Fast - Scalable - Integrated

error SHA-1 for file C:\Dev\tcgxr_app\react_app\node_modules\react-native-css-interop.cache/android.js is not computed.
Potential causes:

    You have symlinks in your project - watchman does not follow symlinks.
    Check blockList in your metro.config.js and make sure it isn't excluding the file path.
    ReferenceError: SHA-1 for file C:\Dev\tcgxr_app\react_app\node_modules\react-native-css-interop.cache/android.js is not computed.
    Potential causes:
    You have symlinks in your project - watchman does not follow symlinks.
    Check blockList in your metro.config.js and make sure it isn't excluding the file path.
    at DependencyGraph.getSha1 (C:\Dev\tcgxr_app\react_app\node_modules\metro\src\node-haste\DependencyGraph.js:179:13)
    at Transformer._getSha1 (C:\Dev\tcgxr_app\react_app\node_modules\metro\src\Bundler.js:15:26)
    at Transformer.transformFile (C:\Dev\tcgxr_app\react_app\node_modules\metro\src\DeltaBundler\Transformer.js:88:19)
    at Bundler.transformFile (C:\Dev\tcgxr_app\react_app\node_modules\metro\src\Bundler.js:43:30)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
