### ISSUE TITLE
RN 0.69.12 Cannot read properties of undefined (reading 'getSha1')

### ISSUE THREAD

**Issue by christophby** [nativewind/nativewind#1161]
**Describe the bug**

With react-native 0.69.12 I'm getting the following error.
Also with a fresh 0.69.12 project.

```
/node_modules/metro-hermes-compiler/src/emhermesc.js:404
      throw e;
      ^

RuntimeError: abort(TypeError: Cannot read properties of undefined (reading 'getSha1')). Build with -s ASSERTIONS=1 for more info.
    at process.abort (node_modules/metro-hermes-compiler/src/emhermesc.js:402:15)
    at process.emit (node:events:517:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)

```

**Reproduction**
* Checkout [fresh react native 0.69.12 project](https://github.com/christophby/Awesome6912)
* `yarn install` && `npx pod-install`
* Start packager
* Start app

Project uses
* react-native 0.69.12
* nativewind 4.1.20
* react-native-reanimated 3.11.0

**Expected behavior**
No Errors when starting app

**Comment by marklawlor** [comment]
Please try `4.1.21`

**Comment by christophby** [comment]
@marklawlor same behaviour as before. As soon as I start the packer `watchman watch-del-all && yarn start --reset-cache` I'm getting the same error. You might check my reproduction repo from above.

> node_modules/metro-hermes-compiler/src/emhermesc.js:404
      throw e;
      ^
RuntimeError: abort(TypeError: Cannot read properties of undefined (reading 'getSha1'))

**Comment by marklawlor** [comment]
How was this project created? Its running `@react-native-community/cli@8` (7 major versions behind), hence is running Metro 0.70 (10 major versions behind)

**Comment by marklawlor** [comment]
Oh damn, `react-native` has an outdated `dependancy` in its package.json. That is unfortunate, as Metro has had a number of improvements since then.

I'll do a backwards compatible fix for people, but I would recommend moving to Expo (which is running Metro 0.81) or forcefully updating the community cli.

**Comment by marklawlor** [comment]
I'm going to close this as "won't fix". As per the React Native website, 0.69 is no longer maintained by Meta and as such, not supported by NativeWind. Reference: https://reactnative.dev/versions

**Comment by taneba** [comment]
The same thing happened on RN 0.76.3 but solved after delete node_modules and installed deps again.
