### ISSUE TITLE
EAS Build on iOS fails with expo-updates

### ISSUE THREAD

**Issue by MrPiao** [nativewind/nativewind#1162]
**Describe the bug**
Similar to #1158, but for iOS. EAS build fails when `expo-updates` package is installed. I was able to repro this build failure using `nativewind@4.1.19` and `expo-updates@0.25.27`. Previously, in my actual project, I was also able to repro the failure using `nativewind@4.1.20`.

**Reproduction**
1. Generate the project using `npx create-expo-stack@latest --nativewind --expo-router`
2. Install updates using `npx expo install expo-updates`
3. Run EAS build using `eas build -p ios --profile preview --local`. Some EAS configuration was necessary to get this build kicked off.

The repro is available at https://github.com/MrPiao/nativewind-expo-updates-ios-repro sans the EAS config.

**Expected behavior**
Build succeeds.

**Actual behavior**
Build fails with the following message:

> [RUN_FASTLANE] › Executing expo-updates Pods/EXUpdates » [CP-User] Generate updates resources for expo-updates
[RUN_FASTLANE]
❌  error: SHA-1 for file /private/var/folders/6n/z_kx6kxj30j5tpbr0tjxs0gw0000gn/T/eas-build-local-nodejs/598ae794-2d02-462e-a221-03f3126b6881/build/node_modules/react-native-css-interop/.cache/ios.js is not computed.
> 
> 
> [RUN_FASTLANE]
❌ Metro encountered an error:
SHA-1 for file /private/var/folders/6n/z_kx6kxj30j5tpbr0tjxs0gw0000gn/T/eas-build-local-nodejs/598ae794-2d02-462e-a221-03f3126b6881/build/node_modules/react-native-css-interop/.cache/ios.js is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.
Learn more: https://docs.expo.dev/build-reference/troubleshooting

EDIT:
**Workaround**
For **this specific error**, reverting to NativeWind 4.1.10 will unblock the EAS build. There are other similar errors floating around, and I don't think those are the same issues.

**Comment by MrPiao** [comment]
Discussion also going on in Discord: https://discord.com/channels/968718419904057416/1295062307784626269

**Comment by MrPiao** [comment]
Rolling back to 4.1.10 has unblocked me for now

**Comment by GMoon777** [comment]
Same problem here

NativeWind v4.1.20
Expo updates v0.25.27

❌  error: SHA-1 for file /Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js (/Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js) is not computed.

❌ Metro encountered an error:
SHA-1 for file /Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js (/Users/expo/workingdir/build/node_modules/react-native-css-interop/.cache/ios.js) is not computed.
         Potential causes:
           1) You have symlinks in your project - watchman does not follow symlinks.
           2) Check `blockList` in your metro.config.js and make sure it isn't excluding the file path.

**Comment by JeanDes-Code** [comment]
I had the same error yesterday with Nativewind `4.1.10` and I'm still getting the error with Nativewind `4.1.20`.
I have `"expo-updates": "~0.25.14"`

**Comment by marklawlor** [comment]
Please try `4.1.21`

**Comment by samtsai** [comment]
> Please try `4.1.21`

This version worked for me

**Comment by MrPiao** [comment]
4.1.21 seems to work for me as well, at least on local. Will try cloud later

**Comment by TCGXR** [comment]
I am already using 4.1.21 and still hvae the error.

**Comment by chocsx** [comment]
fixed after updating to 4.1.21 version and removing node_modules, android and ios folder
