### ISSUE TITLE
[Doc] Please add `react-native-safe-area-context` as a peer dependency in the installation section

### ISSUE THREAD

**Issue by cxa** [nativewind/nativewind#1168]
Started a clean project by following the instructions on [NativeWind's getting started guide](https://www.nativewind.dev/getting-started/react-native), but encountered the following error:

```sh
Unable to resolve "react-native-safe-area-context" from "node_modules/react-native-css-interop/dist/runtime/third-party-libs/react-native-safe-area-context.native.js"
```

I suggest adding `react-native-safe-area-context` as a peer dependency in the installation section.

**Comment by hirbod** [comment]
While I think every single project needs react-native-safe-area-context, it's also possible to make it optional, like other libs.

https://github.com/gorhom/react-native-bottom-sheet/blob/4f26c7825e77ea00a227e13e64e023f6c2b1e679/src/components/bottomSheetScrollable/BottomSheetFlashList.tsx#L12-L19

**Comment by danstepanov** [comment]
@cxa can you provide a repro of the project set up that leads to this error? There are a number of ways to "get started"

**Comment by cxa** [comment]
With `pnpm create expo-app --template blank-typescript@beta`.

**Comment by danstepanov** [comment]
@cxa as far as i know, create expo app + nativewind is broken, on the list of things to fix but have you considered using `npx create-expo-stack@latest`?

**Comment by cxa** [comment]
I found @marklawlor have added `react-native-safe-area-context` to the doc, so I close this issue. Thanks for concern.
