### ISSUE TITLE
[BUG] Doesn't seem to work on a new Expo project

### ISSUE THREAD

**Issue by ospfranco** [nativewind/nativewind#1170]
**Describe the bug**
I was seeing some visual bugs in my app and wanted to try in a brand new expo project. Created a new project then followed the instructions but now I'm faced with this error (even after installing expo-constants) and a blank screen

<img src="https://github.com/user-attachments/assets/c72fbaa2-fece-4951-aa46-f773fe59b617" width="200"/>

<img src="https://github.com/user-attachments/assets/3a25e985-8ecb-4eb6-aebf-3cea67198b4c" width="200"/>

**Reproduction**
I did not use a template, but manually followed the instructions on the nativewind website here is a reproducible example:

https://github.com/ospfranco/nativewind-test

**Comment by janwiebe-jump** [comment]
this doesnt look like a nativewind issue to me.
Did you restart your metro and rebuild the app after the expo constants installation?


I took your repo and ran a npm run ios:
 
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-10-28 at 10 03 29](https://github.com/user-attachments/assets/9bec42b4-e3cd-4d4c-a21a-3a52e053e159)

**Comment by ospfranco** [comment]
Yeah, did both. TBH doesn't matter. I will close this, probably some cache error, but not important.
