### ISSUE TITLE
`safeList` does not work in v4

### ISSUE THREAD

**Issue by albingroen** [nativewind/nativewind#1171]
**Describe the bug**
The `safeList` field in `tailwind.config.js` does not work at all in v4.

**Reproduction**
Upgrade to v4.1

**Expected behavior**
The `safeList` field should work as it did in v2.

**Comment by marklawlor** [comment]
The field is `safelist`.

NativeWind does not change how TailwindCLI works. We process the output of TailwindCLI, so if `safelist` is not working for you then you need to investigate why TailwindCLI is not generating the correct CSS
