### ISSUE TITLE
Height doesnt equate style height number

### ISSUE THREAD

**Issue by oscadev** [nativewind/nativewind#1173]
I have an input (ios react native), and when I add h-12 (which should be height 48px), it only makes it like 42px (something slightly smaller than 48), but adding style height:48, works correctly. Havent tried with all other height values but it may just be h-12 that this happens with.

**Comment by marklawlor** [comment]
No, `h-12` is equal to `3rem`. NativeWind uses an `rem` value of 14 to match the default font size.

If you do not like this scaling, then you can override it in your `tailwind.config.js` or change NativeWinds rem value.
