### ISSUE TITLE
Classes not being applied on Animated.View [NW 4.1.23] [React Native Reanimated 3.16.1] [Web Build]

### ISSUE THREAD

**Issue by amandaharlin** [nativewind/nativewind#1181]
**Describe the bug**
After upgrading React-Native-Reanimated, I noticed that NativeWind was no longer getting its classes applied to an animated view. 

When RNReanimated was at `3.10.1` and NativeWind was at `4.1.21`, and also at `4.1.23`, the NW classes were applied correctly to the Animated.View. After upgrading reanimated to 3.16.1, the class names are now no longer being applied.

I wanted to log this in case NW needed to know if something changed with RNReanimated at 3.16.1. (I opened a [ticket with react-native-reanimated too](https://github.com/software-mansion/react-native-reanimated/issues/6665)) 

| Working Project Details | Not-Working Project Details |
|--------|--------|
| Expo `52.0.0-preview.18` | Expo `52.0.0-preview.18` |
| React NativeReanimated `3.10.1` | React NativeReanimated at `3.16.1` |
| NativeWind at `4.1.21` | NativeWind at `4.1.21` |

**Reproduction**Please see our contribution guide: 
- [gh repo repro here](https://github.com/amandaharlin/react-native-reanimated-nativewind-classname-repro)

Please provide a reproduction of the issue using one of the following templates:
  - I used `bun x create-expo-stack@latest --nativewind`
  - Add the example below* to test the Animated View class property
  - Check the web build (it works correctly, div does have classnames)
  - Upgrade reanimated to 3.16.1
  - Check the web build (the div that gets made does not have the classnames)
 
*Add the following example to app/(tabs)/index.tsx:
```tsx
<Animated.View
	className={"flex items-center justify-center bg-red-400"}
>
	<Image
		source={require("@/assets/images/react-logo.png")}
		width={100}
		height={100}
	/>
</Animated.View>
```

| reanimated 3.10.1 (classnames appear on div, works as expected) | reanimated 3.16.1 (classnames do not appear on div, doesn't work as expected)|
|--------|--------|
| ![Screenshot 2024-11-04 at 10 18 46 AM](https://github.com/user-attachments/assets/e08c5df1-5bba-425b-ba9b-1bf61b7f4561) | ![Screenshot 2024-11-04 at 10 20 16 AM](https://github.com/user-attachments/assets/e0c5c81a-902b-49a0-b7f7-df45456635a2) |

**Comment by amandaharlin** [comment]
I saw the discord uno reverse with the pinned issue. I'll try running with strict mode to test.

**Comment by marklawlor** [comment]
@camxus That is a non NativeWind issue. Please read the link in the error message.

**Comment by marklawlor** [comment]
This issue has been identified and is being tracked in the Reanimated/Builder Bob repro 

https://github.com/software-mansion/react-native-reanimated/issues/6665#issuecomment-2471878297

I'm going to close this issue to avoid multiple conversations

**Comment by camxus** [comment]
> @camxus That is a non NativeWind issue. Please read the link in the error message.

correct. this is a react-native-svg-transformer issue. thank you

**Comment by aldebout** [comment]
For people that stumble upon this like me: if it looks like className properties do not work on web for common libraries (bottom sheet, keyboard controller...) make sure react-native-reanimated > 3.16.3.
