### ISSUE TITLE
Leading decorators must be attached to a class declaration

### ISSUE THREAD

**Issue by ospfranco** [nativewind/nativewind#1187]
**Describe the bug**
Thanks a lot for all the work you put into the library!

I have a RN macOS project. I'm trying to update to the latest version of native wind from 4.0.36 to 4.1.23. Everything on the setup was working, but when I updated I started getting errors when importing the `global.css` file. Metro was complaining that decorators are not supported. After adding @babel/plugin-decorators-proposal it still fails with:

![CleanShot 2024-11-06 at 11 51 01@2x](https://github.com/user-attachments/assets/6e899075-d065-4c77-80dd-1dbbd317ec7c)

It seems it trying to interpret the .css file as JS file. It seems something broke on the bump to 4.1.x.

You can see my changes here and also run the project, you just need to install the deps and the pods and it should run

https://github.com/ospfranco/sol/compare/main...oscar/update-nativewind

**Comment by marklawlor** [comment]
I've tried to run your repro but I've run into various issues / missing configs / etc. As this is a volunteer project, I don't have time trying to troubleshoot how to run a project.

Are you able to replicate this issue with the React Native OSX starter template?

**Comment by ospfranco** [comment]
I will create a reproducible example later, no worries

**Comment by marklawlor** [comment]
I'm going to close this issue, please create a new issue when you have the reproducible repro.

However, I have been informed that you may get this error if you misconfigure your `metro.config.js` and add the incorrect path to the `input` option of `withNativeWind`

**Comment by dimglyn** [comment]
Any update here? I am having this issue when trying to build release android. ios and dev apk for android work fine...
