### ISSUE TITLE
`cssinterop` does not worked as expected: 1. customClassName can't be mapped. 2, nativeStyleToProp does not worked in web

### ISSUE THREAD

**Issue by BeaconSage** [nativewind/nativewind#1188]
**Describe the bug**

_**First, I think It's a bug for `react-native-css-interop`**_

1. `nativeStyleToProp` not work **on web**
```js
{
  className: {
    target: 'style',
    nativeStyleToProp: {
      color: 'themeColor', // `themeColor` is undefined  on web
    },
  },
}
```
2. `cssinterop` map customClassName not work **in all platform**
```js
{
  themeClassName: {
    target: false,
    nativeStyleToProp: {
      color: 'themeColor', // 'themeColor' is undefined 
    },
  },
}
```
**Reproduction**
https://snack.expo.dev/@beaconsage/nativewind-cssinterop

**Expected behavior**
1. `nativeStyleToProp` can work on web
2. `cssinterop` can map customClassName

**Additional context**
`package.json`
```json
{
  "dependencies": {
    "nativewind": "^2",
    "react-native-css-interop": "latest"
  }
}
```

**Comment by marklawlor** [comment]
NativeWind uses pure css for the web. It cannot do any prop mapping as the styles are in CSS not in javascript.

This is why the option is called `nativeStyleToProp` because it only works on `native` platform.
