### ISSUE TITLE
Custom component variants styles are not being applied

### ISSUE THREAD

**Issue by zanzlender** [nativewind/nativewind#1189]
**Describe the bug**
I am trying to create custom component with variants inspired by Shadcn components and by following the [NativeWind - How to write custom components](https://www.nativewind.dev/guides/custom-components).

However, when defining variants in a component the styles are not applied when using it.

However, setting styles in the **className** when using the custom component works as expected.

**Reproduction**
[Reproduction using the npx create-expo-stack@latest --nativewind --expo-router](https://github.com/zanzlender/nativewind-bug-report-components-not-applying-styles)

**Expected behavior**
Custom component styles should apply even when they are generated dynamically and set into className, instead of only working when statically written in className.

**Additional context**
When logging the styles that **should** get applied I get this (inside of the custom component):

![image](https://github.com/user-attachments/assets/f21bd42d-e1e2-42eb-8b04-5e699c07ea71)

```tsx
export function ThemedText({ className, variant, ...rest }: ThemedTextProps) {
  console.log(cn(themedTextVariants({ variant, className })));
  return <Text className={cn(themedTextVariants({ variant, className }))} {...rest} />;
}
```

However, they don't get applied if they aren't actually set statically inside of className.

```tsx
<Container>
        <View className="flex flex-1 flex-col items-center gap-10 px-4 py-12">
          <Text className="text-blue-600">Basic text - should be blue - set in classname</Text>

          <ThemedText className="text-red-500">
            Custom text - Should be red - set in classname when using component
          </ThemedText>

          <ThemedText>
            Custom component - default variant - should be green - set in component variant
            definitions
          </ThemedText>

          <ThemedText variant="default">
            Custom component with explicitly defined variant - should be green - set in component
          </ThemedText>

          <ThemedText variant="yellow">
            Custom component with non-default variant - should be yellow - set in component
          </ThemedText>
        </View>
      </Container>
```

outputs

![image](https://github.com/user-attachments/assets/98ada0b6-7960-4df7-a0e4-23d5d344f678)

**Comment by marklawlor** [comment]
`content: ['./app/**/*.{js,jsx,ts,tsx}'],`

Your `tailwind.config.js` is only collecting styles from the `app` folder.

Here is the troubleshooting guide for future issues https://www.nativewind.dev/guides/troubleshooting

**Comment by zanzlender** [comment]
tyvm!
