### ISSUE TITLE
Encountered issues when creating using the template, suspecting dependency conflicts

### ISSUE THREAD

**Issue by lapse12** [nativewind/nativewind#1190]
**Describe the bug**
I strictly followed the document for the project initialization, but... As shown in the figures, "Disconnected from Metro (1001: "Stream end encountered")."

**Reproduction**

I'd tried the following templates:

- **Create Expo Stack template**: 
  - `npx create-expo-stack@latest --nativewind --expo-router`(which in `create-expo-stack` branch)
  
and another which is `npx create-expo-app@latest`(which in `main` branch)

<img width="427" alt="image" src="https://github.com/user-attachments/assets/d3c7e60d-097e-4efc-bfbd-a6c19761ce55">
<img width="374" alt="image" src="https://github.com/user-attachments/assets/92b1760a-fdca-4538-bf4c-e106c1a191f6">

The issue seems to originate from the package "event-target-shim".

**Comment by lapse12** [comment]
sry, I justI forgot to leave the URL.

this is the minimal reproduction: https://github.com/lapse12/reproduction-of-nativewind-bug

**Comment by marklawlor** [comment]
This does not look like a NativeWind issue (more to do with networking on your machine). Do the templates work as expected before you add NativeWind?

**Comment by lapse12** [comment]
Yes, everything is normal except that Tailwind is not working.

**Comment by marklawlor** [comment]
I cloned your repro but I cannot reproduce the warnings you have reported.

However I can see on line 20 of `app/(tabs)/index.ts` you have added a `className` to `<ThemedText />`, so maybe your expecting that to work? The `<ThemedText />` is a custom component that wraps `<Text />`, however it is not passing the `className` prop to `<Text />` - hence it won't be styled.

If I pass the `className` prop correctly or just use `<Text />` directly the styles work as expected.

<hr />

As for your original issue, I'm still confused and feel that you need to explain the problem more clearly. "Everything is working" is a very broad term. I also don't know if "tailwind is not working" relates to your original issue about the warning, or simply the misuse of `className` prop.

What I need to concise information, basically instructions on how to reproduce the problem. For example

1. Start with a template project. No warnings or problem.
2. Follow the setup instructions  at https://www.nativewind.dev/getting-started/expo-router
3. Once you get to step 3 in the setup, if you run the project the problem occurs.

**Comment by lapse12** [comment]
Thank you very much for your careful and detailed reply. I found that the main issue was that I used the classname in the wrong scope (I didn't notice that the classname was not passed correctly).
