### ISSUE TITLE
Compiling JS Failed

### ISSUE THREAD

**Issue by ikotsov** [nativewind/nativewind#1193]
**Describe the bug**
After upgrading from `2.0.11` to `4.1.23` version, I cannot build my app. As you can see from the screenshot the build fails. It might be connected to the metro configuration (?), it seems that for some reason metro does not see the index.js file. I am on a managed expo installation using react-navigation.

This is my metro configuration:
```
/* eslint-env node */

// Learn more https://docs.expo.io/guides/customizing-metro
// eslint-disable-next-line import/order
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

/**
 * Storybook configuration
 * https://github.com/storybookjs/react-native/blob/next/MANUAL_SETUP.md#metroconfigjs
 */
const path = require('path');
// eslint-disable-next-line import/order
const { generate } = require('@storybook/react-native/scripts/generate');

generate({
  configPath: path.resolve(__dirname, './.storybook')
});

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

// Needed for Storybook
config.transformer.unstable_allowRequireContext = true;

const { transformer, resolver } = config;

// Needed for SVG transformer
config.transformer = {
  ...transformer,
  babelTransformerPath: require.resolve('react-native-svg-transformer/expo')
};
config.resolver = {
  ...resolver,
  assetExts: resolver.assetExts.filter(ext => ext !== 'svg'),
  sourceExts: [...resolver.sourceExts, 'svg']
};

module.exports = withNativeWind(config, { input: './global.css' });
```

I have double checked with other popular boilerplate libraries, such as Obytes, in order to see if the configuration (tailwind config, babel etc) is correct and it looks fine.

I also tried to remove one by one my other metro configs in order to make sure it has to do with native wind and the problem remained.

My version of tailwind css is: `3.4.14`

Any propositions would be very helpful.

**Expected behavior**
The build runs successfully.

**Additional context**
![Simulator Screenshot - iPhone 13 Pro - 2024-11-06 at 17 39 19](https://github.com/user-attachments/assets/801f7410-4c6a-4c53-a8dd-23506dd96a80)

**Comment by marklawlor** [comment]
Working backwards (removing things until it works) is a good troubleshooting step, but only really works when you understand the problem. Because if you don't know where the problem is, how do you know what to remove? The problem probably isn't with your Metro config.

I recommend you take the opposite approach. Start a new template project (https://rn.new) and slowly move parts of your project across to the new template. This way your starting with something that works and as you slowly move things across is will suddenly break. You don't need to migrate your entire app (screens/components don't really affect the build), just your configuration.

I'm going to close this issue because its not isolated to NativeWind at this stage and there isn't a minimal reproduction repro. If you isolate the issue (e.g when I make this NativeWind change to the template project it breaks), please create a new issue with a link to the template project. Its very difficult to troubleshoot an issue without code to run

**Comment by redkean** [comment]
in my case, this stems from `tailwind.config.js` having content to `'../../packages/**/*.{js,jsx,ts,tsx}'`

```js
const { theme } = require('app/design/tailwind/theme');

/**
 * @type {import('tailwindcss').Config}
 */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    '../../packages/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  important: true,
  theme: {
    ...theme,
  },
  plugins: [],
};
```

i have a monorepo setup

**Comment by redkean** [comment]
I have investigated further and found the culprit:

`group-[&:has(~div[aria-selected="true"])]/step:hidden`

this classname fails js compilation.

**Comment by ikotsov** [comment]
> I have investigated further and found the culprit:
> 
> `group-[&:has(~div[aria-selected="true"])]/step:hidden`
> 
> this classname fails js compilation.

Great catch! It might be a compiler issue then.

**Comment by redkean** [comment]
might be worth opening another issue?

**Comment by redkean** [comment]
```diff
diff --git a/node_modules/react-native-css-interop/dist/metro/index.js b/node_modules/react-native-css-interop/dist/metro/index.js
index c91ba6a..65848b9 100644
--- a/node_modules/react-native-css-interop/dist/metro/index.js
+++ b/node_modules/react-native-css-interop/dist/metro/index.js
@@ -240,7 +240,7 @@ function stringify(data) {
         case "function":
             throw new Error(`Cannot stringify ${typeof data}`);
         case "string":
-            return `"${data}"`;
+            return JSON.stringify(data);
         case "number":
             return `${Math.round(data * 1000) / 1000}`;
         case "boolean":
@@ -267,7 +267,7 @@ function stringify(data) {
                         return [];
                     }
                     if (key.match(/[^a-zA-Z]/)) {
-                        key = `"${key}"`;
+                        key = JSON.stringify(key);
                     }
                     value = stringify(value);
                     return [`${key}:${value}`];
```

this fixed the issue for me.
