### ISSUE TITLE
Does not work if App.js is in a folder

### ISSUE THREAD

**Issue by jokeruarwentto** [nativewind/nativewind#132]
**Describe the bug**
I'm trying to use ``nativewind`` package, I have my ``App.js`` in ``/src/`` folder, and Tailwind does not work at all.

**To Reproduce**
1. Create a fresh project using ``npx create-react-native-app``
2. Install ``nativewind`` package
3. Put ``App.js`` in a new directory called ``src``
4. Initialize Tailwind configuration file
5. Put ``content`` to ``["./src/**/*.{js,jsx,ts,tsx}"]``
6. Launch the app using ``yarn android``

**Expected behavior**
Simply working example as the docs.

**Comment by marklawlor** [comment]
Can you please publish a public repo demonstrating your issue. Note that tailwind content globs are relative to the current working directory, not the config file.

**Comment by marklawlor** [comment]
I'm unable to replicate your issue. Can you try clearing your babel cache `yarn start -c`
