### ISSUE TITLE
Nativewind V4.1.23 | className styles override issue with breakpoints

### ISSUE THREAD

**Issue by Aximem** [nativewind/nativewind#1324]
**Describe the bug**
When you want to override a "default" style set on breakpoint, the priority applied is not the same as in the V2, it always takes the "breakpoint" style, see example below.

**Reproduction**
Following code:    
`<View className="h-10 bg-red-300 sm:my-4 md:my-5 lg:my-6 m-0" />`

In NativeWind V2 (2.0.11), the margin applied is `m-0`.   
In NativeWind V4 (4.1.23), the margin applied is `sm:my-4 md:my-5 lg:my-6` depending on device breakpoint.

**Expected behavior**
The style applied at the end should override "breakpoint" style. 

**Additional context**
We also tried to use cva and cn but it doesn't change anything, the "breakpoint" style is never overrided. The only solution we found at to override the style is to do:
`<View className="h-10 bg-red-300 sm:my-4 md:my-5 lg:my-6 sm:my-0 md:my-0 lg:my-0" />`

**Comment by marklawlor** [comment]
NativeWind V4 aligns with the CSS specification of following CSS specificity. This ensures the styles work the same across all platforms.

The Tailwind team recommends using the prettier plugin to sort your styles in specifically order
