### ISSUE TITLE
[v4] EACCES: permission denied, mkdir... /node_modules/react-native-css-interop/.cache

### ISSUE THREAD

**Issue by IlirEdis** [nativewind/nativewind#1327]
**Describe the bug**

Here is the whole log: 

```
npx expo start -c
Starting project at /Users/ilirbajrami/Desktop/MyApp
env: load .env
env: export EXPO_PUBLIC_APP_BASE_URL EXPO_PUBLIC_API_BASE_URL VERTEX_PROJECT_ID EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY STRIPE_SECRET_KEY EXPO_PUBLIC_SUPABASE_URL SUPABASE_SERVICE_ROLE_KEY EXPO_PUBLIC_SUPABASE_ANON_KEY
Error: EACCES: permission denied, mkdir '/Users/ilirbajrami/Desktop/MyApp/node_modules/react-native-css-interop/.cache'
Error: EACCES: permission denied, mkdir '/Users/ilirbajrami/Desktop/MyApp/node_modules/react-native-css-interop/.cache'
    at Object.mkdirSync (node:fs:1379:3)
    at withCssInterop (/Users/ilirbajrami/Desktop/MyApp/node_modules/react-native-css-interop/src/metro/index.ts:75:6)
    at withNativeWind (/Users/ilirbajrami/Desktop/MyApp/node_modules/nativewind/src/metro/index.ts:42:24)
    at Object.<anonymous> (/Users/ilirbajrami/Desktop/MyApp/metro.config.js:8:18)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Function.Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)

```

**Additional context**

If i run `sudo npx expo start -c` i get this error:

```
› Opening on iOS...
› Opening exp://192.168.8.100:8081 on iPhone SE (3rd generation)
Could not update simulator linking permissions: ENOENT: no such file or directory, open '/Users/ilirbajrami/Library/Developer/CoreSimulator/Devices/739E5615-065E-4A3E-87F5-218EAA8604AB/data/Library/Preferences/com.apple.launchservices.schemeapproval.plist'
› Press ? │ show all commands
```

Related: https://github.com/expo/expo/issues/32779

My dependencies (probabaly related): 

```
    ...
    "@react-navigation/native": "^7.0.0",
    "clsx": "^2.1.1",
    "expo": "^52.0.7",
    "expo-build-properties": "~0.13.1",
    "expo-router": "~4.0.5",
    "expo-system-ui": "~4.0.3",
    "nativewind": "4.1.10",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.2",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.0.0",
    "react-native-tab-view": "^4.0.1",
    "react-native-web": "~0.19.10",
    "tailwind-merge": "^2.5.4",
    "tailwindcss": "^3.4.15",

```

I tried deleting `node_modules` and `package-lock.json`. Also tried deleting `.expo` folder. 
I also tried installing `react-native-css-interop` as an npm package but nothing fixed the issue.

**Comment by marklawlor** [comment]
This does not appear to be a NativeWind issue but an issue with permissions on your machine. NativeWind expects that the node process running has the same user permissions as the npm process, hence its should be able to create a folder.

When you look at your file system permissions of your node modules, what user do they belong to?

If you write a NodeJS script that generates a folder, does that folder have the same permissions as the ones created by npm?

**Comment by marklawlor** [comment]
The related issue you linked supports my hypothesis more. It appears you are also have the same issue with the Expo progress, which also has the same permission assumptions.


If your unsure how to resolve this issue, a simple solution would be to remove all versions of node/npm/whatever package manager your using and reinstall them.

**Comment by IlirEdis** [comment]
Removing and reinstalling node alone didn't fix my issue, but you sent me to the right direction. So, i had to fix permissions for `node_modules` and `.expo` folders and assign them to my user. Also for the simulator issue i had to completely uninstall the simulator and reinstall it. 

When my permissions got messed up...? i don't know!
However, thanks for the hint!
