### ISSUE TITLE
`dark:` modifier doesn't respond to `.dark` class

### ISSUE THREAD

**Issue by joshpensky** [nativewind/nativewind#1333]
**Describe the bug**

I'm currently switching over to Nativewind from [twrnc](https://www.npmjs.com/package/twrnc) and am running into one last issue! 

In our app, we're using `darkMode: 'class'` since we have the ability to override the theme from the system appearance.

We also have some view trees that should always be rendered in dark mode, while other views should respond to the system appearance. That ends up looking like this:

```tsx
<>
  <View className="dark">
    <SearchBar />
  </View>
  <AppContent />
</>
```

Most of our design system components rely on the `dark:` modifier to switch between colors and opacity values like so:

```tsx
<View className="bg-red-400 dark:bg-green-400">
```

However, the current version of Nativewind only supports the `dark:` modifier when it's defined at the system level. This means that the above View will never appear `bg-green-400` until the _system appearance_ is dark, not when there's a parent `.dark` class

**Reproduction**

https://stackblitz.com/edit/nativewind-test-qg93fr?file=nativewind.test.tsx

**Expected behavior**

When the `dark` class is applied to the current or a parent component, the `dark:` modifier class should be applied

```tsx
// Should be `bg-red-400` (OR `bg-green-400` when the system appearance is dark)
<View className="bg-red-400 dark:bg-green-400" />

// Should be `bg-green-400`
<View className="dark bg-red-400 dark:bg-green-400" />

// Should be `bg-green-400`
<View className="dark">
  <View className="bg-red-400 dark:bg-green-400" />
</View>
```

**Additional context**

For context, here's what our app [Marathon](https://marathontv.app) looks like. The search bar is always rendered in dark mode, while the app content below switches between light and dark mode with the system appearance

<img width="300px" src="https://github.com/user-attachments/assets/c148076c-a1b4-4104-a263-fb4c932065f9" />

**Comment by marklawlor** [comment]
NativeWind's dark mode doesn't work as your expecting it to. On native, the dark mode is controlled by React Native's `Appearance` module.

Dark mode normally refers to an app wide setting, but your usage is more like themes. So your kinda of misusing dark mode and are probably better using a TailwindCSS plugin for theming such as https://www.npmjs.com/package/tw-colors (you will need to use `class` instead of `data-theme`)

If you

**Comment by joshpensky** [comment]
Hey Mark, thanks for the speedy reply! Unfortunately, I think this only further uncovers the issue that Nativewind doesn't recognize parent class selectors

I've set up this small repro here: https://stackblitz.com/edit/nativewind-test-ejngt4?file=nativewind.test.tsx

Based on the library you sent, I created a simple Tailwind plugin that adds a `themed:` modifier, which is applied when there's a parent `themed` class:
```tsx
plugin(({ addVariant }) => {
  addVariant('themed', '.themed &');
}),
```

For a component like `<View className="themed:text-green">`, this produces the following CSS:
```css
.themed .themed\:text-green {
  color: green;
}
```

However, Nativewind isn't recognizing that a parent component has the `themed` class and so the text never turns green

**Comment by marklawlor** [comment]
NativeWind does not support parent class selectors or cascading CSS. You need to write atomic CSS.

The library I linked uses CSS variables to for theme colours. So the class `dark` just sets the variables for the theme.

**Comment by joshpensky** [comment]
Gotcha, thanks for the clarification!
