### ISSUE TITLE
rounded-s-passes or rounded-e-passes can not work on android side

### ISSUE THREAD

**Issue by Jianlong-Nie** [nativewind/nativewind#1335]
**Describe the bug**
"nativewind": "4.1.23", `rounded-s-passes` or `rounded-e-passes` are not working on Android

**Comment by marklawlor** [comment]
React Native does not support logical border radius.

We might add a polyfill in the future but until then this is expected behaviour and you should use the non-logical classes instead.

**Comment by Jianlong-Nie** [comment]
> React Native does not support logical border radius.
> 
> We might add a polyfill in the future but until then this is expected behaviour and you should use the non-logical classes instead.

@marklawlor but it can work fine ios side
