### ISSUE TITLE
[V4] text-color does not work

### ISSUE THREAD

**Issue by d0lim** [nativewind/nativewind#1340]
**Describe the bug**
text-color does not work.
It works partially only for `text-black` and `text-white`. When I applied `text-blue` or `text-red` to `react-native` `Text`, it shows me only black text.

Here's the example code I applied.

```typescript
import { Text, View } from 'react-native'

function HomeScreen() {
  return (
    <View className="flex-1 items-center justify-center">
      <Text className="text-[60px] text-red">
        Open up App.js to start working on your app!
      </Text>
    </View>
  )
}

export default HomeScreen
```

Here's the screenshots 

**Expo Go**
<img src="https://github.com/user-attachments/assets/f0e79bfd-8ad1-4b20-88bd-235c226c1e61" width="50%" />

**Expo Development Build**
<img src="https://github.com/user-attachments/assets/ee6048bd-aa2c-4d6b-a734-0bd63fa56548" width="50%" />

**Reproduction**
- **GitHub Repository** : https://github.com/d0lim/diet-planner
- `npx expo start -c`

**Expected behavior**
Applies proper color to `Text` components.

**Additional context**
.

**Comment by Lexdgr8est** [comment]
For text-red or blue... You need to add the alpha value

text-red-100 or text-red-200 till 700.

You can also install tailwindcss intellisense for more help. It will show you all valid props for any style

**Comment by d0lim** [comment]
@Lexdgr8est Oh, my bad. 
Just checked tailwindcss documentation and solved it!
Thanks for your help.

Closing the issue!
