### ISSUE TITLE
Native wind not working in expo sdk 52

### ISSUE THREAD

**Issue by justinelut** [nativewind/nativewind#1342]
I have upgraded my expo project to sdk 52 and native wind does not seem to work in the new architecture even after following all the installation instructions.

**Comment by marklawlor** [comment]
I'm am unsure how I'm meant to assist you  when you provide zero information, not even a link to your repro.

The default issue template asks for this information so we can assist you.

Closing this issue due to lack of information

**Comment by XnCN** [comment]
@marklawlor I have got same problem, i started with the clean project with "npx create-expo-app@latest" and install nativewind but not working.

![image](https://github.com/user-attachments/assets/2bf2663c-dcdc-4995-9b22-5c9d51c98c57)

**Comment by Youssef-Helal-Sharkawy-Kalds** [comment]
With the release of Expo SDK 52 and the adoption of the new architecture, the default project template created using npx create-expo-app@latest no longer includes the metro.config.js and babel.config.js configuration files. As a result, the method described in the [NativeWind quick start guide for Expo](https://www.nativewind.dev/v2/quick-starts/expo) is no longer functional and requires adjustments to accommodate the new project structure.

**Comment by marklawlor** [comment]
That guide is out dated and has a large warning at the top of the page

> This is documentation for NativeWind v2, which is no longer actively maintained.
> For up-to-date documentation, see the [latest version](https://www.nativewind.dev/) (v4).
