### ISSUE TITLE
Nativewind and tailwind classes not applying on my project with the latest expo version.

### ISSUE THREAD

**Issue by justinelut** [nativewind/nativewind#1344]
**Describe the bug**
I have enabled the new reactnative architecture with ```"newArchEnabled": true,``` in the app.json, and am using latest packages.
expo version :  "expo": "52.0.7",
Nativewind version : "nativewind": "^4.1.23",

I have just arrived from nextjs to react native and unfortunately as beginner in expo and react native, without console errors, am unable to debug anything. The app just runs fines, but tailwind classes are not applying.

**Reproduction**
```git clone https://github.com/justinelut/fundi-wangu```
```bun install```
```bun start```

Please provide a reproduction of the issue using one of the following templates:
here is my repo maybe someone can help me debug the issue
https://github.com/justinelut/fundi-wangu
after running the app, no errors, but nativewind is not applying

**Expected behavior**
The tailwind classes are supposed to apply to react native views, unfortunately no classes applies even after proper configuration of nativewind

**Additional context**

**Comment by marklawlor** [comment]
Can you please try using an proper file path to the input file in your metro.config.js. Tsconfig paths are not JavaScript and will not work here

**Comment by justinelut** [comment]
@marklawlor i have tried relative paths ```./src/global.css``` in the metrol config, and nothing worked, until i changed to to @ and left it like that because i couldnt figure the solution

**Comment by justinelut** [comment]
![image](https://github.com/user-attachments/assets/80588fd1-54f5-4d23-83d9-d5874d44908a)
i have updated the path to be relative, as you can see above, but below is login screen without tailwind classes applying
![Screenshot_20241124_115925_Expo Go](https://github.com/user-attachments/assets/41ef828f-d4de-4756-bda1-2c66aff7f304)

**Comment by marklawlor** [comment]
I do not understand why you have `react-native-css-interop` listed as a dependency. Every version of NativeWind depends on a specific version of that package, but installing it yourself you have created a dependency conflict.

By removing this package (and regenerating your `node_modules` and lock file and changing that paths to be non-tsconfig paths your app works as expected.
