### ISSUE TITLE
Issue with Nativewind and reactnavigation

### ISSUE THREAD

**Issue by ebnazmul** [nativewind/nativewind#1345]
**Describe the bug**
Telling me 'displayName' is undefined when using NativeWind, but it's working fine with normal React Native.

![image](https://github.com/user-attachments/assets/ffcd39f3-cd56-4691-a8a8-b4a844fd93cb)
![image](https://github.com/user-attachments/assets/916a1801-47eb-4b8c-9815-adb5c9048802)

**Expected behavior**
Working fine with both

**Comment by marklawlor** [comment]
NativeWind doesn't have a `View`/`Text` export, so those values are undefined.
