### ISSUE TITLE
variables not being applied in nativewind

### ISSUE THREAD

**Issue by Pukimaa** [nativewind/nativewind#1348]
**Describe the bug**
I defined my variables via an imported css file and in the tailwind config. The variables are shown when I open the debugger, so it's imported correctly. However when doing something like `bg-surface-primary` the actual color is just `rgb(0, 0, 0)`.
I already tried using the hex code, `R G B`, `rgb(R, G, B)` and embedding the colors directly into the tailwind config.

**Reproduction**
Unable to reproduce using the test suite.
Instead, here are some code snippets:
```
:root {
  --surface-primary: #0b0b0e;
  --surface-secondary: #151519;
  --surface-tertiary: #1f1f24;
 }
```
`<View className="size-2md bg-surface-primary" />`

**Expected behavior**
The background color should change to a dark color.

**Additional context**
![grafik](https://github.com/user-attachments/assets/81c6ca67-21a5-4264-a87c-afd035001244)

**Comment by marklawlor** [comment]
Please provide a reproduction repro with code that I can run. I cannot troubleshoot an issue though a screenshot
