### ISSUE TITLE
Styles are not working in react native web

### ISSUE THREAD

**Issue by Topiya** [nativewind/nativewind#1351]
I am using NativeWind in **Bare React native (not expo)** with below version.

> "react-native": "0.76.1"
> "nativewind": "^4.1.23"
> "tailwindcss": "^3.4.15" 

Tailwind styles are applying properly in App **but not applying in React native Web**.

I got one solution from internet as below

`npx tailwindcss -i ./global.css -o ./public/tailwind.css --watch`

But using above solution I need to save separate css file specially for web.

Can anyone please suggest any solution to get styles in **react native web**?

**Comment by marklawlor** [comment]
Only Expo's Metro config supports CSS imports. Even if your not using Expo, you can still use their Metro config for this to work automatically.

Otherwise you will need to manage the CSS generation/asset handling yourself

**Comment by Topiya** [comment]
Can I use Expo's Metro config @expo/metro-config in bare `react native 0.76.3` ?

If yes then can you tell me how to do it?

**Comment by marklawlor** [comment]
You can, but you will also need the CLI to serve the `.html` file with the style tag injected.

I don't provide instructions on how to use Expo.
