### ISSUE TITLE
v4 Forced Full Reload (Refresh) when changing classNames

### ISSUE THREAD

**Issue by codeAbinash** [nativewind/nativewind#1355]
It is reloading the app fully when a new className is added in any component. 
For those classNames which were already present, it is fast refreshing.

It should fast refresh when added new className in any component. 

I am using React Native CLI

```json
"dependencies": {
    "@react-native-community/netinfo": "^11.4.1",
    "@react-navigation/bottom-tabs": "^7.1.3",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/stack": "^7.0.18",
    "@tanstack/react-query": "^5.62.2",
    "axios": "^1.7.8",
    "lottie-react-native": "^7.1.0",
    "nativewind": "^4.1.23",
    "react": "18.3.1",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "^2.21.2",
    "react-native-mmkv": "^3.1.0",
    "react-native-otp-entry": "^1.7.3",
    "react-native-reanimated": "^3.16.3",
    "react-native-safe-area-context": "^4.14.0",
    "react-native-screens": "^4.3.0",
    "react-native-svg": "^15.10.0",
    "react-native-svg-transformer": "^1.5.0",
    "zustand": "^5.0.1"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@babel/preset-env": "^7.25.3",
    "@babel/runtime": "^7.25.0",
    "@react-native-community/cli": "15.0.1",
    "@react-native-community/cli-platform-android": "15.0.1",
    "@react-native-community/cli-platform-ios": "15.0.1",
    "@react-native/babel-preset": "0.76.3",
    "@react-native/eslint-config": "0.76.3",
    "@react-native/metro-config": "0.76.3",
    "@react-native/typescript-config": "0.76.3",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "babel-plugin-module-resolver": "^5.0.2",
    "eslint": "^9.16.0",
    "jest": "^29.6.3",
    "prettier": "^3.4.2",
    "prettier-plugin-tailwindcss": "^0.6.9",
    "react-test-renderer": "18.3.1",
    "tailwindcss": "^3.4.16",
    "typescript": "^5.7.2"
  },
```

metro.config.js
```js
const { getDefaultConfig, mergeConfig } = require('@react-native/metro-config')
const { withNativeWind } = require('nativewind/metro')
// const path = require('path')
const defaultConfig = getDefaultConfig(__dirname)
const { assetExts, sourceExts } = defaultConfig.resolver

/**
 * Metro configuration
 * https://facebook.github.io/metro/docs/configuration
 *
 * @type {import('metro-config').MetroConfig}
 */
const config = mergeConfig(defaultConfig, {
  transformer: {
    babelTransformerPath: require.resolve('react-native-svg-transformer'),
  },
  resolver: {
    assetExts: [...assetExts.filter((ext) => ext !== 'svg'), 'lottie'],
    sourceExts: [...sourceExts, 'svg'],
  },
})

module.exports = withNativeWind(config, { input: './global.css' })
```

babel.config.js
```module.exports = {
  presets: ['module:@react-native/babel-preset', 'nativewind/babel'],
  plugins: [
    'react-native-reanimated/plugin',
    [
      'module-resolver',
      {
        alias: {
          '@components': './src/components',
          '@icons': './src/assets/icons/src',
          '@images': './src/assets/images/src',
          '@assets': './src/assets',
          '@utils': './src/utils',
          '@screens': './src/screens',
          '@query': './src/query',
          '@': './src/',
        },
      },
    ],
  ],
  env: {
    production: {
      plugins: ['react-native-reanimated/plugin'],
    },
  },
}
```

Is there any solution for this?

**Comment by codeAbinash** [comment]
It was because I was also exporting a const with the export default component.

**Comment by divineniiquaye** [comment]
> It was because I was also exporting a const with the export default component.

Kindly explain futher what you mean by export default component, I facing the same issue

**Comment by arbarlow** [comment]
@divineniiquaye you can only have one export (usually the component/route itself) for Fast Refresh to work properly. If you have other components that are shared, placed them in a separate, commonly imported file

**Comment by ayush-goyal** [comment]
@arbarlow What do you mean by this? I have one component per file export, but I'm still running into this issue with forced full reload

**Comment by nandorojo** [comment]
I think this should get re-opened. I just tried a fresh nativewind project and I get the same issue. I can share a repro if needed.

**Comment by codeAbinash** [comment]
If one file is exporting a Component. It shouldn't export any other thing. Try this. It may work.

**Comment by evelant** [comment]
After nearly a decade developing react native apps how did I not know that fast refresh was tied to having files only export a single component?!?! This changes everything, thank you 🤣

**Comment by MartinCura** [comment]
I am on a codebase with many components and even in those that have only 1 export this happens, especially if i add/change a bg color. See also nativewind/nativewind#1714. Is this caused if _any_ file exports a component and something else? Why does it happen more with certain things like colors? Is there any way to avoid it as much as posssible in dev, even if it means a larger bundle or something? Thank you.

**Comment by emi0x7d1** [comment]
@MartinCura, can you check if you have the same problem I have? https://github.com/nativewind/nativewind/issues/1714#issuecomment-3055696375

**Comment by MartinCura** [comment]
> [@MartinCura](https://github.com/MartinCura), can you check if you have the same problem I have? [#1505 (comment)](https://github.com/nativewind/nativewind/issues/1714#issuecomment-3055696375)

Well it does sound like it.

Still having this annoyance, btw. Is there a way i could "preload" all tw classes somewhere while in dev so none is new? Maybe i'd experiment with that.

**Comment by MartinCura** [comment]
> Is there a way i could "preload" all tw classes somewhere while in dev so none is new? Maybe i'd experiment with that.

I copied [this list](https://github.com/tailwindlabs/tailwindcss/discussions/10379#discussioncomment-6398338) into a file and... for now it seems the reloads are gone? Awesome. Enough for me while developing, at least.

**Comment by divineniiquaye** [comment]
I downgraded my version to 4.1.20, and it fixed the reloading issue
