### ISSUE TITLE
darkMode styles does not get applied while colorScheme returns true

### ISSUE THREAD

**Issue by reanzi** [nativewind/nativewind#279]
Thanks for this package, coming from web devs, this package makes react-native feels like regular react. Thanks @marklawlor 

Trying to make darkMode to work, 

this is ``` App.js ``` file
```
const App = () => {
  const {colorScheme, toggleColorScheme} = useColorScheme();

/*
toggleColorScheme does work and colorScheme changes accordingly
StatusBar does change fine depending on the colorScheme value

but all utility classes prefixed with dark: does not work on dark mode
*/
  const backgroundStyle ='flex h-full justify-center items-center bg-red-200 dark:bg-slate-900';

  return (
      <SafeAreaView className='flex h-full justify-center items-center bg-red-200 dark:bg-slate-900'>
          <StatusBar
              barStyle={colorScheme === 'dark' ? 'light-content' : 'dark-content'}
              backgroundColor={backgroundStyle.backgroundColor}
          />
          <Pressable onPress={toggleColorScheme}>
              <Text className='text-2xl text-slate-700 py-5'>{`Try clicking me! ${
                  colorScheme === 'dark' ? '🌙 Dark' : '🌞 Light'
              }`}</Text>
          </Pressable>
          <Hello />
      </SafeAreaView>
  );
};
```
This is the ``` tailwid.config.js```
```
/** @type {import('tailwindcss').Config} */
module.exports = {
    darkMode: 'class',
    content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
    theme: {
        extend: {},
    },
    plugins: [],
};
```
What I'll be missing here?

**Comment by marklawlor** [comment]
If this is an Expo project can you please ensure you have correctly setup or project, including installing `expo-system-ui`

https://docs.expo.dev/guides/color-schemes/

**Comment by reanzi** [comment]
No it's not an expo project

**Comment by marklawlor** [comment]
Can you please share more information and a link to your repository

**Comment by reanzi** [comment]
Thanks @marklawlor for your lighting responses,
here is the repo [https://github.com/reanzi/MyShop.git](url)

I've simplified and put everything in ```App.js``` file, so it's an exactly copy of my local repo too

**Comment by reanzi** [comment]
@marklawlor  any thoughts?

**Comment by kevin-nguyen-mirvac** [comment]
Just a stab
- For your ios `Info.plist` ([link](https://github.com/reanzi/MyShop/blob/main/ios/vaccinet/Info.plist
)), I noticed there's no `UIUserInterfaceStyle` key/value pairs

https://docs.expo.dev/guides/color-schemes/#ios-configuration
https://developer.apple.com/documentation/bundleresources/information_property_list/uiuserinterfacestyle

**Comment by madly0894** [comment]
This problem still remains. Dark mode only works with withExpoSnack. When I add this HOC, only colors work. Other styles are disappearing

**Comment by marklawlor** [comment]
If you are experiencing this issue, please test the `next` version via `nativewind@next`. Please see #308 for more information

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
