### ISSUE TITLE
Add `styled()` option that maps `customClass` to `customStyle` for consistency with `className` to `style`

### ISSUE THREAD

**Issue by xxRockOnxx** [nativewind/nativewind#321]
**Describe the bug**

Not really a bug.

Currently `styled()` allows `className` to be received as `style` in the component definition i.e:

```javascript
const CustomComponent = styled(function ({ style }) {
  return <View style={style} />
})

return <CustomComponent className="text-white" />
```

And if you have a custom prop that should style inner component e.g:

```javascript
const CustomComponent = styled(function ({ style, textStyle }) {
  return (
    <View style={style}>
      <Text style={textStyle}>Hello</Text>
    </View>
  )
}, {
  props: {
    textStyle: true
  }
})
```

It's kind of inconsistent with how `className` to `style` works.

Naming `textStyle` as `textClassname` is also awkward and might cause confusion and not Typescript friendly because it'd be object but we'd be passing `string`

```javascript
styled(function ({ textClassname }) {
  return (
    <View>
      <Text style={textClassname}>Hello</Text>
    </View>
  )
})
```

It'd be much cohesive if it was something like

```javascript
const CustomComponent = styled(function ({ style, textStyle }) {

}, {
  map: {
    textClassname: 'textStyle'
  },

  // Or
  map: [
    ['textClassname', 'textStyle'],
  ]
})
```

Or even just automatically map anything that ends with `[token]ClassName` to `[token]Style` and have the option above to allow user fix conflicts if they have one.

**To Reproduce**
No reproduction needed

**Expected behavior**
Everything works as expected

**Expo Snack**
N/A

**Screenshots**
N/A

**Additional context**
None

**Comment by marklawlor** [comment]
Currently the `prop` option has two versions, `{ [prop]: boolean | string }` where string can be a style attributes. The docs for this are rather poor https://www.nativewind.dev/api/styled#styling-non-style-properties.

I'd be willing to consider changing this API to 

```
{ [prop]: boolean | string | PropOptions }

interface PropOptions {
  name?: string
  attribute?: keyof (ViewStyle | TextStyle | ImageStyle)
}
```

And changing the default `string` mapping to map to `name` instead of the less common `attribute`

**Comment by xxRockOnxx** [comment]
Yeah, changing the string mapping sounds nice.

```javascript
styled(function ({ textStyle }) {

}, {
  props: {
    textStyle: 'textClassname',
  }
})
```

As for the `PropOptions`, I believe TS union would be better because it's either a name or attribute.

Lastly, how about the auto-mapping of `$(name)Classname` to `$(name)Style`?

I think this case is common enough that having this will make working with Nativewind very pleasant.

It makes it consistent on how `className` is mapped to `style`.

In fact, I'd even go as far as making boolean option default to that behavior as my request.

```javascript
Custom Component = styled(function ({ style, textStyle }) {

}, {
  // What component props should Nativewind process.
  // By default, anything that ends with `style`.
  props: {
    // className
    style: true,

    // textClassName
    textStyle: true,

    // Ignored or error or warning for easy debugging
    imageStyle: false,

    // Other name
    buttonStyle: 'somethingElseForSomeReason',

    // Object config equivalent
    wrapperStyle: {
      enabled: true,

      // Or
      className: 'wrapperClassName',

      // Or
      attribute: 'color'
    }
  }
})

<CustomComponent
  className="w-full"
  textClassName="text-white"
  imageClassName="ignored or error"
  somethingElseForSomeReason="px-4"
/>
```

**Comment by marklawlor** [comment]
I don't believe automapping is a good idea, I'd rather be explicit. Props will not always follow that naming convenion Eg `textColor` is a common prop that people map using `{ props: { textColor: "color" } }`

**Comment by xxRockOnxx** [comment]
> textColor is a common prop that people map using { props: { textColor: "color" } }

That's a good example. Never crossed my mind.
Initially I was just asking for a way to map style prop to another name.

Sticking with that example, the requested option should still allow that.
It's just that by default, `className` is mapped to `style`.

IMO, just an intuitive default

```javascript
<Component
  className="w-full"
  innerStyle="text-red"
/>

function Component({ style, innerStyle }) {
}
```

vs

```javascript
<Component
  className="w-full"
  innerClassName="text-red"
/>

function Component({ style, innerStyle }) {
}
```

I'm not pushing this however if you still think it's not a good one.
I'm just giving arguments on why I think it's a good one.

So for recap, this issue ended up discussing two things:
- option to map prop to another one
- default behavior

**Comment by marklawlor** [comment]
I think I'll stick with being explict. Another reason not to auto-map is that not every `***Style` prop uses a style object.

ScrollView has `indicatorstyle` that accepts a string. https://reactnative.dev/docs/scrollview#indicatorstyle-ios

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
