### ISSUE TITLE
Nativewind styled breaks a component's type

### ISSUE THREAD

**Issue by avedetvedea** [nativewind/nativewind#359]
When using FlashList (from shopify as a performant Flatlist alternative), or say NestableDraggableFlatList as another imported component, I have to include

`const FlashList = styled(FlashListOriginal, {
  props: {
    contentContainerStyle: true,
  },
});
`

 and such to have access to `nativewind`, as recommended. However, when doing this, the data prop's type turns into unknown[] which is reflected on the renderItem prop.
 
 I talked about this about 2 months ago in discussions: https://github.com/marklawlor/nativewind/discussions/173#discussioncomment-3891828

**Comment by lakardion** [comment]
This is happening for me as well but with just a plain FlatList.
I did as such:
```typescript
export const FlatListWind = styled(FlatList, {
  props: {
    contentContainerStyle: true,
    style: true,
    indicatorStyle: true,
    columnWrapperStyle: true,
  },
})
```

Which results in a type-broken FlatList
 
![image](https://github.com/marklawlor/nativewind/assets/52294448/57124b30-dfa4-4a81-bdaa-818229514d4b)

**Comment by asdolo** [comment]
> This is happening for me as well but with just a plain FlatList. I did as such:
> 
> ```ts
> export const FlatListWind = styled(FlatList, {
>   props: {
>     contentContainerStyle: true,
>     style: true,
>     indicatorStyle: true,
>     columnWrapperStyle: true,
>   },
> })
> ```
> 
> Which results in a type-broken FlatList
> 
> ![image](https://user-images.githubusercontent.com/52294448/273867163-57124b30-dfa4-4a81-bdaa-818229514d4b.png)

You should explicitly set the FlatList's item type when applying `styled`:

```ts
export const FlatListWind = styled(FlatList<ItemType>, {
  props: {
    contentContainerStyle: true,
    style: true,
    indicatorStyle: true,
    columnWrapperStyle: true,
  },
})
```

Where `ItemType` is a TypeScript type/interface containing your `id` and any other properties.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
