### ISSUE TITLE
[QUICK SOLUTION] Discrepancy between docs and actual import needed to run on expo projects

### ISSUE THREAD

**Issue by gunslingerOP** [nativewind/nativewind#412]
**Describe the bug**
The docs say to use custom theme functions, one must require nativewind only, for example:
snippet to use hairLineWidth property as per docs 
![image](https://user-images.githubusercontent.com/35041331/217360258-fe9ff40c-d701-4c5c-9e01-17e5ab0a0113.png)

This unfortunately gives a " Cannot use import statement outside a module" error as it seems like these methods aren't exported properly

A few users here faced the same issue and the correct way to import the function is as so:

```
/** @type {import('tailwindcss').Config} */

const { hairlineWidth } = require("nativewind/dist/theme-functions");

module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
    "./src/components/**/*.{js,jsx,ts,tsx}",
    "./src/screens/**/*.{js,jsx,ts,tsx}",
  ],

  theme: {
    extend: {
      borderWidth: {
        hairline: hairlineWidth(),
      },
    },
  },
  plugins: [],
};
```
Please update the docs or say anything about these bugs. The issue I am raising here should serve as a solution for future users until the docs are synced with the actual implementation.

**To Reproduce**
1. Go to tailwind.config.js
2. Attempt to customize theme by importing as per the [documentation's instructions](https://www.nativewind.dev/customization/theme#hairlinewidth:~:text=%2C%0A%7D%3B-,hairlineWidth,-()%E2%80%8B)
3. Attempt to bundle app
4. Get error Cannot use import statement outside a module (While processing: "/YOUR_DIR/node_modules/nativewind/babel.js")

**Expected behavior**
For app to work correctly by bundling successfully as stated in docs
 
 
**Additional context**
I am using typeScript for the project

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
