### ISSUE TITLE
className is passed down instead of style

### ISSUE THREAD

**Issue by bekatd** [nativewind/nativewind#421]
**Describe the bug**
 The docs state that the className attribute is not passed down to custom components - but it is in weird case

**To Reproduce**
I have custom button component. Styles applied to button (via `className`) were working before, but suddenly (as you can see on below image) `className` prop started passing down to custom button (only on this particular screen)

**Expected behavior**
`className` should be compiled to `style` passed down.

**Screenshots**
![image](https://user-images.githubusercontent.com/6948919/218820907-add54606-16f2-40ad-8b60-296133860c54.png)

**Comment by marklawlor** [comment]
Please ensure this file is covered by your `content` glob inside `tailwind.config.js`

**Comment by bekatd** [comment]
My `tailwind.config.js` looks like this. `./src/**/*.{js,jsx,ts,tsx}` is not enough to cover every component?
![image](https://user-images.githubusercontent.com/6948919/218969155-e60b4003-f45b-4b49-9b1c-a283968d7ad2.png)

**Comment by bekatd** [comment]
Found the reason. I am using `babel-plugin-module-resolver` and if I import my button component with standard way it fails.

![image](https://user-images.githubusercontent.com/6948919/219336999-4f3e7afd-9415-4125-bf49-e51636933bde.png)

So instead I have to import components as described in `alias`  node of `babel.config.js`

![image](https://user-images.githubusercontent.com/6948919/219337532-b4b31950-60a3-4558-82b4-4972e1ba6187.png)

PS: maybe we need to outline this somewhere in the docs

**Comment by bekatd** [comment]
@marklawlor should I close this issue?

**Comment by antoniel** [comment]
Yo @bekatd, thank you for the well-described issue you filled. I wanted to suggest that this issue, specifically the solution you found with babel-plugin-module-resolver, should be added to the [troubleshooting](https://www.nativewind.dev/guides/troubleshooting) section. Given that the plugin is widely used with React Native, it would be great to have it documented in case others run into the same issue. Would you like to add it to the documentation or do you mind if I do it?

**Comment by bekatd** [comment]
@antoniel thanks. Would be great if you can do it :)

**Comment by Qweest** [comment]
Thanks @bekatd  

Also it looks like its important that `nativewind/babel` goes before `babel-plugin-module-resolver` plugin config (like in your [screenshot](https://github.com/marklawlor/nativewind/issues/421#issuecomment-1432852118) above). 
For me putting it on top and running `yarn start --reset-cache` did the thing.

**Comment by CagriUysal** [comment]
@Qweest thank you. this solved my issue ❤️

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
