### ISSUE TITLE
Space between doesn't work if child is a component

### ISSUE THREAD

**Issue by chen-rn** [nativewind/nativewind#425]
**Describe the bug**
```
<View className="space-x-1">
  <Text>0</Text>
  <Text>1</Text>
  <Text>2</Text>
</View>
```
works

```
<View className="space-x-1">
  <CustomText>0</CustomText>
  <CustomText>1</CustomText>
  <CustomText>2</CustomText>
</View>
```
Doest not seem to work.
Is this the intended behavior?

**Comment by a-eid** [comment]
it could be so, you should use `gap-1` instead of `space-x-1` if you're using RN >= 71.

**Comment by chen-rn** [comment]
Ahh, I'm not on RN >= 71

**Comment by romulocollopy** [comment]
https://github.com/marklawlor/nativewind/issues/127#issuecomment-1192615503

**Comment by michalpawlowski34** [comment]
It happens to me even without using components that do not accept a style prop as children- simply View and Text. 
RN 71.4

Any ideas?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
