### ISSUE TITLE
monorepo metro configuration

### ISSUE THREAD

**Issue by alperenkarip** [nativewind/nativewind#428]
I am trying to build my react-native project with **pnpm** but the **className** properties are not working. What can I do?

metro.config.js
`const {makeMetroConfig} = require('@rnx-kit/metro-config');
const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');
module.exports = makeMetroConfig({
  projectRoot: __dirname,
  resolver: {
    resolveRequest: MetroSymlinksResolver(),
  },
});`
babel.config.js
`module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: ['react-native-reanimated/plugin', 'nativewind/babel'],
};`
tailwind.config.js
`module.exports = {
  important: true,
  mode: 'jit',
  content: [
    './App.{js,jsx,ts,tsx}',
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        'Muli-Black': ['Muli-Black'],
        'Muli-BlackItalic': ['Muli-BlackItalic'],
        'Muli-Bold': ['Muli-Bold'],
        'Muli-BoldItalic': ['Muli-BoldItalic'],
        'Muli-ExtraBold': ['Muli-ExtraBold'],
        'Muli-ExtraBoldItalic': ['Muli-ExtraBoldItalic'],
        'Muli-ExtraLight': ['Muli-ExtraLight'],
        'Muli-ExtraLightItalic': ['Muli-ExtraLightItalic'],
        'Muli-Italic': ['Muli-Italic'],
        'Muli-Light': ['Muli-Light'],
        'Muli-LightItalic': ['Muli-LightItalic'],
        'Muli-Regular': ['Muli-Regular'],
        'Muli-SemiBold': ['Muli-SemiBold'],
        'Muli-SemiBoldItalic': ['Muli-SemiBoldItalic'],
      },
    },
  },
  plugins: [],
};
`

**Comment by gauthierdc** [comment]
I had the same issue, I tried using version 3 with `pnpm install nativewind@next` and following the instructions here [](https://github.com/marklawlor/nativewind/issues/308). It works for me

**Comment by gauthierdc** [comment]
For v2, I added the auto-install-peers=true pnpm config, worked for me

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
