### ISSUE TITLE
Style doesn't get overriden with styled component on web

### ISSUE THREAD

**Issue by feg624** [nativewind/nativewind#430]
**Describe the bug**
On version 2.0.11, I'm trying to setup a base component with the default styles, and then override with specific style where needed. This works fine for native, but doesn't work for web.

**To Reproduce**
I created a new styled component like this:

```
const MyText = styled(Text, "text-xs")
```

And later I used the component like this:

```
<MyText className="text-3xl" />
```

**Expected behavior**
I expected to get a larger text on the screen, which was the case on the native version, but on web, the text was still with xs size.

**Additional context**
While writing this issue, I kept looking for an alternative, and it started working as expected when I configured Nativewind like this:

```
NativeWindStyleSheet.setOutput({
  web: 'native', // <--- switching this from 'css' to 'native' made it work as expected
  default: 'native'
});

```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
