### ISSUE TITLE
Type compatibility with Solito V3

### ISSUE THREAD

**Issue by sgrund14** [nativewind/nativewind#433]
**Describe the bug**
hello,

noticed that the new V3 of SolitoImage is throwing a typescript error when wrapped with `styled` from Nativewind

<img width="983" alt="Screenshot 2023-03-07 at 6 48 42 PM" src="https://user-images.githubusercontent.com/14083701/223581909-079e7c32-a3d1-4e00-b618-12a57ff6432b.png">

Seems to still be working otherwise... 

**To Reproduce**

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**
[issue in solito](https://github.com/nandorojo/solito/issues/348)

**Comment by sgrund14** [comment]
update: it works if you do this

```
import { styled } from 'nativewind';
import { SolitoImageProps } from 'solito/build/image/image.types';
import { SolitoImage } from 'solito/image';
export const StyledImage = styled<SolitoImageProps>(SolitoImage);
```

**Comment by xinha-sh** [comment]
@sgrund14 The above work for nativewind v2 right ? Have you tried this with nativewind v3 alpha ?

**Comment by sgrund14** [comment]
@xinha-sh yea, it's nativewind v2. Haven't tried it with v3 alpha!

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
