### ISSUE TITLE
Native Wind Does Not pass styles to Styled components

### ISSUE THREAD

**Issue by rizwan92** [nativewind/nativewind#441]
**Describe the bug**
I have one styled component "Text" it's my own custom components native wind is behaving strangely, it applies the styles to subcomponents but not the main components.

**To Reproduce**
```
import {Text as RNText} from 'react-native';
// @ts-ignore
import styled from 'styled-components/native';

type TextProps = {
  weight?:
    | 'ExtraBold'
    | 'Bold'
    | 'SemiBold'
    | 'Medium'
    | 'Regular'
    | 'Light'
    | 'Thin'
    | 'ExtraLight';
  size?: number;
  color?: string;
};

export const Text = styled(RNText)<TextProps>`
  color: #000000;
  font-size: ${(props: {size: any}) => props.size || 12}px;
  font-family: Poppins-${(props: {weight: any}) => props.weight || 'Regular'};
  line-height: 24px;
`;

```

Whenever I try to use this component with native wind and pass the className props in it it does not apply the style for example

```
<Text className="mt-10">Please enter your details</Text>
// here mt-10 will not apply here 
```

But native wind applies styles for subcomponents for example 

```
import styled from 'styled-components/native';

export const Text = styled(RNText)<TextProps>`
  color: #000000;
  font-size: ${(props: {size: any}) => props.size || 12}px;
  font-family: Poppins-${(props: {weight: any}) => props.weight || 'Regular'};
  line-height: 24px;

const Label = styled(Text)`
  font-size: ${(props: {size: any}) => props.size || 12}px;
  font-family: Poppins-${(props: {weight: any}) => props.weight || 'Regular'};
  color: gray;
`;

Text.Label = Label;

//a whenever  I use this with className props like below its will apply the styles

<Text.Label  className="mt-4"> // here mt-4 will be applied
          Shop Owner Name
        </Text.Label>

```

**Expected behaviour**
native wind should apply the styles in main as well as subcomponent

**Expo Snack**
there is no support for styled-components in expo

**Screenshots**
it's just a margin i don't think screen short would require

**Additional context**

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
