### ISSUE TITLE
Expo quick start guide is not working

### ISSUE THREAD

**Issue by catdoglt** [nativewind/nativewind#446]
**Describe the bug**
Hello,

I followed the expo quick start instructions and now my expo app won't even start, I am getting this error:

TypeError: undefined is not an object (evaluating '_NativeWindStyleSheet.create')

**To Reproduce**
1. install nativewind and tailwindcss by running:
npm install nativewind
npm install --dev tailwindcss
2.npx tailwind init to create tailwind.config.js
add this line:
content: ["./App.{js,jsx,ts,tsx}", "./<custom directory>/**/*.{js,jsx,ts,tsx}"],
3. add following line to babel plugin:
plugins: ["nativewind/babel"]

**Expected behavior**
According to the docs it says "Thats it", but I am getting error and the app won't even start, because of that.

**Screenshots**

![Screenshot 2023-03-25 at 16 08 02](https://user-images.githubusercontent.com/20464922/227728685-7f27da73-fd45-41eb-8eff-2c9454f09f58.png)

**Additional context**
Can someone please confirm if something is missing from the expo install docs or is there a bug in this package?

**Comment by Nikola-Milovic** [comment]
Post your versions as well, I installed it through their docs and it seemed to work without any issues

**Comment by amjed-ali-k** [comment]
Post your package.json as well.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
