### ISSUE TITLE
Add direct cli method in create-react-native-app quickstart

### ISSUE THREAD

**Issue by AviAvinav** [nativewind/nativewind#450]
I was looking at the documentation in the quickstart https://www.nativewind.dev/quick-starts/create-react-native-app and just wanted to inform that I added a template for nativewind in the expo/examples repository some time ago, so you can now directly do `npx create-react-native-app my-nativewind-app` and choose the template for with-nativewind. I suggest that we can add that method in it too.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
