### ISSUE TITLE
I think "space between" is not working as expected when using function components

### ISSUE THREAD

**Issue by marco-carvalho** [nativewind/nativewind#455]
**Describe the bug**
Space between (space-y-4) is not creating margins when using function components.

**To Reproduce**
![image](https://user-images.githubusercontent.com/15821724/230700523-afa7a807-80d1-4ef5-9d73-ab92863090b9.png)
https://codesandbox.io/s/xenodochial-panini-besf0x In this example, I have a `margin-top`
```ts
const MyComponent = (props) => {
  return <div className="bg-green-500 h-32" />;
};

export default function App() {
  return (
    <div className="space-y-4">
      <div>Hello CodeSandbox</div>
      <MyComponent />
      <div>Start editing to see some magic happen!</div>
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/15821724/230700567-02b737b2-99f6-4ff1-b355-64a5762d458f.png)
https://snack.expo.dev/@markitu/hello-world In this example, I don't have a `margin-top`
```ts
import React from 'react';
import { withExpoSnack } from 'nativewind';

import { View } from 'react-native';
import { styled } from 'nativewind';

const StyledView = styled(View)

const MyComponent = (props) => {
  return (
    <StyledView className="bg-green-500 h-32" />
  );
};

const App = () => {
  return (
    <StyledView className="space-y-4">
      <StyledView>Hello CodeSandbox</StyledView>
      <MyComponent />
      <StyledView>Start editing to see some magic happen!</StyledView>
    </StyledView>
  );
}

export default withExpoSnack(App);
```

**Comment by kasperkberg** [comment]
from #127 
> I think I can see your issue, you are using components that do not accept a `style` prop as children.
> 
> ```
> <View className="flex-row items-center space-x-4">
>           <Text className="font-black text-3xl">{order.id.slice(-5)}</Text>
>           <BadgeStatus status={order.status} />
>           <BadgePayment paid={order.isPaid} />
> </View>
> ```
> 
> This will not work as BadgeStatus does not accept `style` as a prop.

So in your example, spreading the props should fix the issue

```
const MyComponent = (props) => {
  return (
    <StyledView className="bg-green-500 h-32" {...props} />
  );
};
```

as that passes `style` to MyComponent

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
