### ISSUE TITLE
`useColorScheme` causes error when server rendered

### ISSUE THREAD

**Issue by sgrund14** [nativewind/nativewind#459]
**Describe the bug**
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

this error is surfacing when I try to use `useColorScheme` in `_app.tsx` of my next app, where I'm using it to toggle a `dark` class on a top level element

**To Reproduce**

add `const { colorScheme } = useColorScheme()` to a basic nextjs template

**Expected behavior**

There is no server error

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by apetta** [comment]
You'll need to wrap the component in next/dynamic and disable SSR on it for this to work.

Alternatively, don't use the hook! Bake it into css with the `dark:` selector.

**Comment by thozh** [comment]
did you find a solution @sgrund14 ?

**Comment by sgrund14** [comment]
`dark:` selector should work for you, problem is I was using the `important: html` option in my tailwind config which was messing with some inheritance stuff

see: https://github.com/tailwindlabs/tailwindcss/issues/3842#issuecomment-810362604

for most use cases the `dark:` selector should work just fine tho

**Comment by thozh** [comment]
I also have `important: html` with my solito project.
I'm not sure if I can use the selector. I'm trying to change the ripple color on [Pressable](https://reactnative.dev/docs/pressable#rippleconfig) for Android. 

```
 <Pressable
          android_ripple={{
            color: colorScheme === 'dark' ? '#d4d4d8' : '#3f3f46',
            borderless: false,
          }}
          {...props}
        >
        ...
        </SPressable>
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
