### ISSUE TITLE
not able to import anything in tailwind.config.js file getting babel parser error

### ISSUE THREAD

**Issue by milon27** [nativewind/nativewind#463]
**Describe the bug**
not able to import anything in tailwind.config.js file getting babel parser error (error on v2)

**To Reproduce**
1. create react native cli project `npx react-native init testproject`
2. setup native wind as per documentation
3. const const {fontScale} = require('nativewind'); in tailwind.config.js
5. if you reload the app and open tailwind.config.js you will see 

**Expected behavior**
there should not be any babel error

**Screenshots**

![image](https://user-images.githubusercontent.com/44096479/233037658-6f8a451f-f82a-4973-9897-ab9976485adc.png)
![image](https://user-images.githubusercontent.com/44096479/233037729-2ff71e64-1c68-47d5-a9ef-3c9990c48194.png)

**Additional context**
v3 doesn't give this type of error I have tested but v3 doesn't run it gives another error

**Comment by semvgelooven** [comment]
When using V3 you need to use:

const { fontScale } = require("nativewind/theme"); in your tailwind.config.js file.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
