### ISSUE TITLE
Have an font by default on mobile app like tailwindCSS on web app

### ISSUE THREAD

**Issue by rosanche** [nativewind/nativewind#467]
I can t find out a solution how to have a font by default on all the app without having to write down a className on `Text`.

Has it been implementent with the v3 ?

**Comment by ethanrcohen** [comment]
You can do this with a custom component that wraps `Text` with styled, like `StyledText` in the [docs](https://www.nativewind.dev/api/styled#default-styles) -- you can also just call that custom component `Text` like in this [example repo](https://github.com/nandorojo/solito/blob/master/example-monorepos/with-tailwind/packages/app/design/typography.tsx#L6)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
