### ISSUE TITLE
Custom font names don't hotreload

### ISSUE THREAD

**Issue by danieloi** [nativewind/nativewind#474]
**Describe the bug**
when you specify a custom font with the `font-[n]` syntax, unless you shake your device to refresh things, the font you specify doesn't load. it works seamlessly with styles added with `StyleSheet.create` and the `style` prop

**To Reproduce**
set a component's font family like so 

```jsx
<Text className='font-[<Your-loaded-font-family-name>]' />
```
and notice how when you change the value in the square braces, you need to reload your app to see your changes

**Expected behavior**
The fonts changes should hot-reload like everything else

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
