### ISSUE TITLE
Can not use tailwind.config.js Custom plugin on nativewind & React-Native

### ISSUE THREAD

**Issue by usmangurowa** [nativewind/nativewind#483]
**Describe the bug**

So I tried using the tailwind.config.js to add a custom plugin, using the addBase, I tried adding a custom class ".paper" which I set it background color to "green". Upon using the class in a View tag, nothing happens. I tried using both addUtilities and addComponents and nothing works as well.  

**To Reproduce**
Initialize a nativewind react-native project, and tried adding a custom class using plugin.

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

Here is sample code

` plugin(function ({ addBase, config, theme, addComponents, addUtilities }) {
      addBase({
        ".paper": {
          backgroundColor: "green",
        },
      });
    })`

I will also appreciate it, if someone can point me in the right direction, I am trying to find a way to assign classes to custom classes, just like in tailwindcss @apply.
For example something like this;

`{
".text": "text-black text-base font-semibold"
}`

**Comment by calebpanza** [comment]
👍🏻 same issue, here!

**Comment by minzojian** [comment]
is this feature still not support?
so far i can use `twrnc` to work it out, however, i prefer use a className way directly.
check my question here
https://stackoverflow.com/questions/78689359/does-nativewind-support-custom-plugin-defined-in-tailwind-config-js

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
