### ISSUE TITLE
Dark theme not working in expo... (Native)

### ISSUE THREAD

**Issue by pixelkoduje** [nativewind/nativewind#488]
Why doesn't the dark theme from expo work in any version of nativewind? Even with a minimal demo. I change the mode, no errors pop up - the function returns the correct value, but the styles don't change. The same with version 2 and 3. Please help, or a working demo - minimal with one element. I did --clear, cleared apps etc. still the same. There is no difference.

**Comment by martin-eq** [comment]
I'm too having problems to make dark mode work on a simple app I just started using Expo. I followed all the steps but still the styles are not being applied properly. I have no idea what else to do (I'm new to RN)

**Comment by JWesorick** [comment]
Yea I don't understand, but I had to remove `darkMode: 'class',` despite needing it before for it to work.

**Comment by NandoMB** [comment]
up!

**Comment by alban-ameti** [comment]
+1

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
