### ISSUE TITLE
user-configurable font scaling?

### ISSUE THREAD

**Issue by tconroy** [nativewind/nativewind#492]
Hello! 

For react-native, how can we enable user-configurable font scaling? i.e: in your app, you have a slider to allow the user to scale their font size up or down.

This is doable with JS-only styles as you can just store a root font size and recompute, but I don't see a way to do this with Nativewind.

One idea would be to leverage CSS Custom Properties (similar to what tailwind for web does), but of course this is Native land and we don't have CSS or its custom properties concept. 

Has anyone else solved this? I love the simplicity of the tailwind styling but this feels like a challenge for accessibility.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
