### ISSUE TITLE
I can't use it with my app ?

### ISSUE THREAD

**Issue by hakimov-dev** [nativewind/nativewind#495]
**Describe the bug**
I can't use it with my app ? I've download and added configures as the docs but tailwind not working on my project?

**To Reproduce**
1. Configured as a docs.
2. I've added className to `<Text />` 
3. Restarted my app but nothing changed?

**Expected behavior**
I expected my tailwind classes working fluently and nothing.

**Screenshots**
Application:
![image](https://github.com/marklawlor/nativewind/assets/83240328/81d6d5c7-315a-4951-9710-34bf1af00bc9)
The component:
![image](https://github.com/marklawlor/nativewind/assets/83240328/e859092b-c159-49c3-9f9e-e6d9011f7420)
babel.config.js:
![image](https://github.com/marklawlor/nativewind/assets/83240328/d5c404ca-b916-4cb4-913f-073b6371ac5e)
Tailwind config js:
![image](https://github.com/marklawlor/nativewind/assets/83240328/082c499a-40b0-40cf-986d-22eedcdf0f6f)

**Additional context**
 "expo": "^48.0.7",
"react-native": "0.71.3",
The docs:
https://www.nativewind.dev/quick-starts/expo

**Comment by haydenbleasel** [comment]
More on this: running `npx tailwind -o output.css` produces the CSS file with the correct classes - they're just not being rendered in-app.

**Comment by pynhpo** [comment]
![image](https://github.com/marklawlor/nativewind/assets/26862130/a79de80b-9c41-4621-9c48-3d005c25ad27)
**<custom-folder>** must be the folder containing all your files such as **src** folder ^^
My case, it will be  `content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}']`

**Comment by haydenbleasel** [comment]
@pynhpo Not sure about the OP but I was running this in a sandbox that only had a single `App.tsx` file, which is included in the content array above, and the issue still occured.

**Comment by PR0F1L3R1** [comment]
same problem +1 "expo": "~48.0.18" with expo-router

**Comment by ebulku** [comment]
Try to add this in your main `_layout` file. I am using this in all my new projects with expo 49:

`import { NativeWindStyleSheet } from "nativewind";

NativeWindStyleSheet.setOutput({
  default: "native",
});`

**Comment by 3flippa** [comment]
git the same problem with:
"nativewind": "^2.0.11",
"react": "18.2.0",
"expo": "~50.0.7",
"expo-router": "~3.4.7",

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
