### ISSUE TITLE
losing style in a flatlist

### ISSUE THREAD

**Issue by joaodematejr** [nativewind/nativewind#504]
I'm using this tool to style a flatlist but when it renders the flatlist it loses all the style configuration.

https://github.com/marklawlor/nativewind/assets/17418041/c8ad8369-e8ba-440a-8c58-84c79bbfd2cc

`<FlatList
	className="w-full py-5"
	data={data}
        renderItem={renderItem}
	keyExtractor={(item) => item.id}
/>`

`const renderItem = ({ item }: { item: ApiResponseAttraction }) => {
		const { nome, descricao, data } = item;
		return (
			<View>
				<View className="w-full flex-row justify-start flex-1 flex items-center px-5 py-2">
					<Image
						source={ticket}
						className="w-9 h-9 mr-2"
						style={{ resizeMode: "contain" }}
					/>
					<View className="flex-col">
						<Title
							className="text-[#333333] text-[14px] font-bold"
							title={nome}
						/>
						{descricao.length > 1 ? (
							<Title
								className="text-[#333333] text-[14px] font-normal w-52"
								title={descricao.replace(/<\/?[^>]+(>|$)/g, '')}
							/>
						) : null}
						{data.length > 1 ? (
							<Text numberOfLines={1} className="w-60">
								{data}
							</Text>
						) : null}
					</View>
					<View className="justify-end flex flex-1 flex-row bg-white">
						<Image
							source={next}
							className="w-4 h-4 mr-0"
							style={{ resizeMode: "contain" }}
						/>
					</View>
				</View>
				<View className="px-5">
					<Divider />
				</View>
			</View>
		);
	};
`

"nativewind": "^2.0.11",
"react": "18.2.0",
"react-native": "0.72.3",

npx react-native info
info Fetching system and libraries information...
System:
  OS: macOS 13.4.1
  CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
  Memory: 36.12 MB / 16.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.15.0
    path: ~/.nvm/versions/node/v18.15.0/bin/node
  Yarn:
    version: 1.22.19
    path: /usr/local/bin/yarn
  npm:
    version: 9.5.0
    path: ~/.nvm/versions/node/v18.15.0/bin/npm
  Watchman:
    version: HEAD-f0bd988
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.11.3
    path: /usr/local/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK:
    API Levels:
      - "29"
      - "30"
      - "31"
      - "33"
    Build Tools:
      - 29.0.2
      - 29.0.3
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 33.0.0
      - 33.0.1
    System Images:
      - android-25 | Google APIs ARM EABI v7a
      - android-25 | Google APIs Intel x86 Atom
      - android-25 | Google APIs Intel x86 Atom_64
      - android-25 | Google Play Intel x86 Atom
      - android-29 | Intel x86 Atom_64
      - android-29 | Google APIs Intel x86_64 Atom
      - android-31 | Google APIs Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3/14E222b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.17
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

**Comment by gauthierdc** [comment]
I had this also, I don't remember how I fixed it, flex-1 on the FlatList ? Or an issue with the import ?

**Comment by redkean** [comment]
this might be because of the component you render at renderItem has flex-1.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
