### ISSUE TITLE
Nativewind not working with an expo49 project. No such file or directory node_modules/.cache/nativewind/output.css

### ISSUE THREAD

**Issue by 7ammer** [nativewind/nativewind#519]
**Describe the bug**
I cannot get Nativewind to work with a simple expo 49 project. Looking for a happy path to getting Nativewind working on a expo49 project.

I encounter this issue error: `Error: ENOENT: no such file or directory, open '/Users/test/untitled folder/my-app/node_modules/.cache/nativewind/output.css'`

Full error message...

```
› Opening on Android...
✔ Select a device/emulator › Pixel_7 (device)
› Opening exp+my-app://expo-development-client/?url=http%3A%2F%2F192.168.1.185%3A8081 on Pixel_7
› Press ? │ show all commands
NativeWind: Rebuilding...
NativeWind: /Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:215
        throw err;
        ^

Error: ...
    at Object.assign.manualParsing [as type] (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:25:15)
    at /Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:192:40
    at Object.<anonymous> (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:217:3)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli.js:6:22)

Node.js v18.12.1
Android Bundling failed 442ms
error: Error: ENOENT: no such file or directory, open '/Users/test/untitled folder/my-app/node_modules/.cache/nativewind/output.css'
    at Object.openSync (node:fs:600:3)
    at readFileSync (node:fs:468:35)
    at generateStyles (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/tailwind.js:86:44)
    at runTailwindCli (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/tailwind.js:49:5)
    at Object.getTransformOptions (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/index.js:43:40)
    at calcTransformerOptions (/Users/test/untitled folder/my-app/node_modules/metro/src/lib/transformHelpers.js:79:50)
    at Object.getTransformFn (/Users/test/untitled folder/my-app/node_modules/metro/src/lib/transformHelpers.js:113:57)
    at IncrementalBundler.buildGraphForEntries (/Users/test/untitled folder/my-app/node_modules/metro/src/IncrementalBundler.js:72:41)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async IncrementalBundler.buildGraph (/Users/test/untitled folder/my-app/node_modules/metro/src/IncrementalBundler.js:146:19)
```

Checking the `node_modules/.cache/nativewind` directory I see that there are two files in the nativewind folder: 1. `input.css` 2. `output.js`. There is no `output.css` as there error message states. Adding `output.css` to that folder causes Nativewind to error again here: `node_modules/tailwindcss/lib/cli/index.js:215`

**To Reproduce**
1. Go to https://github.com/7ammer/expo-nativewind-issues (setup by following this: https://docs.expo.dev/routing/installation/#quick-start)
2. `npm install`
3. `npx expo run:android`
4. See error - hopefully??

**Expected behaviour**
No error and works as expected

**Additional context**
Using "nativewind": "3.0.0-next.34"
I also tried the 2.0.11 version and got other issues.

**Comment by 7ammer** [comment]
If anyone has a working expo49/Nativewind project I could look at that runs on android I would be very grateful.

**Comment by renaldodev** [comment]
I've been trying to start a project following their doc instructions I've got no results as well.

**Comment by atanaskanchev** [comment]
> I've been trying to start a project following their doc instructions I've got no results as well.

I've managed to successfully install version 2 on expo 49, but not 3 or 4 alpha

**Comment by 7ammer** [comment]
> > I've been trying to start a project following their doc instructions I've got no results as well.
> 
> I've managed to successfully install version 2 on expo 49, but not 3 or 4 alpha

Would it be possible to post a setup on how you got it working in with v2 on Android?

**Comment by anurag-alla** [comment]
> **Describe the bug** I cannot get Nativewind to work with a simple expo 49 project. Looking for a happy path to getting Nativewind working on a expo49 project.
> 
> I encounter this issue error: `Error: ENOENT: no such file or directory, open '/Users/test/untitled folder/my-app/node_modules/.cache/nativewind/output.css'`
> 
> Full error message...
> 
> ```
> › Opening on Android...
> ✔ Select a device/emulator › Pixel_7 (device)
> › Opening exp+my-app://expo-development-client/?url=http%3A%2F%2F192.168.1.185%3A8081 on Pixel_7
> › Press ? │ show all commands
> NativeWind: Rebuilding...
> NativeWind: /Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:215
>         throw err;
>         ^
> 
> Error: ...
>     at Object.assign.manualParsing [as type] (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:25:15)
>     at /Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:192:40
>     at Object.<anonymous> (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli/index.js:217:3)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Module._load (node:internal/modules/cjs/loader:878:12)
>     at Module.require (node:internal/modules/cjs/loader:1061:19)
>     at require (node:internal/modules/cjs/helpers:103:18)
>     at Object.<anonymous> (/Users/test/untitled folder/my-app/node_modules/tailwindcss/lib/cli.js:6:22)
> 
> Node.js v18.12.1
> Android Bundling failed 442ms
> error: Error: ENOENT: no such file or directory, open '/Users/test/untitled folder/my-app/node_modules/.cache/nativewind/output.css'
>     at Object.openSync (node:fs:600:3)
>     at readFileSync (node:fs:468:35)
>     at generateStyles (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/tailwind.js:86:44)
>     at runTailwindCli (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/tailwind.js:49:5)
>     at Object.getTransformOptions (/Users/test/untitled folder/my-app/node_modules/nativewind/dist/metro/index.js:43:40)
>     at calcTransformerOptions (/Users/test/untitled folder/my-app/node_modules/metro/src/lib/transformHelpers.js:79:50)
>     at Object.getTransformFn (/Users/test/untitled folder/my-app/node_modules/metro/src/lib/transformHelpers.js:113:57)
>     at IncrementalBundler.buildGraphForEntries (/Users/test/untitled folder/my-app/node_modules/metro/src/IncrementalBundler.js:72:41)
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at async IncrementalBundler.buildGraph (/Users/test/untitled folder/my-app/node_modules/metro/src/IncrementalBundler.js:146:19)
> ```
> 
> Checking the `node_modules/.cache/nativewind` directory I see that there are two files in the nativewind folder: 1. `input.css` 2. `output.js`. There is no `output.css` as there error message states. Adding `output.css` to that folder causes Nativewind to error again here: `node_modules/tailwindcss/lib/cli/index.js:215`
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to https://github.com/7ammer/expo-nativewind-issues (setup by following this: https://docs.expo.dev/routing/installation/#quick-start)
> 2. `npm install`
> 3. `npx expo run:android`
> 4. See error - hopefully??
> 
> **Expected behaviour** No error and works as expected
> 
> **Additional context** Using "nativewind": "3.0.0-next.34" I also tried the 2.0.11 version and got other issues.

In your ```main``` branch 
Change dependency in package.json
``` "nativewind": "^3.0.0-next.34", ```
to 
``` "nativewind": "3.0.0-next.34", ```
and run npm install or yarn. It should work

**Comment by Stancobridge** [comment]
@anurag-alla solution worked but is failing to build using eas, it getting stucked

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
