### ISSUE TITLE
Support borderCurve style for IOS

### ISSUE THREAD

**Issue by utkuturunc** [nativewind/nativewind#522]
Request for adding support for IOS style `squircle`, which can be implemented as `borderCurve: 'continuous'`

See
https://reactnative.dev/docs/view-style-props#bordercurve-ios

Also a demo:
https://s4y.github.io/continuousCorners/

**Comment by LukaMarr** [comment]
Bumping this as well! :)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
