### ISSUE TITLE
Declaration merging breaking with @rneui/(base|themed)

### ISSUE THREAD

**Issue by ar3s3ru** [nativewind/nativewind#534]
**Describe the bug**
Installing the latest versions of `@rneui/base` and `@rneui/themed` breaks IntelliSense type checking on VS Code.

The project where I'm observing this bug has an `app.d.ts` file on the root, as described by the guide here: https://www.nativewind.dev/getting-started/typescript

**To Reproduce**
1. Open a project with Nativewind v3 installed using VS Code
2. Run `pnpm i -E @rneui/base @rneui/themed`

**Expected behavior**
VS Code IntelliSense to not complain on `className` properties.

**Additional context**
- The project is using `"nativewind": "3.0.0-next.34"`
- The version of the libraries installed are `"@rneui/base": "4.0.0-rc.8"` and `"@rneui/themed": "4.0.0-rc.8"`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
