### ISSUE TITLE
Class `rounded-none` not working as expected

### ISSUE THREAD

**Issue by doelgonzo** [nativewind/nativewind#546]
When using `rounded-none` in my `react-native@0.72.4` project, namely with `react-native-paper`'s `Button` component, I see that I am unable to get their buttons to not be rounded. Now, if I add `style={{ borderRadius: 0 }}` it works to have square edges just fine. Now, I see they quite specifically [fixed](https://github.com/callstack/react-native-paper/commit/6cfafa9441eb9ce6e0b3ce4669f9564b412cd625) a similar issue being due to not respecting the `0` value, but that's not the case here. What's happening (according to my experimentation with Flipper), is that nativewind is applying a non-shorthand version of the radius values, so the line in the code above would never work:
<img width="352" alt="image" src="https://github.com/marklawlor/nativewind/assets/5482592/97bc2935-b840-4c36-b05a-2119fc504ae4">
Is there a reason we couldn't have it result in both the shorthand and non-shorthand variants to achieve the same result? Seems like this opens things up to not overriding styles in third-party components. Or, maybe there's a config I missed that would help collapse the styles (although I guess I could end up with the opposite issue happening in the future... something having individually-set radiuses and not overriding them due to this)? Any help or guidance is welcome, but this feels like a bug.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
