### ISSUE TITLE
example error: Cannot find module 'nativewind/dist/metro/transformer'

### ISSUE THREAD

**Issue by tyrauber** [nativewind/nativewind#548]
When running the expo-router example with pnpm, the following error is raised:

```
Error: Cannot find module 'nativewind/dist/metro/transformer'
Require stack:
- ../nativewind/packages/nativewind/dist/metro/index.js
- ../nativewind/examples/expo-router/metro.config.js
```

Is there a reason the [transformer path](https://github.com/marklawlor/nativewind/blob/main/packages/nativewind/src/metro/index.ts#L59) is an absolute path as opposed to a relative path? The transformer file is in the same directory?

```
  metroConfig.transformerPath = require.resolve(
    //"nativewind/dist/metro/transformer",
    "./transformer"
  );
```

Note: this same issues exists in [react-native-css-interop](https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/src/metro/index.ts#L38) but doesn't pose the same issue.

If you make this change and re-build the nativewind package, the example works.  This presumably is only needed for running the example, but if it doesn't break the release it would make it easier to build and test the example.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by Anishabhandary** [comment]
Error: Cannot find module 'nativewind/metro/babelTransformer'


HOW TO RESLOVE THIS ISSUE
