### ISSUE TITLE
`styled` for React Native Switch properties not working

### ISSUE THREAD

**Issue by calebpanza** [nativewind/nativewind#551]
**Describe the bug**
I'm trying to use Nativewind to style a React Native `Switch`, though I'm having some issues. [Per the docs](https://www.nativewind.dev/api/styled#styling-non-style-properties), I should be able to do something as simple as:

```
const StyledSwitch = styled(Switch, {
  props: {
    trackColor: "color",
  },
});
```
though it's unclear as to how to use this property once it's been set up
```
<Switch trackColor="blue-500" />
<Switch trackColor="action" /> // custom color

<Switch trackColor="trackColor-blue-500" />
<Switch trackColor="trackColor-action" /> // custom color

<Switch trackColor="track-color-blue-500" />
<Switch trackColor="track-color-action" /> // custom color
```

I would also expect to be able to reference different color values for dark mode:
```
<Switch trackColor="blue-500 dark:red-500" />
```

**To Reproduce**
The above examples given would be exactly what I would use to get it going.

**Expected behavior**
I'm sure what my expectation was in this. I guess that referencing color value was what I _thought_ was suppose to happen, so `blue-500` or `my-custom-color` or `dark:red-500`

**Additional context**
The only way that I was able to get this to work was a super hacky workaround which nested a component inside of `styled` and intercepts the color values that are coming in. It feels like the wrong thing, though?

```
const StyledCoreSwitch = styled(
  (props) => {
    return (
      <CoreSwitch
        {...props}
        trackColor={{
          false: props.trackColor[0].fill,
          true: props.trackColor[0].fill,
        }}
        thumbColor={last(props.thumbColor).fill}
        ios_backgroundColor={last(props.ios_backgroundColor).fill}
      />
    );
  },
  {
    props: {
      trackColor: true,
      thumbColor: true,
      ios_backgroundColor: true,
    },
  }
);
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
