### ISSUE TITLE
Cannot find module "path_to_my_file"

### ISSUE THREAD

**Issue by chenzesam** [nativewind/nativewind#558]
**Describe the bug**
1. Require other file(theme tokens) from "./src/theme/tokens", and use it to tailwind.config.js theme param.
2. pnpm run ios.
3. show an error in the terminal.

**Expected behavior**
Can use it normally, and can use my theme tokens to the tailwind theme.

**Screenshots**
<img width="1440" alt="image" src="https://github.com/marklawlor/nativewind/assets/39208194/127043e7-6c26-4ee2-8adc-61492d527ee9">

**Additional context**
1. node_modules deps
"tailwindcss": "^3.3.3",
"nativewind": "3.0.0-next.34",
"expo": "~49.0.8",

2. tailwind.config.js
```js
const nativewind = require('nativewind/tailwind');
const tokens = require('./src/themes/tokens').tokens;

module.exports = {
  content: ['./App.{js,jsx,ts,tsx}', './src/**/*.{js,jsx,ts,tsx}'],
  presets: [nativewind],
  corePlugins: {
    fontFamily: false,
    gridColumn: false,
    gridAutoColumns: false,
    gridAutoRows: false,
    gridColumnEnd: false,
    gridColumnStart: false,
    gridRow: false,
    gridRowEnd: false,
    gridRowStart: false,
    gridTemplateColumns: false,
    gridTemplateRows: false,
  },
  theme: {
    fontWeight: {
      light: '400',
      regular: '600',
      DEFAULT: '600',
      bold: '700',
    },
    colors: {
      ...tokens.color,
    },
    spacing: {
      ...tokens.spacing,
      DEFAULT: tokens.spacing.m,
    },
    zIndex: {
      ...tokens.zIndex,
      DEFAULT: tokens.zIndex.s,
    },
    borderRadius: {
      ...tokens.radius,
      DEFAULT: tokens.radius.s,
    },
    fontSize: {
      xs: ['14px', getLineHeight(14)],
      s: ['16px', getLineHeight(16)],
      m: ['18px', getLineHeight(18)],
      l: ['20px', getLineHeight(20)],
      xl: ['24px', getLineHeight(24)],
      xxl: ['28px', getLineHeight(28)],
    },
  },
};
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
