### ISSUE TITLE
NativeWind CSS Open Sans Semibold Not Rendering on Android (iOS Works Fine)

### ISSUE THREAD

**Issue by mashwishi** [nativewind/nativewind#576]
**Describe the bug**
When using the NativeWind CSS library in an Android application, the "Open Sans Semibold" font weight appears to be not rendering correctly, while it works perfectly on iOS. This inconsistency in font rendering behavior between Android and iOS needs to be investigated and resolved.

**To Reproduce**
1. Create a NativeWind CSS project that includes the "Open Sans Semibold" font.
2. Apply the "font-semibold" class to a text element or component in your Android app.
3. Compare the rendered text on Android and iOS devices/emulators.

**Expected behavior**
The "Open Sans Semibold" font weight should render correctly on both Android and iOS devices, maintaining consistency in appearance.

**Actual behavior**
1. On Android: The "Open Sans Semibold" font weight is not rendering correctly, or it falls back to a different font weight.
2. On iOS: The "Open Sans Semibold" font weight renders correctly as expected.

**Version**
```json
"react": "18.0.0",
"react-native": "0.69.4",
"tailwindcss": "3.3.2"
"nativewind": "^2.0.11",
```

**iOS Screenshots**
<img width="198" alt="image" src="https://github.com/marklawlor/nativewind/assets/62344860/25bba2ea-35b3-43dc-9092-92d8d1f8702a">

**Android Screenshots**
<img width="193" alt="image" src="https://github.com/marklawlor/nativewind/assets/62344860/82e513c8-f2c1-41df-a622-afd5314e6c77">

**Additional context**
Source of the font: https://fonts.google.com/specimen/Open+Sans
How I used it: https://harshvitra.medium.com/using-custom-fonts-in-react-native-52ebb3c51454

tailwind.config.js
```json
      fontFamily: {
        'ss-extralight': 'OpenSans_Condensed-Light', // 100
        'ss-light': 'OpenSans-Light', // 200
        'ss-thin': 'OpenSans_Condensed-Regular', // 300
        'ss-regular': 'OpenSans-Regular', // 400
        'ss-medium': 'OpenSans-Medium', // 500
        'ss-semibold': 'OpenSans-SemiBold', // 600
        'ss-bold': 'OpenSans-Bold', // 700
        'ss-extrabold': 'OpenSans-ExtraBold', // 800
        'ss-black': 'OpenSans-ExtraBold', // 900
      },
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
