### ISSUE TITLE
Nativewind v4: No support for space-* on native devices, gap-* as (temporary) drop-in replacement / polyfill?

### ISSUE THREAD

**Issue by ItsWendell** [nativewind/nativewind#607]
**Describe the bug**
The documentation for the [space utility](https://www.nativewind.dev/v4/tailwind/spacing/space-between), notes that:

> space-{n} was temporary removed in v4. We are working to re-add it in the future.

Wouldn't it be possible for native to use `gap` as a drop-in replacement for space on native? Is there any difference in behavior? If not, this is issue can be seen as a feature request to add the `space` back. 

**To Reproduce**
 - Use `space-x-4` in an View.
 - Place Add two elements within
- No space's been added.

**Expected behavior**
Space should've been added.

**Expo Snack**
```ts
<View className="space-x-4">
    <Text>Hello</Text>
    <Text>World</Text>
</View>
```

**Comment by marklawlor** [comment]
There is progress being made on `block` styling for RN, in-which margin based padding will be relevant again.

But yes, if you are encountering this issue wondering what happened to `space-{n}`, using `gap-{n}` is a generally superior option.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
