### ISSUE TITLE
v4: inlineNativeRem set to 14 and cannot be disabled

### ISSUE THREAD

**Issue by robcaldecott** [nativewind/nativewind#616]
```
nativewind@4.0.9
expo@49.0.13
```

NativeWind seems to be enabling the new `inlineNativeRem` setting using a 14px value. This is messing up with padding, margins, etc. which we're expecting to use a base unit value of 4px and are now using 3.5px.

Here is a sample repo: https://github.com/robcaldecott/nativewind-4-issues

Note that `inlineNativeRem` is explicitly disabled in `metro.config.js` but it seems to be ignored.

For example, the following code should use padding of 24px and a gap of 32px:

```tsx
<View className="flex-1 bg-white items-center justify-center gap-8 p-6">...</View>
```

But the element inspector shows padding of **21px** and a gap of **28px** which implies a base Tailwind unit of **3.5px** (14 / 4).

![image](https://github.com/marklawlor/nativewind/assets/796702/20bbb70d-5013-4e3e-941c-d8525cad22b1)

**Comment by johnf** [comment]
That's a bug on the announcement page, try
```js
inlineRem: 16
```

I'm not sure if false works from a quick look at the code, but the above works for me.

**Comment by robcaldecott** [comment]
> That's a bug on the announcement page, try
> 
> ```js
> inlineRem: 16
> ```

That works, thank you.

> I'm not sure if false works from a quick look at the code, but the above works for me.

`inlineRem: false` does not work fwiw.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
