### ISSUE TITLE
v4. Animations do not work properly (they work until the first refresh)

### ISSUE THREAD

**Issue by pakerekchdz** [nativewind/nativewind#623]
**Describe the bug**

As in the description. Animations work - but don't work in fast refresh. When I refresh, they stop working. Latest version v4.0.13

**Comment by marklawlor** [comment]
Related: https://github.com/software-mansion/react-native-reanimated/issues/5296 https://github.com/software-mansion/react-native-reanimated/pull/5268

I'm currently trying to gauge how much effort a hack fix will be vs waiting for the fix.

**Comment by marklawlor** [comment]
Actually this can occur though normal usage as well. I'll publish a fix soon

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
