### ISSUE TITLE
Space-y-* not being applied

### ISSUE THREAD

**Issue by nicolas-wl** [nativewind/nativewind#625]
In my code space-y-* is not being applied, however the other classes are.

```ts
<ScrollView
                className="flex-1 flex-col pt-4 space-y-8"
                showsVerticalScrollIndicator={false}>
                
                <CustomTextInput
                  title="An input field"
                />

                <CustomTextInput
                  title="Another input field"
                />
              ...
```

NativeWind v2.0.11
RN v0.72.3

**Comment by marklawlor** [comment]
`space-` will not work in all situations. Please read how it is implemented in the docs and ensure that it works with your components.

 https://www.nativewind.dev/tailwind/spacing/space-between

Without a full reproduction (what is `CustomTextInput`?) I cannot assist you any more than that.
