### ISSUE TITLE
v4: Error when deploying an update

### ISSUE THREAD

**Issue by ghmendonca** [nativewind/nativewind#637]
**Describe the bug**
When I run the command `eas update --auto`, its throwing an error related to nativewind. The full message:

```
SyntaxError: global.css: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
```

This is happening when the `tailwindcss(native)` tries to rebuild.

**Expected behavior**
Should build the app and deploy using eas.

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/29390554/5a1a7767-3ead-4752-94af-8eb24dcd1752)

**Additional context**
This is also happening on CI (using github actions), not just on my machine.

**Comment by ghmendonca** [comment]
I was debugging to track down this issue, and looks like the `rawOutput` is never set during the build process, so during the transform step, when you do `data = Buffer.from(config.nativewind.rawOutput, "utf8");`, the error is thrown.

@marklawlor would love your feedback on this card since this is a huge issue for me. I'll be glad to help you fix this, I just don't understand exactly how everything works, so if you could explain how the build process works and why the `rawOutput` is never being set, I can try to fix and open a PR

**Comment by ghmendonca** [comment]
@marklawlor  Thanks for the information! Now I can take a look on this and come up with a solution, will try to fix this today and open a PR

**Comment by ghmendonca** [comment]
@marklawlor so this is harder than I thought. I added a bunch of logs and sometimes some of them executes and some not, so I started thinking that this could be a data racing issue. I couldn't find exactly why this is happening, but I can confirm it's a data racing issue because if you attach the debugger and go step by step, everything works just fine, I can see the `rawOutput` being set but if you just add logs and execute, it's hard to understand what's being called and which function is invoking other functions and since everything runs in child processes, this makes even harder to debug.

I already spent hours into debugging this and I'm not close to find a solution, so I don't think I'll be able to open a PR with a fix for this, so I would like to ask you to take over this issue, if you don't mind.

Sorry that I couldn't help much here and hopefully knowing this is a data race can help you resolving this bug.

**Comment by a-eid** [comment]
@ghmendonca @marklawlor guys, were you able to resolve this issue ?

**Comment by a-eid** [comment]
weirdly it worked for me locally but not on github actions.

**Comment by ghmendonca** [comment]
@a-eid yeah, for some reason it's working locally in the latest version, but still doesn't work on github actions. I spent a lot of time already trying to figure this out, but I still have no clue why this doesn't work on github actions :/

@marklawlor do you have any idea why this issue could still be happening on github actions?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
