### ISSUE TITLE
v4.(0.13): remapProps returns undefined

### ISSUE THREAD

**Issue by tyrauber** [nativewind/nativewind#638]
**Describe the bug**

According to the [v4 documentation](https://www.nativewind.dev/v4/api/remap-props), we should be able to `remap-props` with the following:

```
import { remapProps } from "nativewind";
import { Button } from "react-native";

const CustomizedButton = remapProps(Button, {
  buttonClass: "buttonStyle",
  labelClass: "labelStyle",
});

<CustomizedButton buttonClass="bg-blue-500" labelClass="text-white" />;
```

Unfortunately, remapProps returns undefined.

```
  console.log(CustomizedButton)
  console.log('type', typeof CustomizedButton)
```
> LOG  undefined
> LOG  type undefined

**Expected behavior**

Expected behavior is for remapProps to return a react-native component.

**Comment by johnf** [comment]
You don't need to create a new button. You can simply keep using `<Button>` as normal after remapping.
Remapping happens magically behind the scenes

**Comment by tyrauber** [comment]
Ah, thanks @johnf, so the documentation should be updated:

```
remapProps(ThirdPartyButton, {
  buttonClass: "buttonStyle",
  labelClass: "labelStyle",
});

<ThirdPartyButton buttonClass="bg-blue-500" labelClass="text-white" />;
```

**Comment by Agent57** [comment]
I'm attempting something similar, to remap the containerStyle and textStyle props on react-native-elements CheckBox component, but having no luck. Probably me just doing it wrong though...
```
import {CheckBox} from '@rneui/base';
import {remapProps} from 'nativewind';

export function CheckboxGroup() {
  remapProps(CheckBox, {
    containerClassName: 'containerStyle',
    textClassName: 'textStyle',
  });

  return <CheckBox containerClassName={'bg-blue-900 p-0'} textClassName="text-grey-100">
  // ...
}
```
Any assistance with understanding how this works would be much appreciated. Thanks!

**Comment by ospfranco** [comment]
Just lost a lot of time because the documentation is indeed wrong. It also doesn't seem to be working properly. I'm trying to remap a FlatList contentContainerStyle and with className it does nothing

![Oscar Franco Screen 001359](https://github.com/marklawlor/nativewind/assets/1634213/e5187b29-1b03-46d7-8bc1-33cd13f151d4)
![Oscar Franco Screen 001358](https://github.com/marklawlor/nativewind/assets/1634213/453e886a-52b4-452b-9b44-da0cd7d47f5c)

**Comment by ospfranco** [comment]
Apparently `contentContainerClassName` has already been patched by native wind. Still even after changing the name it doesn't work. Another question would be how to patch the types.

![Oscar Franco Screen 001360](https://github.com/marklawlor/nativewind/assets/1634213/fbf54f73-59a2-4b6f-9448-0df3ca96ae37)

**Comment by curiosbasant** [comment]
`remapProps` doesn't work at all, have wasted so much time. 😞

**Comment by denysoleksiienko** [comment]
remapProps doesn't work

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
