### ISSUE TITLE
V2: Color scheme not persisting

### ISSUE THREAD

**Issue by shessafridi** [nativewind/nativewind#644]
**Describe the bug**
Color mode is not persisting on Android and possibly iOS, on the web it's working fine and I can see the `theme` variable in localStorage but on Android the app resets back to dark mode, I have tested it in Expo GO and Expo development build.

`userInterfaceStyle` is set to `automatic` in my `app.json`

Packages:
`"nativewind": "^2.0.11",`
`"expo-system-ui": "~2.4.0",`
`"expo": "~49.0.15",`

**To Reproduce**
1. Create a new expo project
2. Setup Nativewind
3. Add dark mode support

**Expected behavior**
Dark mode should persist across app restarts

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
