### ISSUE TITLE
Confusing/Wrong Instructions for Tailwind CLI setup using PostCSS

### ISSUE THREAD

**Issue by speedhawk21** [nativewind/nativewind#649]
The Native CLI instructions are unclear related to the postcss.config.js setup instructions.  

1). They indicate to add require statements for tailwindcss and nativewindcss/postcss to the plugins prop as an array.  

2). The next section says to add an output object to the same plugin property we just defined as an array. 

Where should the require statements go?  Surely not the plugins prop!!??

What is the correct config setup for postcss setup for Tailwind CLI???

<img width="830" alt="Screenshot 2023-11-14 at 6 30 43 PM" src="https://github.com/marklawlor/nativewind/assets/8126555/e02e4641-1f8d-4462-b8f5-a9c1f295a253">

https://www.nativewind.dev/guides/cli-native

**Comment by speedhawk21** [comment]
When adding both as module.exports:

module.exports = {
  plugins: [require("tailwindcss"), require("nativewind/postcss")],
};

module.exports = {
  plugins: {
    "nativewind/postcss": {
      output: "nativewind-output.js",
    },
  },
};


I'm getting another error:

npx tailwindcss -i global.css --postcss postcss.config.js
node:internal/modules/cjs/loader:1077
  const err = new Error(message);
              ^

**Error: Cannot find module 'nativewind/postcss'**

**Comment by speedhawk21** [comment]
Here are my configs:

tailwind.config.js

```
/** @type {import('tailwindcss').Config} */

const nativewind = require("nativewind/tailwind/native");

module.exports = {
  content: [
    "./App.{js,jsx,ts,tsx}",
  ],

  theme: {

  },
  plugins: [nativewind()],
  presets: [],
};
```

postcss.config.js

```
module.exports = {
  plugins: [require("tailwindcss"), require("nativewind/postcss")],
};

module.exports = {
  plugins: {
    "nativewind/postcss": {
      output: "nativewind-output.js",
    },
  },
};
```
bable.config.js

```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ["babel-preset-expo", "nativewind/babel"],
    plugins: ["react-native-reanimated/plugin"],
  };
};
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
