### ISSUE TITLE
V4: NativeWind Storybook Web Example - (Expo) (React Native Web) 

### ISSUE THREAD

**Issue by 0mitch** [nativewind/nativewind#659]
It would be great to have a Storybook Web (with Webpack) example that uses NativeWind V4. Something like [this](https://github.com/expo/examples/tree/master/with-storybook) example by Expo but with NativeWind V4 added. 

When trying to set this up myself I got suck on the below point in the [Other bundlers](https://www.nativewind.dev/v4/getting-started/other-bundlers) docs: 

<img width="782" alt="Screenshot 2023-11-20 at 19 43 02" src="https://github.com/marklawlor/nativewind/assets/138505192/ed484edd-6673-45a2-8f4e-d2eddee35a73">

> Note: `<View style={{ $$css: true, test: "w-10 h-10 bg-blue-500" }} />` works fine so RNW is configured. 

So far I've tried the following:

1.  Setting `@babel/plugin-transform-react-jsx` in `.storybook/main.ts` like below in an example app similar to the Expo one above:
```
{
            name: getAbsolutePath("@storybook/addon-react-native-web"),
            options: {
                modulesToTranspile: ["../../../packages/design-system"],
                babelPlugins: [
                    "@babel/plugin-proposal-export-namespace-from",
                    [
                        "@babel/plugin-transform-react-jsx",
                        {
                            runtime: "automatic",
                            importSource: "nativewind",
                        },
                    ],
                ],
            },
        },
```

2. Creating a Storybook app in a Next app instead and following the docs [here](https://www.nativewind.dev/v4/getting-started/nextjs) - however I still get stuck on the same issue which leads me to believe this might **not** be an issue with `jsxImportSource` but instead related to [this](https://www.nativewind.dev/v4/getting-started/react-native) warning: 

"Web: If you wish to use Metro to bundle for website or App Clip and you are not using Expo, you will need either: Expo's Metro config @expo/metro-config or manually use Tailwind CLI to generate a CSS file."

If so how can this be set up and configured?

**Comment by panzacoder** [comment]
@Omitch just realized you created the issue on the storybook repo too.

Here is the config that finally worked for me after debugging for 2 days:
```javascript
{
      name: getAbsolutePath('@storybook/addon-react-native-web'),
      options: {
        projectRoot,
        modulesToTranspile: [
          'app', // this is my local monorepo package
          'react-native',
          'react-native-web',
          'solito',
          'moti',
          'react-native-reanimated',
          'react-native-css-interop',
          'nativewind',
          'react-native-gesture-handler',
        ],
        babelPlugins: [
          'react-native-reanimated/plugin',
          [
            '@babel/plugin-transform-react-jsx',
            {
              runtime: 'automatic',
              importSource: 'nativewind',
            },
          ],
        ],
      },
    },
```

Once I have my project a bit cleaner, I will share a starter and link it back here.

**Comment by oliviercperrier** [comment]
@panzacoder Any update on that starter project? Thanks!!

**Comment by panzacoder** [comment]
@oliviercperrier thanks for the bump, I think my project is at a decent spot to do this, I'll try to extract a starter this weekend.

**Comment by oliviercperrier** [comment]
@panzacoder Awesome thanks

**Comment by panzacoder** [comment]
@oliviercperrier I _finally_ got through extracting mine as well. I want to keep adding to it over time, it's been a good exercise to strip it down and double check some assumptions I had made. 

[PLFX Stack](https://github.com/panzacoder/plfx-stack)

---

@kimchouard's solution is simpler if you don't need a monorepo and/or nextjs!

**Comment by oliviercperrier** [comment]
@kimchouard @panzacoder Thanks you guys, much appreciated!

**Comment by kimchouard** [comment]
> [PLFX Stack](https://github.com/panzacoder/plfx-stack)

Interesting @panzacoder, thanks for sharing too! Great Readme file btw 😎

Quick question out of curiosity: I've never used Solito yet, but I feel there is some ovelap now with Expo Router v3, no? Curious to get your thoughts. 🙃

**Comment by panzacoder** [comment]
@kimchouard thank you!

I am new to expo & expo router (and native dev) so I didn't want to introduce more unfamiliarity with my web hosting & deployment. I know well how to configure and deploy next, so that's a requirement for me.

Solito is a bridge between the two routers that allows your linking and router hooks to do proper in-linking for each platform.

[Solito also has a short page about Expo Router](https://solito.dev/guides/expo-router)

**Comment by akashdevcc** [comment]
@panzacoder Will you be able to add storybook support in the expo app too?
I am trying to setup it with my project, but it doesn't seem to work with Nativewind and Turbo monorepo.
I'll try forking and adding it to your repo, if I can reproduce the problem I am facing.

@panzacoder @kimchouard 
Would you be able to have a look, if I reproduce the problem?

**Comment by akashdevcc** [comment]
@panzacoder I think my issue is related to `pnpm` and not `nativewind`, as mentioned in [this github issue](https://github.com/marklawlor/nativewind/issues/734#issuecomment-1898824306).

Anyway, I'll try to replicate this in your repo, and check if it works with storybook too while using `pnpm`, with the above fix.

**Comment by panzacoder** [comment]
Yeah I had issues with any package manager except npm. Which is super odd because I’m using yarn4 in the project this repo is based on.

I would prefer to be using pnpm or bun. I’m fairly new to RN but I think support for anything but yarn is pretty new.

Jacob Hebert
Pensacola, FL

**Comment by akashdevcc** [comment]
True. But I think going forward most projects will be supporting `pnpm` to the fullest. As I have seen most projects recommends `pnpm` as preferred package manager in their "guides". But it's true although they are recommending `pnpm`, the number of examples and guides with `pnpm` are very limited.

Also, I tested the `config.resolver.disableHierarchicalLookup = true` with my project setup, the storybook is now able to apply styles on the components, coming from separate `components` package. Although, I have noticed, it is not able to apply [fontSize](https://www.nativewind.dev/v4/tailwind/typography/font-size) style properly on these components, coming from separate `components` package.

This is the scenario, I am facing:
1. If the storybook is in package `apps/expo`.
2. If there is a component `A` defined like below:
  ```
  export default function A({ title, content }) {
    return (
      <SafeAreaView className="bg-background">
        <View className="h-full w-full p-4">
          <Text className="py-2 text-9xl font-bold text-primary">{title}</Text>
        </View>
      </SafeAreaView>
    );
  }
  ```
3. If this component `A` is in package `packages/ui`, the component in storybook, does not get style applied for `text-9xl` but it works for other styles `py-2 font-bold text-primary`.
4. If there is a component `B` with exact same code as component `A` but is defined in the same package as the storybook i.e. `apps/expo`, the component in storybook, gets all the styles correctly.
5. Interestingly, now after looking at component `B` in storybook, if I switch the story to component `A`, now it successfully loads with the `text-9xl` style, but if I change the style in component `A` to `text-8xl` / `text-7xl` / `text-6xl` it does not work. But it will again work if I apply the same change in component `B` and switch the story to `A` again.
6. So, I think, nativewind (or may be something else) has getting issue loading some of the styles like `fontSize` for components coming from different packages.

I'll try to reproduce this, in a separate minimal repo.

**Comment by akashdevcc** [comment]
@panzacoder Also, I tested the `config.resolver.disableHierarchicalLookup = true` with my project setup, the storybook is now able to apply styles on the components, coming from separate `components` package. Although, I have noticed, it is not able to apply [fontSize](https://www.nativewind.dev/v4/tailwind/typography/font-size) style properly on these components, coming from separate `components` package.

This is the scenario, I am facing:
1. If the storybook is in package `apps/expo`.
2. If there is a component `A` defined like below:
  ```
  export default function A({ title, content }) {
    return (
      <SafeAreaView className="bg-background">
        <View className="h-full w-full p-4">
          <Text className="py-2 text-9xl font-bold text-primary">{title}</Text>
        </View>
      </SafeAreaView>
    );
  }
  ```
3. If this component `A` is in package `packages/ui`, the component in storybook, does not get style applied for `text-9xl` but it works for other styles `py-2 font-bold text-primary`.
4. If there is a component `B` with exact same code as component `A` but is defined in the same package as the storybook i.e. `apps/expo`, the component in storybook, gets all the styles correctly.
5. Interestingly, now after looking at component `B` in storybook, if I switch the story to component `A`, now it successfully loads with the `text-9xl` style, but if I change the style in component `A` to `text-8xl` / `text-7xl` / `text-6xl` it does not work. But it will again work if I apply the same change in component `B` and switch the story to `A` again.
6. So, I think, nativewind (or may be something else) has getting issue loading some of the styles like `fontSize` for components coming from different packages.

I'll try to reproduce this, in a separate minimal repo.

**Comment by oliviercperrier** [comment]
@kimchouard Do you get slow build time in local development? When i run `npm run storybook:web` it takes like 1min to start the dev server

**Comment by kimchouard** [comment]
> @kimchouard Do you get slow build time in local development? When i run `npm run storybook:web` it takes like 1min to start the dev server.

It takes a bit to boot yes, but only on first start and then it's pretty fast. I can't really compare with other setups though since it's the first time I use Storybook 🤷🏼‍♂️

**Comment by oliviercperrier** [comment]
> > @kimchouard Do you get slow build time in local development? When i run `npm run storybook:web` it takes like 1min to start the dev server.
> 
> It takes a bit to boot yes, but only on first start and then it's pretty fast. I can't really compare with other setups though since it's the first time I use Storybook 🤷🏼‍♂️

Ok thanks! ill try to figure out why! Ive been using storybook a couple time and it was talking like 10 seconds to start max.. Will keep you posted if i find something

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by acv-dancom** [comment]
@panzacoder thanks men, your code helped me a lot
