### ISSUE TITLE
v4: `expo-image` doesn't render any image with `className`

### ISSUE THREAD

**Issue by imranbarbhuiya** [nativewind/nativewind#680]
**Describe the bug**
When using `expo-image`, with height and width in `className` it doesn't render the image. If I add the height and width in `style`, it works

**To Reproduce**
create a new app using expo, import `expo-image`, use className and style and see the result

**Expected behavior**
Using `height`, and `width` in className and `style` should behave the same

**Expo Snack**
https://github.com/imranbarbhuiya/nativewind/commit/1042909149e0071304ee9417065c8d9b771be4d9
run this commit and you'll see the issue

**Comment by lockieluke** [comment]
+1

**Comment by lockieluke** [comment]
+1

**Comment by alexandrius** [comment]
+1

**Comment by MohammedAbidNafi** [comment]
+1

**Comment by siquick** [comment]
Same issues on V4

```sh
import { Image } from "expo-image";
....
....
<Image
        source={release.small_img}
        placeholder={blurhash}
        contentFit="cover"
        transition={1000}
        style={{ width: "100%", height: 80, borderRadius: 8 }} # this works
        className="w-full h-12" # this doesnt
 />
```

`package.json`

```sh
"expo-image": "~1.10.5",
"nativewind": "^4.0.23",
```

**Comment by ShanThatos** [comment]
Check this out: [https://github.com/marklawlor/nativewind/blob/4232087bd2405e8d9b42979fcda429b5ddaa2a49/packages/react-native-css-interop/src/runtime/components.ts](Components with cssInterop & remapProps). 

By default, it looks like only react-native components are setup for nativewind & className -> style transformations. 

Add `cssInterop(Image, { className: "style" })`.

**Comment by imranbarbhuiya** [comment]
Will try thanks, I'll still expect it to work without manually adding it as it's a commonly used expo official package. So @marklawlor will u accept a pr adding it?

**Comment by lockieluke** [comment]
> Will try thanks, I'll still expect it to work without manually adding it as it's a commonly used expo official package. So @marklawlor will u accept a pr adding it?

He’s now working at Expo

**Comment by JN-forkwork** [comment]
Hey guys, I don't get it. If I want to use a third party library like super-grid for example, and the FlatGrid component originally uses style, is it possible to use className+tailwind with it. Currently, className is being ignored, is that expected?

**Comment by DannyCare** [comment]
It definitely should accept a className – a change that saves having to import yet another function into each screen. I want to use expo-image as I'm having issues with <Image> making multiple requests. Expo does not have this problem and is more performant in my project.

Please add this

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by angel-luis** [comment]
This renders:
```
<Image
          style={{ width: "100%", height: "100%" }}
          source="https://picsum.photos/seed/696/3000/2000"
          contentFit="cover"
        />
```

This not:
```
<Image
          className="w-full h-full"
          source="https://picsum.photos/seed/696/3000/2000"
          contentFit="cover"
        />
```

**Comment by Hosam-hsm** [comment]
import { Image } from "expo-image";
 
cssInterop(Image, { className: "style" });

 <Image
            contentFit={"contain"}
            className="w-50 h-50"
            source={require("../../assets/images/transparent-icon.png")}
            onLoadEnd={onImageLoaded}
      />

This renders only if I use normal style param

"expo": "~52.0.25",
"nativewind": "^4.1.23",

Issue still exist?

**Comment by partytoni** [comment]
I'm on 2.0.4 (currently latest version) and is still not working. When will it be fixed?

**Comment by codinsonn** [comment]
@angel-luis @partytoni  Have you tried with @ShanThatos solution yet?

Putting a `cssInterop()` wrapper around did the trick for me:

```tsx
const StyledExpoImage = cssInterop(ExpoImage, {
    className: 'style',
})
```

**Comment by Eysteix** [comment]
import {  StyleSheet,View } from "react-native";
import {Image} from "expo-image"
import { cssInterop } from 'nativewind';
const PlaceholderImage = require('@/assets/images/background-image.png');

export default function Index() {
  return (
    <View
      className="flex-1  items-center bg-slate-900"
    >
      <View className="flex-1 m-5">
        <Image source={PlaceholderImage} className="w-[300px] h-[400px] rounded-lg"  />
      </View>
    </View>
  );
}

cssInterop(Image, {
  className: {
    target: "style",
  },
});

**Comment by jasonluo07** [comment]
> Just Adding the NativeWind Interop fixed this Issue
> 
> `cssInterop(Image, { className: { target: "style", }, });`

Thanks a ton, this saved me!
