### ISSUE TITLE
V4 - IncompatibleNativeProperty  -moz-column-gap

### ISSUE THREAD

**Issue by RaederDev** [nativewind/nativewind#681]
**Describe the bug**
When using nativewind ^4.0.16 use the `gap-x-4` class and you get a log message with
`IncompatibleNativeProperty  -moz-column-gap`

The actual feature does work fine you do get a gap, you just also get your console spammed by the message above on every reload.

**To Reproduce**
1. Use the `gap-x-4` class

**Expected behavior**
No log message is generated.

**Comment by JuanRdBO** [comment]
I have this error as well. Was not present in V2

**Comment by suchai-foundnerds** [comment]
me too `"nativewind": "^4.0.1",`

**Comment by julian-gargicevich** [comment]
Same here

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
