### ISSUE TITLE
V4: Nativewind styling with Expo Router navigators

### ISSUE THREAD

**Issue by ShaneKeney** [nativewind/nativewind#682]
**Describe the bug**
Are there any clear docs on how to handle cases such as Expo Router navigation components with Nativewind?

e.g.

```
export default () => {
  return (
    <Tabs
      initialRouteName="home"
      screenOptions={{
        tabBarShowLabel: false
      }}
    >
    ... other tabs
      <Tabs.Screen
        name="account"
        options={{
          tabBarIcon: ({ focused }) => (
            <TabBarIcon
              Icon={focused ? SVG.AccountFilled : SVG.Account}
              focused={focused}
              width={24}
              height={24}
            />
          ),
          tabBarBadgeStyle: {
            backgroundColor: 'fill-Primary-70'
          },
          tabBarBadge: 3
        }}
      />
    </Tabs>
  );
};
```

The above snippet would be a simple example.  I tried using `cssInterop` but can't seem to access the `tabBarBadgeStyle` of the `options` prop of the `Tabs.Screen` component.

**To Reproduce**
See above.

**Expected behavior**
I'd ideally expect to be able to use some mapping function to use Tailwind class utilities in one of the style props of the `Tabs.Screen` component for custom styling.

**Comment by tyrauber** [comment]
Hey @ShaneKeney, I was looking into the same thing and had a conversation with Mark about it.

> React Navigations navigators currently don't work well with nativewind. Its styling solution is quite different from the normal RN styling practices, so it doesn't quite fit.
If you want to go 100% nativewind with the navigators you probably want to render them as a custom component, that way you can pass className
https://reactnavigation.org/docs/bottom-tab-navigator#tabbar
[Bottom Tabs Navigator | React Navigation](https://reactnavigation.org/docs/bottom-tab-navigator)
A simple tab bar on the bottom of the screen that lets you switch between different routes. Routes are lazily initialized -- their screen components are not mounted until they are first focused.
The other option is to wrap the navigator in a custom component and use cssInterop's nativeStyleToProp functionality.. This isn't well documented yet, as its something I'm currently improving

I've tried a couple different approaches and the easiest way to theme react-navigation navigators is to create a constants file for colors, and import the themes through react-navigation ThemeProvider.

```
// src/constants/Colors.ts
import colors from 'tailwindcss/colors';

export default {
  light: {
    // react-navigation defaults
    primary: colors.neutral[900],
    background: colors.white,
    card: colors.neutral[100],
    text: colors.neutral[800],
    border: colors.neutral[500],
    notification: colors.neutral[700]

  },
  dark: {
    // react-navigation defaults
    primary: colors.neutral[100],
    background: colors.black,
    card: colors.neutral[950],
    text: colors.neutral[300],
    border: colors.neutral[500],
    notification: colors.neutral[700]
  }
};
```
```
// src/contexts/Theme.tsx
import React from 'react';
import { useColorScheme } from 'nativewind';
import { ThemeProvider } from '@react-navigation/native';
import Themes from './src/constants/Colors.ts';

export const resolveTheme = (colorScheme) => ({
  dark: colorScheme === 'dark',
  colors: Themes[colorScheme],
});

export const ThemeContext = React.createContext({
  colorScheme: 'light',
});

export function useTheme() {
  return React.useContext(ThemeContext);
}

export function Provider(props) {
  const { colorScheme, setColorScheme } = useColorScheme();
  return (
    <ThemeContext.Provider value={{ colorScheme, setColorScheme }}>
      <ThemeProvider value={resolveTheme(colorScheme)}>
        {props.children}
      </ThemeProvider>
    </ThemeContext.Provider>
  );
}

export default Provider;
```

I would have loved to have all the colors set at css variables in global.css, but I couldn't figure out a good method for extracting the colors into a theme object react-navigation ThemeProvider could use.

**Comment by ShaneKeney** [comment]
@tyrauber Is there a way to pull in custom colors defined in the `tailwind.config.ts`?  The above shows how we can use the default colors that comes with Tailwind out of the box e.g. `colors.neutral[500]`.

**Comment by tyrauber** [comment]
@ShaneKeney, I wish!  

Unfortunately, it isn't exactly straightforward.  The best I could come up with was to use `tailwindcss/resolveConfig`,  which will take into account colors defined in tailwind.config.
```
import { ThemeProvider } from '@react-navigation/native';
import { useColorScheme } from 'nativewind';
import React from 'react';
import resolveConfig from 'tailwindcss/resolveConfig';

const tailwindConfig = require('@/tailwind.config');

const config = resolveConfig(tailwindConfig);
const Themes = config.theme.extends.colors;

export const resolveTheme = (colorScheme) => ({
  dark: colorScheme === 'dark',
  colors: Themes[colorScheme],
});

export const ThemeContext = React.createContext({
  colorScheme: 'light',
});

export function useTheme() {
  return React.useContext(ThemeContext);
}

export function Provider(props) {
  const { colorScheme, setColorScheme } = useColorScheme();

  React.useEffect(() => {
    //console.log('Theme Changed', colorScheme);
  }, [colorScheme]);

  return (
    <ThemeContext.Provider value={{ colorScheme, setColorScheme }}>
      <ThemeProvider value={resolveTheme(colorScheme)}>{props.children}</ThemeProvider>
    </ThemeContext.Provider>
  );
}

export default Provider;
```
```
module.exports = {
  darkMode: 'class',
  content: [
    'src/**/*.{js,jsx,ts,tsx}', 
    '../../packages/ui/src/**/*.{js,jsx,ts,tsx}'
  ],
  presets: [require('nativewind/preset')],
  plugins: [],
  theme: {
    extends: {
      colors:  {
        light: {
          // react-navigation defaults
          primary: colors.neutral[900],
          background: colors.white,
          card: colors.neutral[100],
          text: colors.neutral[800],
          border: colors.neutral[500],
          notification: colors.neutral[700]

        },
        dark: {
          // react-navigation defaults
          primary: colors.neutral[100],
          background: colors.black,
          card: colors.neutral[950],
          text: colors.neutral[300],
          border: colors.neutral[500],
          notification: colors.neutral[700]
        }
      }
    }
  }
};
```

 I've been trying unsuccessfully to devise a method to take into account variable colors defined in the global.css file, but `tailwindcss/resolveConfig` only takes into account the tailwind.config and has no knowledge of the css.

**Comment by mcavaliere** [comment]
I managed to achieve this in `nativewind@^4.0.16` by wrapping the `Stack` component and using the `cssInterop` utility to map over some style properties: 

```
function StackContainer({ headerBackgroundColor, headerTintColor, ...props }: any) {
  return (
    <Stack
      screenOptions={{
        contentStyle: { backgroundColor: 'transparent' },
        headerStyle: { backgroundColor: headerBackgroundColor },
        headerTintColor,
      }}
    />
  );
}

/**
 * Translate nativewind classes to values that we can use to style the react-navigation <Stack> component.
 */
cssInterop(StackContainer, {
  headerClassName: {
    target: false,
    nativeStyleToProp: {
      backgroundColor: 'headerBackgroundColor',
      color: 'headerTintColor',
    },
  },
});
```

Then I call it like this: 

```
<StackContainer headerClassName="bg-background text-foreground" />
```

And it works well, EXCEPT when the style definitions have CSS Variables in them. I.e., the above code works when my tailwind custom colors are defined with static values as follows: 

```
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: 'red',
        },
        foreground: {
          DEFAULT: 'green',
        },
       // ...

```

...but but when they contain CSS variables, the below does not work at the moment (even though I'm able to use those the classes containing CSS vars elsewhere): 

```
        background: {
          DEFAULT: 'rgb(var(--user-color-1) / <alpha-value>)',
        },
        foreground: {
          DEFAULT: 'rgb(var(--user-color-2) / <alpha-value>)',
        },
```

**Comment by Porter-smith** [comment]
I found a solution for working with CSS variables on the `expo-router-tabs` component using the same approach as @mcavaliere with `cssInterop` and `nativewind@^4.0.16`

```jsx
import { Ionicons } from '@expo/vector-icons';
import { Tabs } from "expo-router";
import { useColorScheme } from 'nativewind';
import { cssInterop } from 'nativewind';

function TabLayoutContainer({ tabBarClassName, headerClassName, ...props }) {
  return (
    <Tabs
      screenOptions={{
        tabBarStyle: { backgroundColor: tabBarClassName.backgroundColor },
        headerStyle: { backgroundColor: headerClassName.backgroundColor },
        headerTintColor: headerClassName.color,
      }}
      {...props}
    />
  );
}

cssInterop(TabLayoutContainer, {
  tabBarClassName: {
    target: false,
    nativeStyleToProp: {
      backgroundColor: 'tabBarClassName.backgroundColor',
    },
  },
  headerClassName: {
    target: false,
    nativeStyleToProp: {
      backgroundColor: 'headerClassName.backgroundColor',
      color: 'headerClassName.color',
    },
  },
});

export default function TabLayout() {
  const { colorScheme } = useColorScheme();

  return (
    <TabLayoutContainer
      tabBarClassName="bg-background"
      headerClassName="bg-background text-primary"
    >
      {/* Tabs.Screen components */}
    </TabLayoutContainer>
  );
}
```

However, it's important to note that this solution doesn't work with the web. `cssInterop` doesn't seem to work though and the CSS classes don't seem to apply for some reason. I'm not sure if this is a bug or if I misconfigured something.

**Comment by Mirthis** [comment]
Thanks @Porter-smith your solution helped me a lot with a different component that had a similar nested structure.
I was able to avoid specifying the individual attributes and also make this works more nicely with Typescript (this works if the target props accepts a style and it's not a single property).
Example below for the component I was using.

```javascript
// add className props (actually used when using the component) and style props (target for cssInterop)
type OtpInputWrapperProps = OtpInputProps & {
  containerStyleClassName: string;
  containerStyle?: ViewStyle;
  pinCodeContainerStyleClassName: string;
  pinCodeContainerStyle: ViewStyle;
  pinCodeTextStyleClassName: string;
  pinCodeTextStyle: TextStyle;
};

// nested props inside theme take Style so no need to extract individual attributes from the className props
const OtpInputWrapper = ({
  containerStyle,
  pinCodeContainerStyle,
  pinCodeTextStyle,
  ...props
}: OtpInputWrapperProps) => {
  return (
    <OtpInput
      {...props}
      theme={{
        containerStyle,
        pinCodeContainerStyle,
        pinCodeTextStyle,
      }}
    />
  );
};

// mapping from className(s) to Style(s)
cssInterop(OtpInputWrapper, {
  containerStyleClassName: {
    target: "containerStyle",
  },
  pinCodeContainerStyleClassName: {
    target: "pinCodeContainerStyle",
  },
  pinCodeTextStyleClassName: {
    target: "pinCodeTextStyle",
  },
});

// actual component use
<OtpInputWrapper
  containerStyleClassName="bg-red-400"
  pinCodeTextStyleClassName="font-bold"
  numberOfDigits={6}
  onTextChange={onChange}
  focusColor="green"
  focusStickBlinkingDuration={500}
/>
```

**Comment by kachidk** [comment]
Simple syntax that plays nice with Typescript.

```tsx
import { Tabs } from "expo-router";
import { cssInterop } from "nativewind";
import React, { ComponentProps } from "react";
import { ViewStyle } from "react-native";

export default function TabsLayout() {
  return (
    <CustomTabs headerClassName="bg-green-200">
      <Tabs.Screen name="index" />
    </CustomTabs>
  );
}

type CustomTabsProps = Omit<
  ComponentProps<typeof Tabs> & {
    headerStyle?: ViewStyle;
  },
  "screenOptions"
>;

const CustomTabs = cssInterop(
  ({ headerStyle, ...props }: CustomTabsProps) => (
    <Tabs screenOptions={{ headerStyle }} {...props} />
  ),
  {
    headerClassName: "headerStyle",
  }
);
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by vladcos** [comment]
**Theme provider integration**

Definition:
`
import { DefaultTheme, ThemeProvider } from '@react-navigation/native'
import { useColorScheme, cssInterop } from 'nativewind'

import type { Theme } from '@react-navigation/native'

import type { ReactNode } from 'react'
import './global.css'

const InteropThemeProvider = cssInterop(
  ({
    children,
    ...colors
  }: Theme['colors'] & { readonly children: ReactNode }) => {
    const { colorScheme } = useColorScheme()
    return (
      <ThemeProvider
        value={{
          dark: colorScheme === 'dark',
          colors,
        }}
      >
        {children}
      </ThemeProvider>
    )
  },
  Object.fromEntries(
    Object.keys(DefaultTheme.colors).map((name) => [
      name,
      {
        target: name,
        nativeStyleToProp: {
          color: name,
        },
      },
    ]),
  ) as {
    [K in keyof Theme['colors']]: {
      target: K
      nativeStyleToProp: {
        color: K
      }
    }
  },
)
`

Usage

`
 <InteropThemeProvider
      background="tw-text-background"
      border="tw-text-border"
      card="tw-text-card"
      notification="tw-text-background"
      primary="tw-text-primary"
      text="tw-text-foreground"
    >
      <Stack>
        <Stack.Screen name="(tabs)" options={{ headerShown: false }} />
        <Stack.Screen name="+not-found" />
      </Stack>
    </InteropThemeProvider>
`

**Comment by kevingjs** [comment]
Tried @kachidk solution and doesn't work, can anyone help me please? My header its not red 😭

### My code:

```tsx

import { Tabs } from 'expo-router';
import { cssInterop } from 'nativewind';
import House from '@icons/House';
import Settings from '@icons/Settings';

import { ComponentProps } from 'react';
import { ViewStyle } from 'react-native';

type TabsProps = Omit<
    ComponentProps<typeof Tabs> & {
        headerStyle?: ViewStyle;
    },
    'screenOptions'
>;

const CustomTabs = cssInterop(
    ({ headerStyle, ...props }: TabsProps) => (
        <Tabs
            screenOptions={{ headerStyle }}
            { ...props }
        />
    ),
    {
        headerClassName: { target: 'headerStyle' }
    }
);

const TabLayout = () => {
    return (
        <CustomTabs headerClassName='bg-red-500'>
            <Tabs.Screen
                name="index"
                options={{
                    title: 'Home',
                    tabBarIcon: ({ color }) => (
                        <House color={ color } size={ 24 } />
                    )
                }}
            />
            <Tabs.Screen
                name="config"
                options={{
                    title: 'Settings',
                    tabBarIcon: ({ color }) => (
                        <Settings color={ color } size={ 24 } />
                    )
                }}
            />
        </CustomTabs>
    );
};

export default TabLayout;
```

### Screenshot result:

![Image](https://github.com/user-attachments/assets/705db31c-d18a-4a66-9b18-7692b39ea187)

**Comment by joernroeder** [comment]
@vladcos did you manage to make this work with dark/light mode?
