### ISSUE TITLE
VSC Update to v 1.85.0

### ISSUE THREAD

**Issue by DMed98** [nativewind/nativewind#695]
Project has the app.d.ts file with
/// <reference types="nativewind/types" />

Working fine.

After VSC latest 1.85.0 v update the error className is not defined is appearing, tried downgrading vsc and everything works fine.

**Comment by nazim-musayev** [comment]
I am also experiencing this issue starting from yesterday. VSCode v 1.85.0. Property 'className' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<View> & Readonly<ViewProps>'.

**Comment by Vaib215** [comment]
Same issue

**Comment by robcaldecott** [comment]
Same issue here and other declarations in our `app.d.ts` seem be ignored (such as for `.svg` files.) Commenting out the `/// <reference types="nativewind/types" />` makes no difference either, neither does a TS update (we're on `5.2.x`)

Looking at the VS Code TypeScript logs I see then when restarting the TS server:

```
2023-12-20 14:39:06.263 [info] Using tsserver from: /Applications/Visual Studio Code.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js undefined
2023-12-20 14:39:06.263 [info] <syntax> Forking...
2023-12-20 14:39:06.264 [info] <syntax> Starting...
2023-12-20 14:39:06.264 [info] <semantic> Forking...
2023-12-20 14:39:06.264 [info] <semantic> Starting...
2023-12-20 14:39:06.269 [error] TSServer exited. Code: null. Signal: SIGTERM
```

No idea if that error is related but it sure looks fishy.

**Comment by robcaldecott** [comment]
OK, fixed it. I renamed `app.d.ts` to `declarations.d.ts` and it's working. I have a file called `App.tsx` in the same folder as `app.d.ts` so maybe that's causing the VS Code TS support to get confused?

**Comment by robcaldecott** [comment]
Found a better solution: make VS Code use your local project version of TS instead of the built-in one. Much more future proof. Just create a `.vscode/settings.json` file that contains this:

```
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

https://x.com/housecor/status/1739622823004434791?s=20

**Comment by shikhardixitprojects** [comment]
Tried the above ^ still not working for me. 

<img width="704" alt="Screenshot 2024-01-02 at 1 54 30 AM" src="https://github.com/marklawlor/nativewind/assets/45184269/c3156363-19ef-419c-be0f-f8c5d21e17eb">

tsconfig.json:
```
{
  "extends": "@tsconfig/react-native/tsconfig.json",
  "include": ["src"],
  "exclude": ["__tests__/**/*-test.ts"]
}
```

my-app.d.ts (is in my src folder):
```
/// <reference types="nativewind/types" />
```

tailwind.config.js:
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './App.{js,jsx,ts,tsx}',
    './src/DailyUpdate/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
  output: 'native',
};
```

**Comment by robcaldecott** [comment]
@shikhardixitprojects did you restart VS Code? What happens if you open a `.ts` or `.tsx` file, do `CMD+SHIFT+P` and choose `Select Typescript version`?

![image](https://github.com/marklawlor/nativewind/assets/796702/374642b6-9e2a-4c9c-9d13-53a51ba99f49)

As soon as I did this the issue went away for me but my version of TS could be different to yours.

**Comment by shikhardixitprojects** [comment]
@robcaldecott Yep, restarted VS code as well as installed same version as you for typescript & Select Typescript version from workspace:
<img width="1023" alt="Screenshot 2024-01-02 at 10 11 42 AM" src="https://github.com/marklawlor/nativewind/assets/45184269/0fedbdb1-71ea-4620-b1e0-ea4664ecf237">

still seeing the issue unfortunately

**Comment by robcaldecott** [comment]
@shikhardixitprojects do you have a `my-app.ts` or `my-app.tsx` file? My first solution was to rename our `app.d.ts` file (we also have an `App.tsx` and I thought maybe that was confusing TS).

Very odd that the TS version trick doesn't work for you though. I don't know what else to suggest unless there is anything VS Code could be caching somewhere?

**Comment by robcaldecott** [comment]
@shikhardixitprojects your VS Code TS version is odd... is it an insiders build? Maybe that's relevant?

**Comment by shikhardixitprojects** [comment]
@robcaldecott That is just from a plugin I installed (to get latest TS version)
<img width="598" alt="Screenshot 2024-01-02 at 10 20 56 AM" src="https://github.com/marklawlor/nativewind/assets/45184269/62168301-d097-422a-940a-0b780ec0efcd">

I un-installed the plugin, went through same steps, have the same screen as you now, but still failing :/

<img width="875" alt="Screenshot 2024-01-02 at 10 21 31 AM" src="https://github.com/marklawlor/nativewind/assets/45184269/29ee52dd-33ea-4396-84d2-abcd16d33b40">

**Comment by shikhardixitprojects** [comment]
> @shikhardixitprojects do you have a `my-app.ts` or `my-app.tsx` file? My first solution was to rename our `app.d.ts` file (we also have an `App.tsx` and I thought maybe that was confusing TS).
> 
> Very odd that the TS version trick doesn't work for you though. I don't know what else to suggest unless there is anything VS Code could be caching somewhere?

Yep, the `my-app.d.ts` solution was working for me for a while. Then it suddenly stopped working 😭 

<img width="598" alt="Screenshot 2024-01-02 at 10 22 51 AM" src="https://github.com/marklawlor/nativewind/assets/45184269/c2a3c2d5-0478-4f65-ae14-e75310024d5e">

**Comment by nazim-musayev** [comment]
Moving /// <reference types="nativewind/types" /> to declaration.d.ts file fixed the issue for me

**Comment by shikhardixitprojects** [comment]
@nazim-musayev can you share more - it is not working for me :/ 

as in what does your `tailwind.config.js`, `tsconfig.json`, `babel.config.js` look like?

**Comment by nazim-musayev** [comment]
This is only working if reference is placed at the top of the file. I do not think it is related to any of those config files. 
![code3](https://github.com/marklawlor/nativewind/assets/85366399/2c38781d-f3b4-48c3-890d-e8f664bc1a7e)

**Comment by nazim-musayev** [comment]
> @shikhardixitprojects This is only working if reference is placed at the top of the file. I do not think it is related to any of those config files. ![code3](https://private-user-images.githubusercontent.com/85366399/294028245-2c38781d-f3b4-48c3-890d-e8f664bc1a7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzMTYzOTgsIm5iZiI6MTcwNDMxNjA5OCwicGF0aCI6Ii84NTM2NjM5OS8yOTQwMjgyNDUtMmMzODc4MWQtZjNiNC00OGMzLTg5MGQtZThmNjY0YmMxYTdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDIxMDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1MWNkN2U0YzA3MzIyYmUwNDMzY2MyOTBlYzliMmQxZTllZGRjNTZjMGRiNTdmYTliMmYwY2YwM2RhMWMzYzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bPavAEYE5jvwkhztv7RM7f0-AbPdAD5dFFR2AkpDzLs)

So, this is not working
![code2](https://github.com/marklawlor/nativewind/assets/85366399/03a51163-007c-4be6-8b62-f9208451a0ef)

**Comment by shikhardixitprojects** [comment]
Update figured out a solution. This is not a nativewind issue. In fact, their document covers this:
https://www.nativewind.dev/api/styled

in order to to use this library and not get className prop TS errors, I created `StyledComponents.tsx` with the following code:

```
import {styled} from 'nativewind';
import {
  Text as ReactNativeText,
  View as ReactNativeView,
  TouchableOpacity as ReactNativeTouchableOpacity,
  Pressable as ReactNativePressable,
  TextInput as ReactNativeTextInput,
  SafeAreaView as ReactNativeSafeAreaView,
  FlatList as ReactNativeFlatlist,
  Button as ReactNativeButton,
} from 'react-native';

export const Text = styled(ReactNativeText);
export const View = styled(ReactNativeView);
export const TouchableOpacity = styled(ReactNativeTouchableOpacity);
export const Pressable = styled(ReactNativePressable);
export const TextInput = styled(ReactNativeTextInput);
export const SafeAreaView = styled(ReactNativeSafeAreaView);
export const FlatList = styled(ReactNativeFlatlist);
export const Button = styled(ReactNativeButton);
```

Now className prop is totally valid because components are wrapped by nativewind "styled" function :)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
