### ISSUE TITLE
Support for safe-area-insets

### ISSUE THREAD

**Issue by pvinis** [nativewind/nativewind#730]
I see that tailwind kind of has this with env vars, and nativewind has the hairlindWidth that is dependent on the device, so maybe we could have a way to have `mb-safe` etc in nativewind?

**Comment by marklawlor** [comment]
I've been thinking about this. We might have to add [react-native-safe-area-context](https://github.com/th3rdwave/react-native-safe-area-context) as a dependency. As long as your app has a root `<SafeAreaProvider>` these could work.

**Comment by pvinis** [comment]
most if not all apps have that as a dep. all navigation libs need this, expo router, react navigation etc. its basically the default.

I think that would be amazing to have here. I could try to make a PR if you could maybe point me somewhere?

**Comment by alexandrius** [comment]
@marklawlor is there any workaround for this? Can we extend theme in runtime?

**Comment by alexandrius** [comment]
I achieved fairly elegant solution for this:

### tailwind.config.js
```js
/** @type {import('tailwindcss').Config} */
const colors = require('./src/constants/colors');
const dimens = require('./src/constants/dimens/defined');
module.exports = {
  content: ['./src/app/**/*.{js,jsx,ts,tsx}', './src/components/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors,
      spacing: {
        ti: 'var(--spacing-top-inset)',
        bi: 'var(--spacing-bottom-inset)',
        hi: 'var(--spacing-header-inset)',
        fi: 'var(--spacing-footer-inset)',
      },
      sizing: {
        ...dimens.heights,
        ...dimens.widths,
        ...dimens.sizes,
      },
    },
  },
};
```


### theme.js
```js
import { vars } from 'nativewind';
import { getBottomInset, getTopInset } from 'rn-iphone-helper';

import { heights } from '@/constants/dimens';

const topInset = getTopInset();
const bottomInset = getBottomInset();

const theme = {
  '--spacing-top-inset': topInset,
  '--spacing-bottom-inset': bottomInset,
  '--spacing-header-inset': topInset + heights.header,
  '--spacing-footer-inset': bottomInset || 20,
};

export default vars(theme);
```

### Usage

```jsx
<GestureHandlerRootView style={[{ flex: 1 }, theme]}>
    <View className='flex-1 pt-ti pb-bi'>
        <View className='flex-1 bg-black' />
    </View>
</GestureHandlerRootView>
```

**Comment by pvinis** [comment]
oh SNAP! I did not know you can set cars from js. I'll try that, thanks!

**Comment by elmaxe** [comment]
> oh SNAP! I did not know you can set cars from js. I'll try that, thanks!

CSS variables is only supported for v4 fyi

**Comment by alexandrius** [comment]
@pvinis You can achieve similar thing by In V2 by `NativeWindStyleSheet`

**Comment by natew** [comment]
@marklawlor just a heads up you may want to check, it's been a while but last I checked that library caused a repaint/reflow on initial render that significantly impacted lighthouse scores.

**Comment by marklawlor** [comment]
@natew Yep I'm aware. Luckily, we would never load `react-native-safe-area-context` on web, as people should be using [`env()`](https://developer.mozilla.org/en-US/docs/Web/CSS/env).

The trick is trying to work out an elegant way to implement this. The plan is

### Native

Override the `dvh`, `lvh`, and `svh` tailwind plugin to use `var()` instead of `env()`
Provide an `safeAreaVars` export that people can use at the root of their project

### Web

No change. `safeAreaVars` is undefined

### Example usage

```tsx
import { safeAreaVars } from 'nativewind'

export function MyApp({ style, ...props }) {
  return <View style={[safeAreaVars, style]} {...props} />
}
```

**Comment by elmaxe** [comment]
I see this has been added in 4.0.36 🥳 : https://github.com/marklawlor/nativewind/commit/4acc98867e1a4a30f5ee0c24f717711cbebfc78e

**Comment by marklawlor** [comment]
They are in progress and not yet fully available.

If you'd like to try them you can either copy/paste the plugin or use a custom css class.

**Comment by pvinis** [comment]
My only issue with the suggestion @alexandrius, is that I would like to do something like `mt-safe` and it would pick the top inset. Then do `mb-safe` and pick the bottom inset. And finally `m-safe` and it should pick top bottom left right insets.

In my mind i thought something like:
```
extend: {
  margin: {
    safe: {
      top: insets.top,
      bottom: insets.bottom,
...
}}}
```

**Comment by marklawlor** [comment]
If you set `mt-safe` multiple times it will push things down, because you are declaring multiple margins. 

If you don't want multiple margins you can use `absolute top-safe` to position it with `position: absolute`

**Comment by Brunowilliang** [comment]
@marklawlor I can't import the: { useSafeArea Env } from "nativewind";
to use the safe area

**Comment by martinezguillaume** [comment]
You can import it with
```js
// tailwind.config.js
  plugins: [require('nativewind/dist/tailwind/safe-area').safeArea],
```
and
```tsx
import {useSafeAreaEnv} from 'react-native-css-interop/dist/runtime/api'
```

one thing, `*-safe-or*` and `*-safe-offset*` are not working for me

**Comment by trevorpfiz** [comment]
@martinezguillaume I am following https://www.nativewind.dev/v4/tailwind/new-concepts/safe-area-insets, but struggling to get this to work. How are you using `useSafeAreaEnv`? it is returning `{}` when I `console.log(useSafeAreaEnv());`, but when I `console.log(useSafeAreaInsets());` I get `{"bottom": 34, "left": 0, "right": 0, "top": 59}`

```
const safeAreaEnv = useSafeAreaEnv();
console.log(safeAreaEnv);
```

**Comment by martinezguillaume** [comment]
For me, what is working
```js
// tailwind.config.js
...
  plugins: [require('nativewind/dist/tailwind/safe-area').safeArea],
```
and
```tsx
// app/_layout.tsx
import {useSafeAreaEnv} from 'react-native-css-interop/dist/runtime/api'

<View style={[{flex: 1}, useSafeAreaEnv()]}>
  <RootLayout />
</View>
```
and finally
```tsx
// screen.tsx
 <View className="mt-safe">
 ...
 </View>
```

**Comment by trevorpfiz** [comment]
@martinezguillaume thanks! this is working for me now.

```
function SafeAreaEnv({ children }: { children: React.ReactNode }) {
  // Add the safe area insets to the render tree
  return <View style={[{ flex: 1 }, useSafeAreaEnv()]}>{children}</View>;
}
```
and then wrapped `Stack`
```
<SafeAreaEnv>
        <Stack>
          <Stack.Screen...
        </Stack>
      </SafeAreaEnv>
```

**Comment by ikotsov** [comment]
> @pvinis You can achieve similar thing in V2 by `NativeWindStyleSheet`

By defining a local class name? How would you approach that?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by ikotsov** [comment]
> We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

How is v4.1 released? In the [releases page](https://github.com/nativewind/nativewind/releases), it seems that v2.0.11 is the latest.
