### ISSUE TITLE
Dark mode toggle not working

### ISSUE THREAD

**Issue by mritul** [nativewind/nativewind#738]
**Describe the bug**
I'm trying to implement dark/light mode by class in React Native but I'm getting an error described below while trying to create a toggle button

**To Reproduce**
Here's my code:

const {toggleColorScheme} = useColorScheme()
<TouchableOpacity className='bg-red dark:bg-dark-orange' onPress={()=>{toggleColorScheme()}}>
         <Text>Press</Text>
</TouchableOpacity>

**Expected behavior**
The colors of dark mode mentioned in the classes by dark: should apply

**ERROR**
Warning: Cannot update a component (`ForwardRef(NativeWind.TouchableOpacity)`) while rendering a different component (`App`). To locate the bad setState() call inside `App`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render

Any assistance would highly be appreciated

**Comment by marklawlor** [comment]
This is resolved in the latest `v4`. Be aware that `bg-red` and `bg-dark-orange` are not valid Tailwind classes.

**Comment by marklawlor** [comment]
I understand. But when you provide code that is meant to be a "reproduction", I can't tell that. I've had many issues where people simply typed the className wrong.
