### ISSUE TITLE
Disabled modifier

### ISSUE THREAD

**Issue by itsyoboieltr** [nativewind/nativewind#754]
Is the `:disabled` modifier implemented? I could not find anything about it in the docs or anywhere, and I tried using it, and it does not seem to work. Is it planned?

**Comment by marklawlor** [comment]
Its planned and technically implemented in the latest versions, but `<TextArea />` uses `enabled={false}` instead of the standard `disabled` prop. I'm not sure how to handle that in a generic nice way yet

**Comment by itsyoboieltr** [comment]
> Its planned and technically implemented in the latest versions, but `<TextArea />` uses `enabled={false}` instead of the standard `disabled` prop. I'm not sure how to handle that in a generic nice way yet.
> 
> React Native RFC to address the problem: [react-native-community/discussions-and-proposals#496](https://github.com/react-native-community/discussions-and-proposals/pull/496)

@marklawlor Is it supposed to work with Pressable? I cannot get it to work. Sample code that does not work on the latest version:

```tsx
<Pressable className={'disabled:bg-gray-400'} disabled>
  <Text>Submit</Text>
</Pressable>
```

The pressable does not have a gray background, even though disabled is true.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
