### ISSUE TITLE
cssInterop Not Working

### ISSUE THREAD

**Issue by ShaneKeney** [nativewind/nativewind#778]
**Describe the bug**
`cssInterop` does not seem to work the way it should based on the documentation for Nativewind v4.

**To Reproduce**
https://github.com/ShaneKeney/repro-example-2
See above repro example.
I have a couple attempts I have tried to make work commented out.

**Expected behavior**
The ability to use a tailwind utility class such as `w-[50px]` with a custom mapped prop for third party libraries.  

e.g. the ability to do something like:

```
<Skeleton colorMode="light" radiusClassName={'rounded-sm'} heightClassName={'h-60'} widthClassName={'w-full'}>
...
</Skeleton>
```

and map the custom props to the corresponding native props for the third part y library.

**Additional context**
This very well might be me misunderstanding how `cssInterop` is intended to work with third party libraries.  Nativewind cos suggest it is not made to be fully compatible with every library out there but the use case here seems to be something `cssInterop` is intended to work with.

See https://discord.com/channels/695411232856997968/1195578705137893387 for additional information

**Comment by HenryWu01** [comment]
I'm facing a same situation here, I'm using a third-party avatar library called ``react-native-userpic``. If I understand the document correctly, this should be working. But I gave me even more confusing error: 
```
Property 'sizeClassName' does not exist on type 'IntrinsicAttributes & Props'. Did you mean 'className'?
```

Here is my code:
**Avatar.tsx**
```TypeScript
import { cssInterop } from 'nativewind';
import { Userpic } from 'react-native-userpic';

const Avatar = cssInterop(Userpic, {
    sizeClassName: {
        target: false,
        nativeStyleToProp: {
            width: 'size'
        }
    }
});

export default Avatar;
```

**Usage**
```TypeScript
<Avatar source={{uri: 'https://fakeimg.pl/200x200'}} sizeClassName='w-6' />
```

**Comment by HenryWu01** [comment]
> I'm facing a same situation here, I'm using a third-party avatar library called `react-native-userpic`. If I understand the document correctly, this should be working. But I gave me even more confusing error:
> 
> ```
> Property 'sizeClassName' does not exist on type 'IntrinsicAttributes & Props'. Did you mean 'className'?
> ```
> 
> Here is my code: **Avatar.tsx**
> 
> ```ts
> import { cssInterop } from 'nativewind';
> import { Userpic } from 'react-native-userpic';
> 
> const Avatar = cssInterop(Userpic, {
>     sizeClassName: {
>         target: false,
>         nativeStyleToProp: {
>             width: 'size'
>         }
>     }
> });
> 
> export default Avatar;
> ```
> 
> **Usage**
> 
> ```ts
> <Avatar source={{uri: 'https://fakeimg.pl/200x200'}} sizeClassName='w-6' />
> ```

As a temporay workaround, I created a custom hook that resolves tailwindconfig and manually transform the value to px for the third-party component. But this is not clean enough and seems a bit ugly in code style.

**Comment by quocluongha** [comment]
@ShaneKeney  I also encounter this issue with React Native `StatusBar` component. I follow the example on the document about `TextInput`, but it seems not working. I changed it to `target: 'style'` and then it worked. Maybe the `target: false` value in document is not working correctly?

Also I also notice that if using `target: 'style'`, there will be Typescript error when the component does not have `style` prop.
```javascript
import { StatusBar } from 'react-native';

cssInterop(StatusBar, {
  className: {
    target: false, //<-- not working
    nativeStyleToProp: {
      backgroundColor: true,
    },
  },
});

cssInterop(StatusBar, {
  className: {
    target: 'style', //<-- this is working but has Typescript error when component does not have style prop
    nativeStyleToProp: {
      backgroundColor: true,
    },
  },
});


```

**Comment by codinsonn** [comment]
> Anyone running into an issue where cssInterop is causing nextjs to throw the following:
> 
> ```
> Unhandled Runtime Error
> ReferenceError: exports is not defined
> 
> Call Stack
> exports
> ..\node_modules\react-native-css-interop\dist\doctor.js (3:0)
> (app-pages-browser)/../../node_modules/react-native-css-interop/dist/doctor.js
> ```

Yes, but only in Next.js, in Expo (native and on web) it works fine. No idea what the issue is here or how to fix it

**Comment by codinsonn** [comment]
> > Anyone running into an issue where cssInterop is causing nextjs to throw the following:
> > ```
> > Unhandled Runtime Error
> > ReferenceError: exports is not defined
> > 
> > Call Stack
> > exports
> > ..\node_modules\react-native-css-interop\dist\doctor.js (3:0)
> > (app-pages-browser)/../../node_modules/react-native-css-interop/dist/doctor.js
> > ```
> 
> Yes, but only:
> 
> * in Next.js (in Expo native and on web it works fine)
> * only in the browser (during SSR with Next, it also works fine, but then crashes with this error in console 🤷‍♂️)
> 
> No idea what the issue is here or how to fix it
> 
> * `react-native-css-interop@0.1.1`
> * `nativewind@4.1.1`
> 
> Both in `transpileModules` field in `next.config.js`

Hi @marklawlor, may have found a bug:

It seems like this line where you `verifyJSX()` in `react-native-css-interop` is causing the entire package to not be transpiled when set in `next.config.js`'s `transpilePackages` field.

Verified with this patch:

`patches/react-native-css-interop+0.1.1.patch`

```diff
diff --git a/node_modules/react-native-css-interop/dist/doctor.js b/node_modules/react-native-css-interop/dist/doctor.js
index 98379be..ef2c281 100644
--- a/node_modules/react-native-css-interop/dist/doctor.js
+++ b/node_modules/react-native-css-interop/dist/doctor.js
@@ -7,7 +7,8 @@ const computedStyles = globalThis.window
     ? globalThis.window.getComputedStyle(globalThis.window.document.documentElement)
     : { getPropertyValue: () => "asdf" };
 function verifyJSX() {
-    return <react-native-css-interop-jsx-pragma-check /> === true;
+    return true
+    // return <react-native-css-interop-jsx-pragma-check /> === true;
 }
 function verifyFlag(name, value = "true") {
     return globalThis.window

```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
