### ISSUE TITLE
Latest version 4.0.33 breaks EAS Updates

### ISSUE THREAD

**Issue by edmbn** [nativewind/nativewind#796]
**Describe the bug**
After installing my dependencies I got automatically upgraded to `4.0.33` and got this error when trying to make an OTA update via EAS Updates:

`src/styles.css: Cannot read properties of undefined (reading 'raw')`

**Additional context**
I was using before "^4.0.23" and can confirm that getting back to 4.0.23 is working fine. There have been multiple new versions this last 2 days so I don't know exactly when it broke.

**Comment by pnodet** [comment]
Running into the same issue

**Comment by ghmendonca** [comment]
Also having the same issue! This could be related to #637

**Comment by marklawlor** [comment]
The `main` branch had a potential fix but I'm away over the weekend and cannot test & release. Feel free to test yourself using patch-package.

**Comment by mdwekat** [comment]
+1

**Comment by Darkhorse-Fraternity** [comment]
+1

**Comment by AyoCodess** [comment]
same issue
![Uploading Screenshot 2024-02-18 at 13.05.28.png…]()

**Comment by garygcchiu** [comment]
Happening for me as well

**Comment by marklawlor** [comment]
Please try `4.0.34`. Its hard to debug people's builds and Metro isn't the easiest to work with, so let me if you still have issues. Any logs would be appreciated.

**Comment by Bahnasawy** [comment]
`4.0.35` Fixed it for me

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
