### ISSUE TITLE
Adding a react-native Modal breaks the fonts on another screen. 

### ISSUE THREAD

**Issue by eriktoor** [nativewind/nativewind#799]
I have a header that I want to have a modal on called ImageFlaggedModal and the basic structure is this
![image](https://github.com/marklawlor/nativewind/assets/30181835/862274a1-32cf-4e0c-8bcc-43e466a5ae3c)

After adding

`<ImageFlaggedModal visible={imageFlaggedVisible} setVisible={setImageFlaggedVisible} />`

Which I have reduced to only having just an empty Modal component. It changes all of the fonts on another screen so that they now are the default font rather than the expected font.

![image](https://github.com/marklawlor/nativewind/assets/30181835/85c643d4-c5f4-43bb-9217-dd52723344f2)

Before adding the modal my fonts are poppins as expected on another screen.

![image](https://github.com/marklawlor/nativewind/assets/30181835/7965b21a-6552-4cb4-8bec-fb909fea5256)
Before adding ImageFlaggedModal ^^ 

And with the ImageFlaggedModal in that component (as show in the first image above) my font goes back to the default font only for my SettingsScreen.tsx.

![image](https://github.com/marklawlor/nativewind/assets/30181835/44fe211b-935a-4c61-9ab5-537bd723a3bd)

Does anyone have any ideas why adding this Modal would mess with my fonts on another screen?

My native wind version: "nativewind": "^2.0.11"

**Comment by eriktoor** [comment]
Hey @marklawlor thanks for the quick reply. I just struggled through making this work for the last 10 minutes but I can confirm that this works even when I add back the modal if I use inline styles like this 
new (with inline styles) & old (with native wind) side by side
<img width="409" alt="Screenshot 2024-02-16 at 8 46 34 PM" src="https://github.com/marklawlor/nativewind/assets/30181835/047ef31f-3fec-4b3d-8a6d-fdb2a22a1840">

code: 
<img width="705" alt="Screenshot 2024-02-16 at 8 46 48 PM" src="https://github.com/marklawlor/nativewind/assets/30181835/e0e5e7dd-488f-4291-adfb-5acfe67f7378">

**Comment by marklawlor** [comment]
Can you please share the repo. I cannot debug via screenshots

**Comment by eriktoor** [comment]
OK Give me 10 minutes I can get that to you.

**Comment by eriktoor** [comment]
The public repo is https://github.com/eriktoor/native-wind-issue

- Header is in mobile/components/swipe/HeaderHome.tsx
- Profile Screen that has the working inline styles but the not working nativewind styles is mobile/screens/Profile/ProfileScreen.tsx
- HeaderHome is used in mobile/screens/Home/HomeScreen.tsx
- ImageFlaggedModal is in mobile/components/modals/ImageFlaggedModal.tsx

**Comment by eriktoor** [comment]
Hey @marklawlor I wanted to note that if I remove the ImageFlaggedModal.tsx from the HeaderHome.tsx screen and put it into the HomeScreen.tsx like this

```
export default function HomeScreen({ liveShowUUID }: { liveShowUUID?: string }) {
  const navigation = useNavigation()
  const { user, logout } = useAuth()

  const bottomSheetRef = useRef(null)
  const handleClose = () => {
    bottomSheetRef.current?.dismiss()
  }

  const [imageFlaggedVisible, setImageFlaggedVisible] = React.useState(false)

  useEffect(() => {
    if (liveShowUUID) {
      bottomSheetRef.current?.present()
    }
  }, [liveShowUUID])

  return (
    <>
      <View className="bg-primaryBlack h-full">
        <SafeAreaView className="flex-1">
          <HeaderHome setImageFlaggedVisible={setImageFlaggedVisible} />
          <ImageFlaggedModal visible={imageFlaggedVisible} setVisible={setImageFlaggedVisible} /> // CHANGE HERE @marklawlor 

          <CardSwiperV2 />
        </SafeAreaView>
        <CustomBottomBar />
      </View>
      <BottomSheetComponent
        snapPoints={[`45%`]}
        bottomSheetRef={bottomSheetRef}
        handleClose={handleClose}
        content={<LiveShowItem liveShowUUID={liveShowUUID} handleClose={handleClose} />}
      />
    </>
  )
}
```

It fixes the problem. However, in this project I am having the same issue where when I try to change this to use a TabNavigator, the fonts stop working even though they will work with inline styling.

**Comment by marklawlor** [comment]
This is a large repo for me to troubleshoot, can you please provide a minimal reproduction of the issue?

My time to troubleshoot individual issues is limited, so the smaller and easier to you can make this for me the better I can help you

Have you also tried upgrading to NativeWind v4? It may already fix your issue.

**Comment by eriktoor** [comment]
I tried upgrading to v4 and had a lot of issues and gave up on it after 3-4ish hours. Is it possible there is any additional documentation for troubleshooting issues other than this documentation? https://www.nativewind.dev/v4/overview

I will try to produce a minimal example with nativewind v2 and get that back to you.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
