### ISSUE TITLE
Support `:not()` selector

### ISSUE THREAD

**Issue by marklawlor** [nativewind/nativewind#805]
This feature is need to correctly support `:disabled` for the core TextInput https://github.com/marklawlor/nativewind/issues/754

If we supported `:not()`, `:disabled` would be outputted as

```css
.my-class[disabled] {}
.my-class:not([enabled]) {}
```

Media queries already have a `qualifier`, so attribute queries could use the same logic. 

`:not(.my-class)` is an alias for `.not([className~=my-class])`

This would be useful for `groups`, e.g `group-[:not(.primary)]:color-white`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
