### ISSUE TITLE
Fast Refresh Not working with monorepo

### ISSUE THREAD

**Issue by Jm-Zion** [nativewind/nativewind#806]
Hello there, 

First of all, thanks for this amazing project.

I followed the documentation to configure the app in a monorepo using yarn workspaces. 

When I'm updating classnames from the inside apps/expo-app/App.tsx, FastRefresh is working well. 
When I'm updating classnames from the inside packages/ui-kit/src/input/input.variant.ts, FastRefresh is not working ( styles are not updated ) , I've to press R.

> Classnames are generated, I checked it with the command : 
```
npx tailwindcss -o ../../node_modules/.cache/nativewind/global.css.ios.css --watch
```

But I have to press R to get result displayed on screen ( instead of just waiting for fast refresh )

**To Reproduce**

Repro : https://github.com/Jm-Zion/expo-mono 

Clone / Install 

Run ```yarn```

From `apps/expo-app` run `yarn ios`

Update classnames form 'apps/expo-app/src/App.tsx' (line 13) -> classnames updated / UI updated on FastRefresh
Update classnames form 'packages/ui-kit/src/input/input.variant.tsx' (line 13) -> classnames updated / UI **not** updated on FastRefresh

**Expected behavior**

Styles should updates even when updated from packages.

**Comment by Jm-Zion** [comment]
Oh sorry for that, I switched the visibility you should access it now

**Comment by LightBounded** [comment]
I'm getting a similar issue to this in my own monorepo, any updates?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
