### ISSUE TITLE
[Question] V4: Correct way to use cssInterop with 3rd-party components

### ISSUE THREAD

**Issue by HenryWu01** [nativewind/nativewind#808]
I'm using a third party user avatar library called [react-native-userpic](https://github.com/kolking/react-native-userpic/blob/main/src/Userpic.tsx). It accpets an property called size to controll the size of the avatar as shown below:
```TypeScript
export interface Props extends ViewProps {
  size?: number;
  name?: string;
  email?: string;
  source?: ImageSourcePropType;
  defaultSource?: ImageSourcePropType;
  color?: string;
  radius?: number;
  colorize?: boolean;
  style?: StyleProp<ImageStyle>;
  textStyle?: StyleProp<TextStyle>;
  badge?: BadgeProps['value'];
  badgeColor?: BadgeProps['color'];
  badgeProps?: Omit<BadgeProps, 'value' | 'color' | 'parentRadius'>;
}

const Userpic = ({
  size = 50,
  name,
  email,
  source,
  defaultSource = DEFAULT_SOURCE,
  color = DEFAULT_COLOR,
  radius = size / 2,
  colorize = false,
  style,
  textStyle,
  badge,
  badgeColor,
  badgeProps,
  ...props
}: Props) => {
```

I have created a minimum reproducible example below:
```TypeScript
import './global.css';

import { cssInterop } from 'nativewind';
import { Userpic } from 'react-native-userpic';
import { SafeAreaView } from 'react-native-safe-area-context';

cssInterop(Userpic, {
  sizeName: {
    target: false,
    nativeStyleToProp: {
      width: 'size'
    }
  }
});

export default function App() {
    return (
      <SafeAreaView>
        <Userpic sizeName='w-64' />
        <Userpic size={256} />
      </SafeAreaView>
    );
}
```

``w-64`` in my environment is same as ``256px``. But when you run the example, you will see that the first avatar have a exact size of original ``50px``. It seems like sizeName does not have any effect on controlling the size of Userpic through cssInterop.  Visual Studio Code will also give an error:
![Code_dzZd95wFPc](https://github.com/marklawlor/nativewind/assets/99880210/12c005d5-121f-40ca-aaed-b35e0319dad5)

> To be more specific, I am running with Expo SDK 50, Nativewind 4.0.33 on an Android device with command ``npx expo start --clear``

Am I using this feature incorrectly? #778 seems to be a same issue with my situation.

**Comment by kdwkr** [comment]
you need to declare types.

https://github.com/marklawlor/nativewind/blob/main/packages/react-native-css-interop/types.d.ts

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
