### ISSUE TITLE
Rotate classNames no longer working

### ISSUE THREAD

**Issue by TheDunco** [nativewind/nativewind#819]
**Describe the bug**
Updating from NativeWind v40.0.23 to v4.0.36 seems to have broken the rotate classes (e.g. `rotate-90`)

**To Reproduce**
1. Using NativeWind v4.0.23, verify that an element such as an SVG with the `rotate-90` className applied properly rotates
2. Upgrade to NativeWind v4.0.36
3. Provide the same `rotate-90` className to the element
2. It doesn't have an effect

**Expected behavior**
The `rotate` class should be applied and rotate the element.

**Expo Snack**
(Tried unsuccessfully to make a Snack with Nativewind 4)

**Additional context**
I've been able to replace every instance of this className with `style={{ transform: [{ rotate: '90deg' }] }}` in my codebase but wanted to report this issue nonetheless.

**Comment by theblondealex** [comment]
can you provide a repo to debug? I have tested by forking the repo and running the expo example from 4.0.36 [here](https://github.com/marklawlor/nativewind/blob/main/examples/expo-router/app/(tabs)/index.tsx)

Rotate worked across all native components, for svg components tailwind itself doesnt support rotate for svg components see [here ](https://tailwindcss.com/docs/fill)all supported tw classes for svg components - note the fill class I tested works.

**Comment by moritzlang** [comment]
After upgrading to Expo SDK 50 and nativewind 4.0.36 the SVG styles did not apply anymore for me.
Previously I would render something like:
```jsx
import Arrow from "@icons/arrow.svg"
<Arrow classname="w-24 h-24 text-black" />
```
I needed to adjust my code to use [cssInterop](https://www.nativewind.dev/v4/tailwind/svg/fill#usage) in order to make this work. Also `rotate-90` works on those `<Svg />` components.

**Comment by badalsaibo** [comment]
I cannot apply `className` styles on SVG starting from `v4.0.1` itself. It worked fine on `v2`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
