### ISSUE TITLE
[V4] SSR Vite does not work

### ISSUE THREAD

**Issue by ceopaludetto** [nativewind/nativewind#824]
**Describe the bug**
I'm getting errors related to `module.exports` when I try to use Nativewind 4 + Vite in a SSR environment(like remix). A ESM version of `nativewind/jsx-runtime` can be provided as well?

**To Reproduce**
https://stackblitz.com/edit/remix-run-remix-brj5fl

**Expected behavior**
Everything should work just like the CSR environment

**Screenshots**
<img width="923" alt="Screenshot 2024-02-23 at 16 55 20" src="https://github.com/marklawlor/nativewind/assets/30508218/1f073dea-88dd-48e4-94d3-b0b83b3b74c3">

**Additional context**
I've tried a CSR vite environment and it just works

**Comment by ceopaludetto** [comment]
> > I've tried a CSR vite environment and it just works
> 
> Hey @ceopaludetto, would you mind sharing how please? I can't seem get this to work!
> 
> ```js
> // https://stereobooster.com/posts/react-native-web-with-vite/
> import react from '@vitejs/plugin-react-swc'
> import path from 'path'
> import { defineConfig } from 'vite'
> // import { esbuildFlowPlugin } from "@bunchtogether/vite-plugin-flow";
> 
> // https://tamagui.dev/docs/intro/installation
> const extensions = [
>   '.web.tsx',
>   '.tsx',
>   '.web.ts',
>   '.ts',
>   '.web.jsx',
>   '.jsx',
>   '.web.js',
>   '.js',
>   '.css',
>   '.json',
>   '.mjs',
> ]
> 
> const development = process.env.NODE_ENV === 'development'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   clearScreen: true,
>   plugins: [react()],
>   define: {
>     // https://github.com/bevacqua/dragula/issues/602#issuecomment-1296313369
>     global: 'window',
>     __DEV__: JSON.stringify(development),
>     // https://tamagui.dev/docs/intro/installation
>     DEV: JSON.stringify(development),
>     'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV),
>   },
>   resolve: {
>     extensions,
>     alias: {
>       'react-native': 'react-native-web',
>       '@repo/ui': path.resolve('../../packages/ui'),
>       '@repo/lib': path.resolve('../../packages/lib'),
>     },
>   },
>   optimizeDeps: {
>     esbuildOptions: {
>       resolveExtensions: extensions,
>       // https://github.com/vitejs/vite-plugin-react/issues/192#issuecomment-1627384670
>       jsx: 'automatic',
>       jsxImportSource: 'nativewind',
>       // need either this or the plugin below
>       loader: { '.js': 'jsx' },
>       // plugins: [
>       //   esbuildFlowPlugin(/\.(flow|jsx?)$/, (path) =>
>       //     /\.jsx$/.test(path) ? "jsx" : "jsx"
>       //   ),
>       // ],
>     },
>   },
>   // build: {
>   //   emptyOutDir: false,
>   // },
> })
> ```

@tomhendra try to use `verifyInstallation` to check if your installation is correct:

```ts
import { verifyInstallation } from "nativewind"
```

Also check if the nativewind version is `^4.0.36`.

An working example on stackblitz: https://stackblitz.com/edit/vitejs-vite-5kagam?file=vite.config.ts

**Comment by tomhendra** [comment]
> @tomhendra try to use `verifyInstallation` to check if your installation is correct:
> 
> ```ts
> import { verifyInstallation } from "nativewind"
> ```
> 
> Also check if the nativewind version is `^4.0.36`.
> 
> An working example on stackblitz: https://stackblitz.com/edit/vitejs-vite-5kagam?file=vite.config.ts

Thanks very much @ceopaludetto!

**Comment by theronaldostar** [comment]
import react from "@vitejs/plugin-react-swc";
import { defineConfig } from "vite";

export default defineConfig({
	define: {
		global: "window",
		loader: { ".js": "jsx" },
	},
	optimizeDeps: { include: [] },
	plugins: [react({ jsxImportSource: "nativewind" })],
	resolve: {
		alias: {
			"react-native": "react-native-web",
			"react-native-svg": "react-native-svg-web",
		},
		extensions: [".css", ".json", ".web.js", ".web.ts", ".web.tsx", ".js", ".ts", ".tsx"],
	},
	server: { port: 3000, host: true },
});

**Comment by zoriya** [comment]
@ceopaludetto Could you get react-native-web working in an SSR context before trying to run nativewind there? I don't think it currently works. Cf: https://github.com/vitejs/vite/issues/16679

**Comment by ceopaludetto** [comment]
Maybe you need to do an alias in the package.json instead of doing only in vite resolve.alias section. Something like this:

```json
{
  "dependencies": {
    "react-native": "npm:react-native-web"
  }
}
```

Since in the SSR mode we do not bundle dependencies into the final build, vite discard alias related to packages. Also, I don't know if react ssr streaming mode works, since we need to inject a style tag after calling AppRegistry

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
