### ISSUE TITLE
When a child component within `TouchableOpacity` has a `hover` style, the `onPress` event cannot be triggered

### ISSUE THREAD

**Issue by Jianlong-Nie** [nativewind/nativewind#825]
When a child component within `TouchableOpacity` has a `hover` style, the `onPress` event cannot be triggered,when i remove  
```
isSelected
               ? "md:border-r md:border-passes-primary md:bg-passes-primary/25"
               : "hover:border-r hover:border-passes-gray-medium hover:bg-passes-gray-dark"
```  
then the button can work fine,and this code can work fine with `nativewind 2`,but not with `nativewind 4.0.36`

```
 <TouchableOpacity
        className="rounded-l w-[300px] h-[45px] bg-passes-primary mt-4"
        onPress={() => {
          onNavigationToActiveTab(id)
        }}
      >
        <View
          className={classNames(
            "w-full flex-row items-center justify-between border-r p-2.5 pr-3 transition-colors"
             isSelected
               ? "md:border-r md:border-passes-primary md:bg-passes-primary/25"
               : "hover:border-r hover:border-passes-gray-medium hover:bg-passes-gray-dark"
          )}
        >
          <Text className="text-lg font-semibold">{name}</Text>
          <ChevronRight color={colors.passes.dark} size={IconSize.sm} />
        </View>
      </TouchableOpacity>
```
**Expected behavior**
when user click this `button``,onPress` can be triggered

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by Jianlong-Nie** [comment]
Additionly,if the view style include  ` "active:opacity-50"` then it also will work

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
