### ISSUE TITLE
[V4] Performance issue when changing the color scheme [Old Architecture]

### ISSUE THREAD

**Issue by alisherks** [nativewind/nativewind#828]
**Describe the bug**
There appears to be a noticeable performance issue when rendering a large number of components on the screen with the dark color variant. When changing the color scheme, JS thread seems to hang for a while. React Dev Tools FlameGraph shows a separate commit for each View.

I submitted a [PR](https://github.com/marklawlor/nativewind/pull/820) that batches the effects update and solves the JS thread hanging issue, but that change introduced unpredictable behavior.

**To Reproduce**
Clone the [repo](https://github.com/alisherks/nativewind-performance.git)
Change the color scheme.

**Expected behavior**
Ideally, it's preferable to have a single commit.

**Screenshots**
FlameGraph
| Current main |  PR  |
| ---------- |-----------|
| ![Screenshot 2024-02-26 at 20 04 34](https://github.com/marklawlor/nativewind/assets/10130569/08aa0bcb-7806-4bb5-8c62-002270e11368) | ![Screenshot 2024-02-26 at 20 06 24](https://github.com/marklawlor/nativewind/assets/10130569/fbdba4a2-83ce-421d-ad62-e46695d9fdde)|

| Current main (Release)       | PR (Release)         |
| ---------- |-----------|
|![](https://github.com/marklawlor/nativewind/assets/10130569/4ff04c47-a105-4d95-b003-98741f789d9c)|![](https://github.com/marklawlor/nativewind/assets/10130569/2d267f58-1128-4fbf-9728-fd3370e230b9) |

**Additional context**
This doesn't happen if you turn on the concurrent mode.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
