### ISSUE TITLE
Metro error None of these files exist:  @tailwind base;

### ISSUE THREAD

**Issue by devcomtal8** [nativewind/nativewind#838]
**Describe the bug**
After a fresh install using `https://createexpostack.com/`

when starting app I get the following errror
```
Metro error: Unable to resolve module /app/node_modules/.cache/nativewind/global.css from /app/global.css: 

None of these files exist:
  * ../app/node_modules/.cache/nativewind/global.css(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
  * ../app/node_modules/.cache/nativewind/global.css/index(.web.ts|.ts|.web.tsx|.tsx|.web.js|.js|.web.jsx|.jsx|.web.json|.json|.web.cjs|.cjs|.web.mjs|.mjs|.web.scss|.scss|.web.sass|.sass|.web.css|.css|.web.css|.css)
> 1 | @tailwind base;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | @tailwind components;
  3 | @tailwind utilities;
  4 |


```

**To Reproduce**
1. Create new app using `createexpostack` with nativewind and expo-router
```
"nativewind": "^4.0.1",
"expo-router": "^3.4.6",
```
2. run `yarn start`
3. start web
4. Error

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by juanchaur** [comment]
I've seen the same issue

**Comment by theblondealex** [comment]
There’s not enough context to help here...

- did you follow the installation steps?
- what does your metro config look like? 
- have you installed tailwind? 
- did you setup your global.css file and import it

...create/attach a repo with your files or more information otherwise it's hard to help you :)

**Comment by devcomtal8** [comment]
Here's a fresh repo we just created following the steps:
https://github.com/devcomtal8/test-me

metro.config.js
```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

/** @type {import('expo/metro-config').MetroConfig} */
// eslint-disable-next-line no-undef
const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' });

```
package.json
```
{
  "name": "test-me",
  "version": "1.0.0",
  "scripts": {
    "android": "expo start --android",
    "format": "eslint \"**/*.{js,jsx,ts,tsx}\" --fix && prettier \"**/*.{js,jsx,ts,tsx,json}\" --write",
    "ios": "expo start --ios",
    "start": "expo start",
    "web": "expo start --web"
  },
  "dependencies": {
    "nativewind": "^4.0.1",
    "@react-navigation/native": "^6.1.7",
    "react-native-gesture-handler": "~2.14.0",
    "react-native-safe-area-context": "^4.8.2",
    "react-native-screens": "~3.29.0",
    "@expo/vector-icons": "^14.0.0",
    "expo-linking": "~6.2.2",
    "expo-router": "^3.4.6",
    "expo-constants": "~15.4.5",
    "expo-system-ui": "~2.9.3",
    "expo-web-browser": "~12.8.2",
    "react-dom": "18.2.0",
    "react-native-reanimated": "~3.6.2",
    "react-native-web": "~0.19.6",
    "expo": "~50.0.5",
    "expo-status-bar": "~1.11.1",
    "react": "18.2.0",
    "react-native": "0.73.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/react": "~18.2.14",
    "@typescript-eslint/eslint-plugin": "^6.7.2",
    "@typescript-eslint/parser": "^6.7.2",
    "eslint": "^8.50.0",
    "eslint-config-universe": "^12.0.0",
    "prettier": "^3.0.3",
    "tailwindcss": "^3.4.0",
    "typescript": "^5.1.3"
  },
  "eslintConfig": {
    "extends": "universe/native"
  },
  "resolutions": {
    "expo-modules-core": "~1.11.0"
  },
  "overrides": {
    "expo-modules-core": "~1.11.0"
  },
  "expo": {
    "install": {
      "exclude": [
        "react-native-safe-area-context"
      ]
    }
  },
  "private": true
}


```

Also here's video of the installation and fresh start showing the error:

https://drive.google.com/file/d/1KXu7eMqJW2mArX2lai00X0UUexn-TEgY/view?usp=sharing

**Comment by ImSingee** [comment]
I encountered this error too.

This error only appears the first time (when `node_modules/.cache/nativewind/global.css.web.css` does not exist).

A workaround now (typically in CI) is to create this file manually

```
mkdir -p node_modules/.cache/nativewind
touch node_modules/.cache/nativewind/global.css.web.css

npx expo # build now works
```

**Comment by samlaycock** [comment]
We're experiencing the same issue. @ImSingee's workaround seems to work for now.

**Comment by OgDev-01** [comment]
> I encountered this error too.
> 
> This error only appears the first time (when `node_modules/.cache/nativewind/global.css.web.css` does not exist).
> 
> A workaround now (typically in CI) is to create this file manually
> 
> ```
> mkdir -p node_modules/.cache/nativewind
> touch node_modules/.cache/nativewind/global.css.web.css
> 
> npx expo # build now works
> ```

How will this look like in action on the CI side of things?

**Comment by zuffik** [comment]
Any progress? Happens in gitlab CI for me.

**Comment by fortion71** [comment]
`yarn start -c` seemed to do the trick for me. (I can't be 100% if that's what did it, though, since I was fooling around with other things, but that's the command I ran that finally got things working 😁)

**Comment by csiqueirasilva** [comment]
For those struggling, i put this on my package.json to deploy to github pages:

    # on package.json
    "deploy": "gh-pages -t -d dist"
    "predeploy": "npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css.web.css && expo export -p web"

And we on the team here use it on Dockerfile, run on CI with an on premises Azure Devops, like this:

    # on our web deploy Dockerfile
    RUN npm install && npx expo install && npx tailwindcss -i ./global.css -o ./node_modules/.cache/nativewind/global.css.web.css && npx expo export -p web

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
