### ISSUE TITLE
cssInterop nativeStyleToProp does not work as expected

### ISSUE THREAD

**Issue by Tobertet** [nativewind/nativewind#843]
**Describe the bug**
When nativeStyleToProp is configured like in the docs example https://www.nativewind.dev/v4/api/css-interop, the props are not being generated as expected.

**To Reproduce**
This works fine and passes to the Skeleton component a prop boneStyle with the style contents of boneClassName
```
cssInterop(Skeleton, {
  boneClassName: "boneStyle",
});
```

However, the code below does not generate a "boneColor" prop with the color style passed to boneClassName
```
cssInterop(Skeleton, {
  boneClassName: {
    nativeStyleToProp: {
      color: "boneColor",
    },
    target: false,
  },
});
```
Instead, I can see that it is passing a prop named boneClassName that contains the styles, which is not what is described in the docs.

**Expected behavior**
cssInterop should populate the boneColor prop with the color style passed in a class to boneClassName

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
