### ISSUE TITLE
nativewind lsp for neovim

### ISSUE THREAD

**Issue by m1guer** [nativewind/nativewind#845]
i am testing nativewind andi noted a important thing, the nativewind dont have a lsp or works with normal tailwindcss lsp.

**Comment by believer** [comment]
I'm using the regular `tailwindcss-language-server` installed with Mason and it works correctly with the `className` property. What's your setup like?

<img width="439" alt="Screenshot 2024-03-13 at 09 18 51" src="https://github.com/marklawlor/nativewind/assets/1478102/0b28a75e-c62d-4a33-9a92-10bfd9233d98">

I've only had to add some [special settings](https://github.com/believer/dotfiles/blob/d75c84b4e5f95e77a2822cd0d055cf48e55317d3/nvim/lua/plugins/lsp.lua#L187) to get it working with `cva` and `ts-pattern`.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
