### ISSUE TITLE
Unknown at rule @tailwind

### ISSUE THREAD

**Issue by jmarsh24** [nativewind/nativewind#848]
I followed the documentation to install native wind to an existing expo app and I ran into this warning in vscode. It could be helpful to include instruction on how to deal with this as a hint or instruction in the documentation here.

https://www.nativewind.dev/v4/getting-started/expo-router

<img width="1443" alt="image" src="https://github.com/marklawlor/nativewind/assets/48605824/0978fe46-e012-4d81-b3b1-f2a598ed1098">

I have included an image of the warning.

`Unknown at rule @tailwindcss(unknownAtRules)`

**Comment by glncy** [comment]
Hope this answers your question. https://github.com/tailwindlabs/tailwindcss/issues/13202#issuecomment-1989211271

You can also set on your settings settings.json

Create folder `.vscode` on your root folder then create `settings.json` file inside `.vscode` folder then paste this

```json
{
  "files.associations": {
    "**/*.css": "tailwindcss",
  },
}
```

Make sure to install [Tailwind CSS IntelliSense](https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss) Plugin

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
