### ISSUE TITLE
react-native-css-interop/dist/metro/poll-update-client could not be found within the project or in these directories:

### ISSUE THREAD

**Issue by DavidIlie** [nativewind/nativewind#849]
**Describe the bug**
Creating a fresh project off the T3 template, and I get this error when I try and first launch my project.

**Expected behavior**
The app is supposed to function properly.

**Screenshots**
<img width="1456" alt="image" src="https://github.com/marklawlor/nativewind/assets/47594764/55d539e0-d0bf-4204-bf49-5feabda82268">

**Additional context**
Looking through the sourcecode I found [this](https://github.com/marklawlor/nativewind/blob/a017832f38fe5ce46dfb4f97b1daec1d44bd0955/packages/react-native-css-interop/src/metro/transformer.ts#L44):
```typescript
  if (options.platform !== "web" && options.dev && options.hot) {
    data = `${data}\nrequire("react-native-css-interop/dist/metro/poll-update-client")`;
  }
```

and if I look into my node_modules I see that the file "poll-update-client" does not exist:
<img width="1456" alt="image" src="https://github.com/marklawlor/nativewind/assets/47594764/2ae251a0-e647-43c1-acc2-6a590307662f">

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
