### ISSUE TITLE
useColorScheme broken for dev mode on web

### ISSUE THREAD

**Issue by andrestone** [nativewind/nativewind#850]
When running the bundler in development mode, there seems to be a race condition causing `darkMode` and `darkModeValue` to be empty.

https://github.com/marklawlor/nativewind/blob/a017832f38fe5ce46dfb4f97b1daec1d44bd0955/packages/react-native-css-interop/src/runtime/web/color-scheme.ts#L9-L12

That happens because at the time this code is evaluated, the `--css-interop` variable isn't there yet:

https://github.com/marklawlor/nativewind/blob/a017832f38fe5ce46dfb4f97b1daec1d44bd0955/packages/react-native-css-interop/src/runtime/web/stylesheet.ts#L5-L8

**Comment by matheusmichels** [comment]
Having the same issue here

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
