### ISSUE TITLE
[v4]: Unable to override shadow-styles

### ISSUE THREAD

**Issue by ljukas** [nativewind/nativewind#853]
**Describe the bug**
Extending config for shadow works as long as the prefix dont conflict with default values

**To Reproduce**
Extend theme with a custom shadow, modify either `lg` or `md` or another existing default and try to use it, it will use the default style and not the custom one. Set the custom to ex. `mdx` and it will work.

Tailwindcss documention says to override default values we should set the under `theme` and not `extend` in the config, but this does not work either

**Expected behavior**
Overriding existing values should work

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
