### ISSUE TITLE
remapProps is not a function

### ISSUE THREAD

**Issue by brerdem** [nativewind/nativewind#855]
**Describe the bug**
remapProps function returns undefined

**To Reproduce**
1) install nativewind and dependencies
2) install react-native-elements
3) try to remap props of a RNE element, such as Button

**Expected behavior**
Props should be correctly remapped without errors

![Simulator Screenshot - iPhone 14 - 2024-03-19 at 09 09 00](https://github.com/marklawlor/nativewind/assets/778976/94f2cb0e-993c-4811-9f30-61b9a5b05821)

**Additional context**

Using
nativewind@^4.0.1
react-native@0.72.4
react-native-elements@4.0.0-rc.8
node@18.17.1
MacOS Ventura

I also also cleared Metro's cache and tried to delete and reinstall node_modules

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
