### ISSUE TITLE
TextInput: text color and placeholder color conflict

### ISSUE THREAD

**Issue by stesvis** [nativewind/nativewind#856]
**Describe the bug**
It appears that you can't set the placeholder color and the text color in a `TextInput` without conflicting with each other.
The last class name that you use overwrites the previous one.

**To Reproduce**
```jsx
  // 1
  <StyledTextInput className="text-blue-500 placeholder-red-500" placeholder="Enter something" />
  // 2
  <StyledTextInput className="placeholder-red-500 text-blue-500" placeholder="Enter something" />
```

**Expected behavior**
1. The placeholder should be red. As you start typing, the text color should be blue
2. The placeholder should be red. As you start typing, the text color should be blue

**Actual behavior**
1. The placeholder is red. As you start typing, the text color remains red
2. The placeholder is blue. As you start typing, the text color remains blue

**Expo Snack**
https://snack.expo.dev/@stesvis/hello-world

How do you get test color and placeholder color to work together?

**Comment by mkamran67** [comment]
Ever figure out how to change the placeholder color? I get the conflict too.

**Comment by visualcookie** [comment]
I'm currently at the same problem. As soon as I try to style the placeholder via the prefix with a text color, it overrides somehow the default value and doesn't set the placeholder color. I think that the placeholder should be treated as documented by the `TextInput`: https://reactnative.dev/docs/textinput#placeholdertextcolor

It almost looks as if you can't use the placeholder prefix to style the placeholder but have to use a hex color. Weirdly enough, in the old codebase, where I styled the TextInput with `styled-components` it worked without any issues (dark and light mode).

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
