### ISSUE TITLE
[V4] Styling using className

### ISSUE THREAD

**Issue by oskarleonard** [nativewind/nativewind#857]
**Describe the bug**
When upgrading from "4.0.22" to latest i can no longer attach a className (using nativewind) to the SVGs

**To Reproduce**
```
import DownloadIcon from '~shared/assets/downloadIcon.svg';
<DownloadIcon className="text-white" />
```
The above works in v4.0.22 but not in "4.0.25" and later version

**Comment by reinink** [comment]
Yeah, running into the same problem here. Adding this helps a bit:

```js
cssInterop(Svg, { className: 'style' })
```

But even then some classes like `fill-*` don't work.

**Comment by visualcookie** [comment]
For me it works with this part:
``` typescript
cssInterop(Svg, {
  className: {
    target: 'style',
    nativeStyleToProp: {
      width: true,
      height: true,
      fill: true,
    },
  },
});
```

But I now get a TypeScript error: `Object literal may only specify known properties, and 'fill' does not exist in type 'NativeStyleToProp<SvgProps | Readonly<SvgProps>>`

Seeing the types the function extends from, it only extends from `ViewStyle & TextStyle & ImageStyle`.

**Comment by resticker** [comment]
That's a great tip @visualcookie. Thank you. Any idea for a workaround to get `w-auto` working?

The following works fine on Web, but not iOs: `<Logo className="h-8 w-auto" viewBox="0 0 793 183" />`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
