### ISSUE TITLE
[v4] Tailwind config: `platformSelect` on color with alpha value breaks css variables on 2nd platform

### ISSUE THREAD

**Issue by mrzachnugent** [nativewind/nativewind#859]
**Describe the bug**
**Given** a tailwind config that uses `platformSelect` for a color with an alpha value,
```js
 background: platformSelect({
          android: 'rgb(var(--android-background) / <alpha-value>)',
          ios: 'rgb(var(--background) / <alpha-value>)',
        })
```
**When** you start the app on the second platform (iOS in the example above)
**Then** the css variables no longer work on iOS.

**To Reproduce**
1. Clone the following minimal reproduction repo: https://github.com/mrzachnugent/nw-platform-select-alpha-value
2. Install the dependencies and start the iOS app: `npm i && npm run ios`
3. The screen should be a red color with an opacity of 30%, instead it is the default screen color.

**Expected behavior**
The css variables work for the second platform as it does for the first platform. In the minimal repo, the iOS screen should be a red color with an opacity of 30%.

**To Reproduce working version for first platform (2 options)**
<ins>With Android</ins>
1. Run the android app: `npm run android`
2. When the app loads, you will see the screen will be a red color with an opacity of 30%

<ins>With iOS</ins>
1. Checkout the branch with iOS as first platform in platform select: `git checkout @zach/working-first-platform`
2. Run the android app: `npm run ios`
3. When the app loads, you will see the screen will be a red color with an opacity of 30%

**Screenshots**
Current behavior:
![Simulator Screenshot - iPhone 15 Pro - 2024-03-27 at 13 11 28](https://github.com/marklawlor/nativewind/assets/63797719/7d4cef9e-a19b-4495-b064-f5a8a9830bec)

Expected behavior:
![Simulator Screenshot - iPhone 15 Pro - 2024-03-27 at 13 11 45](https://github.com/marklawlor/nativewind/assets/63797719/e557bcc6-c298-423a-b2da-2274e877f2d2)

**Additional context**

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
