### ISSUE TITLE
[v4] Class name priority is incorrect

### ISSUE THREAD

**Issue by JinYuSha0** [nativewind/nativewind#861]
**Describe the bug**
Class name priority is incorrect

**To Reproduce**
```jsx
const Home: React.FC<Props> = () => {
  return (
    <Layout>
      <View className="w-10 h-10 bg-rose-300 bg-[#0000FF]" />
    </Layout>
  );
};
```

**Expected behavior**
The view should be blue because bg-[#0000FF] is sorted behind.

**Screenshots**
![image](https://github.com/marklawlor/nativewind/assets/20939091/43347280-9a6f-4521-aeaa-536832b3677f)

**Comment by JinYuSha0** [comment]
pr [#862 [](url)]

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
