### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by achtan** [nativewind/nativewind#867]
Hi, we want to rewrite our UI library but we are not sure if NativeWind is the right horse to bet on :)

It seems like @marklawlor is no longer contributing nor is anybody else...
<img width="920" alt="Screenshot 2024-04-04 at 12 48 36" src="https://github.com/marklawlor/nativewind/assets/1048212/1c09998d-2c8a-44b5-aa73-948f97f49285">

There is this issue "NativeWind v4 - Coming soon" https://github.com/marklawlor/nativewind/issues/600 opened on Nov 1 but the v4 is still not here, and no new commit was pushed for 3 months.

**Comment by galenom** [comment]
@achtan stumbled on your , I started using this library a few months ago. I couldn't find any better tools out there for react native tailwind support. 

Originally started using v2 but revisited v4 with the recent expo release. I was able to install on a fresh project and working wonderfully.  A few quirks but it's expected when supporting a new major version of a improtant dependency

@marklawlor with how useful this tool has been, I'd love for this to tool to keep going. I've cloned the repo and will see if i can get it running locally. I can't commit to any dedicated time but hoping I can debug some of the things I'm seeing at least. I'd be happy to connect to see how I can help the v4 release.

**Comment by alexandrius** [comment]
@achtan 
Sigh, posts like this benefit no one. The charts you've shared literally show somewhat recent enormous amount of changes. 

NativeWind 4 is ready and you can start using it in production. @marklawlor is simply waiting for feedback

**Comment by achtan** [comment]
I'm asking because we need to decide based on the answer. I didn't mean to troll or anything. 

We spent the last 5 months rewriting our spate management from Recail to Redux because Recoil seems to be dead https://github.com/facebookexperimental/Recoil/issues/2288 and we don't want to make the same mistake again.

I think my question is valid since this repo was not touched for months...

> NativeWind 4 is ready and you can start using it in production. @marklawlor is simply waiting for feedback
@alexandrius do you have some behind the sean information? or are you just guessing/hoping?

**Comment by dmitryshostak** [comment]
2 weeks ago I created a PR that has to be merged to fix an issue for Windows. https://github.com/marklawlor/nativewind/pull/860

@marklawlor not responding to it anyhow. So, it's hard to say if it's really still maintained.

**Comment by dmitryshostak** [comment]
2 weeks ago I created a PR that has to be merged to fix an issue for Windows. https://github.com/marklawlor/nativewind/pull/860

@marklawlor not responding to it anyhow. So, it's hard to say if it's really still active/maintained.

**Comment by GustavoBonfimS** [comment]
Looks like Mark has been working on the Expo Router, maybe he's a little busy.
Any chance of the Expo team embracing this project and helping by contributing? It would be interesting and would make this project more reliable without depending on a single person.

I rewrote my entire project from Styled Components to Nativewind, I think this discussion is valid since the repo issues grow and we don't have help to attract new contributors like contributing.md or something like that.

This library is impressive, I believe it will not die.

**Comment by oliverfunk** [comment]
Upvote my Canny feature request here

https://expo.canny.io/feature-requests/p/native-and-web-tailwind-support

**Comment by angelo-hub** [comment]
Can also help! trying to rely on this in production, and given the popularity pushing nativewind v4 through to the finish line will help the community immensely

**Comment by danstepanov** [comment]
This project is active
