### ISSUE TITLE
Allow theming without CSS Variables

### ISSUE THREAD

**Issue by useEffects** [nativewind/nativewind#870]
Using CSS Variables approach would limit us to abstract the color scheme in CSS files, this causes hardships in monorepo setups as exporting and importing css files are hard and sometimes would not work.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
