### ISSUE TITLE
react-native-css-interop is not installed when installing via PNPM

### ISSUE THREAD

**Issue by angelo-hub** [nativewind/nativewind#875]
**Describe the bug**
When installing v4 Xcode build fails unless `react-native-css-interop` is manually installed into the project.

**To Reproduce**
Install into a bare react-native project from scratch

Follow install steps.

Result is failure of metro-bundler on dev or release builds for 0.74+

**Expected behavior**
Should successfully install on the target iOS device

**Comment by danstepanov** [comment]
@angelo-hub Is this still an issue for you?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
