### ISSUE TITLE
zsh: no matches found: nativewind@^4.0.1 when running npm install nativewind@^4.0.1 react-native-reanimated tailwindcss 

### ISSUE THREAD

**Issue by FrenchFryInteractive** [nativewind/nativewind#876]
Hey, I am trying to install nativeWind, following the guide on https://www.nativewind.dev/v4/getting-started/expo-router
but i keep getting this error no matches found: nativewind@^4.0.1

What am I doing wrong here? Or is the version deprecated?

**Comment by thunderousNinja** [comment]
any update on this? seeing the same issue

**Comment by maianhvu** [comment]
Does adding quotes around "nativewind@^4.0.1" work? Like
```sh
npx expo install "nativewind@^4.0.1"
```

**Comment by FrenchFryInteractive** [comment]
npx expo install nativewind@4.0.27 tailwindcss react-native-reanimated this worked for me.

**Comment by danstepanov** [comment]
@FrenchFryInteractive Is this still an issue for you?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
