### ISSUE TITLE
Nativewind in Expo Snack - resolving dependency error

### ISSUE THREAD

**Issue by jleonard99** [nativewind/nativewind#879]
**Describe the bug**
A simple nativewind app written in expo snack editor "hangs" when loading the tailwindcss dependency.

**To Reproduce**
1. [Here is a working snack.](https://snack.expo.dev/@jleonard99/cmsc475-example-tailwind-and-nativewind)  *Note that the nativewind CSS works on the right-hand window*,
3. Note the red bar on the bottom - "add dependency" (see first screen shot below.)
4. When you add the dependency, *snack* hangs while trying to load *tailwindcss 3.0.0*.
5. When you refresh the screen, the app no longer works and an error is thrown. (See second screen shot below).
6. You can edit the *package.json*, removing the tailwindcss dependency.  The app starts to work, but the *Add dependency* bar warning is shown.

**Expected behavior**
I would expect that the *tailwindcss* dependency is loaded without errors so that I can continue to use nativewind for my snack.

**Expo Snack**
https://snack.expo.dev/@jleonard99/cmsc475-example-tailwind-and-nativewind

**Screen shots**
This shows the browser when the snack is first loaded.  Note that the nativewind rendering works, but there is a dependency 
that needs loading at the bottom.

<img width="1025" alt="nativewind-issue-1" src="https://github.com/marklawlor/nativewind/assets/1222364/93fc5c36-639b-477e-baa4-c95571618368">

When you add the dependency, snack hangs while trying to load tailwindcss 3.0.0.  When you *refresh* the screen you get this:

<img width="1025" alt="nativewind-issue-2" src="https://github.com/marklawlor/nativewind/assets/1222364/bc9c2bd8-3351-4a6c-a76b-964629ed6282">

Note that the nativewind rendering is no longer showing.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
