### ISSUE TITLE
Nativewind has no exported member: styled and StyledComponent 

### ISSUE THREAD

**Issue by amars29** [nativewind/nativewind#881]
I tried exporting styled component to make a component to enable classNames inside it. But it doesn;t have it. Actually the `styled` and `StyledComponent` were earlier present inside dist folder in version 2.0.11 but it is not in version 4.0.36

**Comment by AZReed** [comment]
![Screenshot 2024-04-29 at 12 53 49 AM](https://github.com/marklawlor/nativewind/assets/1939510/e245ab53-752f-48cf-80b6-49dc4292bf98)

Not sure if this is the same issue, @amars29 , but I think I'm having it too with nativewind v4

**Comment by daybreaker** [comment]
Running into this issue using react native bottom sheet, trying to get my custom colors to work for font and background colors in regular `Text` and `View` components inside a `BottomSheetView`. Someone said their solution was to wrap BottomSheetView in `styled` but v4 doesnt have this. I have tried using `cssInterop` without success so far.

**Comment by danstepanov** [comment]
@amars29 Is this still an issue for you?

**Comment by hawoooi** [comment]
gotta love it when the `styled` function is gone. this breaks like all of my code. what now?

**Comment by hawoooi** [comment]
update: there is a way to replace the `styled()` function:
```
import { cssInterop } from "nativewind";

// (as an example component
import { YourComponent } from "whatever-library-this-is-from";

const StyledYourComponent = cssInterop(YourComponent, {
  className: 'style'
});

// ...
// then, you can use it as normal:
<YourComponent className="text-white"></YourComponent>
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
