### ISSUE TITLE
Text-{anyColor}-{anyNumber} does not work on Native Text Component in PRODUCTION ONLY. - V.4.0.36",

### ISSUE THREAD

**Issue by AyoCodess** [nativewind/nativewind#883]
**Th solution is add the style tag** which i do not want to do.
Version:  "nativewind": "^4.0.36",

```
      <Text
            style={{
              color: moment.momentLabel === 'red' ? '#f87171' : '#60a5fa'
            }}
            className={cn('w-60 truncate font-ggRegular', {
              // 'text-red-400': moment.momentLabel === 'red',
              // 'text-blue-400': moment.momentLabel === 'blue'
            })}
            numberOfLines={1}>
            {moment.topics}
          </Text>
```

**Comment by Darren120** [comment]
update?

**Comment by danstepanov** [comment]
@AyoCodess Is this still an issue for you?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
