### ISSUE TITLE
Documentation update

### ISSUE THREAD

**Issue by 1ChristianAlex** [nativewind/nativewind#884]
**Describe the bug**
Since the page [Retrieving theme values](https://www.nativewind.dev/guides/theme-values) is showing how to use imports from "tailwindcss/colors" depedencie, i do recommend this dependencie to be add as a non-dev dependency, as showing on expo's guide page [Expo](https://www.nativewind.dev/quick-starts/expo)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
