### ISSUE TITLE
[v4] Expo V3 Router and Nativewind. Styles are not loading.

### ISSUE THREAD

**Issue by Viraj-10** [nativewind/nativewind#886]
**Describe the bug**
Initial load of application in Expo router is not loading styles.
but once you hot reload it after just saving `tailwind.config.js` without any changes.
it loads all the styling.

**To Reproduce**
1. clone this github repo [link](https://github.com/Viraj-10/router-nativewind-expo).
2. run it on ios. (you will see styles are not loaded)
3. save `tailwind.config.js` and refresh the app it will load all the styles.

**Expected behavior**
It should have load style on initial load of the application.

**Video**

https://github.com/marklawlor/nativewind/assets/66306233/73e6f5b2-3838-4309-a7b2-7abd86c82d36

**Comment by ArifKobel** [comment]
I am having the same Problem.

**Comment by hukpo** [comment]
You should always install the latest nativewind version before opening a new issue.

**Comment by BAMFuuuCrab** [comment]
hi guys,i found the same problem in my project, it happend that i transform to src directory.
I tried to roll back the directory structure to before using/src, and the problem was resolved, and it only occurs in iOS.
like this:
<img width="359" alt="image" src="https://github.com/marklawlor/nativewind/assets/58927506/589a8a3e-3481-485c-ba37-50ab01a7d230">

@Viraj-10 @ArifKobel

**Comment by welsh11** [comment]
Same issue here, I don't really want to change my project layout so it would be good to know if there is a solution

**Comment by thienautran** [comment]
I fixed this by running:
npx expo start -c
Or
expo start -c

I put this command in my package json as the default start script

The -c / --clear flag  clears the expo cache when starting the dev server , not sure if there's a better workaround but this worked for me

**Comment by erkamdemirci** [comment]
> I fixed this by running: npx expo start -c Or expo start -c
> 
> I put this command in my package json as the default start script
> 
> The -c / --clear flag clears the expo cache when starting the dev server , not sure if there's a better workaround but this worked for me

tried this first but didnt work for me...

**Comment by erkamdemirci** [comment]
> hi guys,i found the same problem in my project, it happend that i transform to src directory. I tried to roll back the directory structure to before using/src, and the problem was resolved, and it only occurs in iOS. like this: <img alt="image" width="359" src="https://private-user-images.githubusercontent.com/58927506/324740637-589a8a3e-3481-485c-ba37-50ab01a7d230.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4NzQ0MTAsIm5iZiI6MTcxMzg3NDExMCwicGF0aCI6Ii81ODkyNzUwNi8zMjQ3NDA2MzctNTg5YThhM2UtMzQ4MS00ODVjLWJhMzctNTBhYjAxYTdkMjMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDEyMDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwYWNjNGY3MzAzZDU5YmU0NWI0NTFmN2Q3ZDhkN2JmZWQ5Y2RmZjJiZTcyYzVmZjQ4ZTRmMTIzN2M0MWU0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TTb9lTpnCws0VGlMghLTYEYzHpCTGbRyVUQV0fIZRSc">
> 
> @Viraj-10 @ArifKobel

I was thinking it might be related to /src but I haven't tried for days (don't know why). You encouraged me and it worked! thanks :)

**Comment by rlesniak** [comment]
Same here. I need to make change in any component, save, and then press `r` in terminal to reload expo's JS .
In addition, the build version (production) lacks the same styles as the developer version.

**Comment by erkamdemirci** [comment]
Tried @BAMFuuuCrab 's solution and it worked for me!  (using expo-router btw)

Also some recommendations;
- Use v4.0.1 (they also recommend this) https://www.nativewind.dev/v4/getting-started/expo-router
`"nativewind": "4.0.1", "tailwindcss": "^3.4.3"`
- Be careful with **metro.config.js** path for global.css;
`module.exports = withNativeWind(config, { input: './global.css' });`
- Double check **tailwind.config.js** content and presets;
`content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}']`
`presets: [require('nativewind/preset')],`
- Also here is my **babel.config.js** presets and plugins;
`presets: [['babel-preset-expo', { jsxImportSource: 'nativewind' }], 'nativewind/babel']`
`plugins: ['react-native-reanimated/plugin']`

**Comment by BAMFuuuCrab** [comment]
Afterwards, I tried some other methods and found another solution that works with the src directory (it worked for me).

Make sure your tailwind.config.js settings are correct, ensuring the content configuration is accurate. You can try using my configuration.
```
const { hairlineWidth } = require('nativewind/theme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {} // your config
}
```
Ensure global.css is correctly imported at the root.

![image](https://github.com/marklawlor/nativewind/assets/58927506/7a3f89c4-a240-4067-83a5-f6514dbe291f)

In metro.config.js, also make sure the path to global.css is correctly configured.

![image](https://github.com/marklawlor/nativewind/assets/58927506/539b2845-5e19-4f10-95e5-c5772819cdbe)

After confirming there are no mistakes in the above, slightly change the way you start the project.

Since this issue only occurs for me on the iOS platform, first use
```
npx expo run:ios
```
 If you don't have an iOS folder, Expo will first perform a prebuild, then build and install onto the iOS device. After this step, you can stop the development server with Control + C.

Start the development server with
```
npx expo start --clear
``` 
The Expo documentation explains the --clear parameter as follows: Restart the development server and clear the JavaScript transformation caches.

so, that it, i hope the above can be helpful to you guys
if this method works, I suggest configuring it in package.json.

```
{
  "scripts": {
    "start": "expo start --clear",
  },
}
```

@welsh11

**Comment by danharten-sovtech** [comment]
I needed to clear my expo cache once. All subsequent tries worked fine.

I presume some config is cached on expo init, and it's not aware of nativewind after installing, until reset 🤷 

Not entirely sure though. Would be cool to hear from maintainers on this one

**Comment by liydaco** [comment]
Still an issue for me

**Comment by n8udd** [comment]
> * `content: ['./app/**/*.{js,jsx,ts,tsx}', './components/**/*.{js,jsx,ts,tsx}']`
>       `presets: [require('nativewind/preset')],`

This was the issue for me. 
I wasn't including the components dir which now sits outside of /app

**Comment by danstepanov** [comment]
@Viraj-10 Is this still an issue for you?

**Comment by Viraj-10** [comment]
Hey @danharten-sovtech, Not sure what's the issue but I just checked and it's working fine now. I will close the issue.

**Comment by periakteon** [comment]
> Afterwards, I tried some other methods and found another solution that works with the src directory (it worked for me).
> 
> Make sure your tailwind.config.js settings are correct, ensuring the content configuration is accurate. You can try using my configuration.
> 
> ```
> const { hairlineWidth } = require('nativewind/theme');
> 
> /** @type {import('tailwindcss').Config} */
> module.exports = {
>   content: ["./src/**/*.{js,jsx,ts,tsx}"],
>   presets: [require("nativewind/preset")],
>   theme: {} // your config
> }
> ```
> 
> Ensure global.css is correctly imported at the root.
> 
> ![image](https://private-user-images.githubusercontent.com/58927506/325086666-7a3f89c4-a240-4067-83a5-f6514dbe291f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODk2NTQsIm5iZiI6MTcyMzI4OTM1NCwicGF0aCI6Ii81ODkyNzUwNi8zMjUwODY2NjYtN2EzZjg5YzQtYTI0MC00MDY3LTgzYTUtZjY1MTRkYmUyOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDExMjkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMjY1MGExNDc2N2RjODE1YTA4MzlkM2JmYWE5ZDhmNjY0OTliMDE4ZjY3YzNjNGMzOGE5OTRlM2RmYWMyY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FL8neFj0Mi935rpQ4AWcEllEfWMgXagedN6xz7XnmEs)
> 
> In metro.config.js, also make sure the path to global.css is correctly configured.
> 
> ![image](https://private-user-images.githubusercontent.com/58927506/325086786-539b2845-5e19-4f10-95e5-c5772819cdbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyODk2NTQsIm5iZiI6MTcyMzI4OTM1NCwicGF0aCI6Ii81ODkyNzUwNi8zMjUwODY3ODYtNTM5YjI4NDUtNWUxOS00ZjEwLTk1ZTUtYzU3NzI4MTljZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEwVDExMjkxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhZjAwMjc4ZjdjNmYyYjlkYTg2ZDc4NmJkMWE2MzVhNDE2NGQ1NzE3ZDU5MDE0ZWY2MjFmZjVjYzgzMzk2YjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.48sQxC04CICL3IN2Es7Zwl7apypcqEtgeAX1GNjmJMY)
> 
> After confirming there are no mistakes in the above, slightly change the way you start the project.
> 
> Since this issue only occurs for me on the iOS platform, first use
> 
> ```
> npx expo run:ios
> ```
> 
> If you don't have an iOS folder, Expo will first perform a prebuild, then build and install onto the iOS device. After this step, you can stop the development server with Control + C.
> 
> Start the development server with
> 
> ```
> npx expo start --clear
> ```
> 
> The Expo documentation explains the --clear parameter as follows: Restart the development server and clear the JavaScript transformation caches.
> 
> so, that it, i hope the above can be helpful to you guys if this method works, I suggest configuring it in package.json.
> 
> ```
> {
>   "scripts": {
>     "start": "expo start --clear",
>   },
> }
> ```
> 
> @welsh11

worked for me, thanks!

**Comment by MounsefSAHOUL** [comment]
Hi,
Maybe try this tools for your future App : [https://rn.new/]

**Comment by Seanmclem** [comment]
upgrading to 4.1 caused this issue for me. rolling back to 4.0.36 fixes it, but breaks eas builds

**Comment by kisszoltan** [comment]
> upgrading to 4.1 caused this issue for me. rolling back to 4.0.36 fixes it, but breaks eas builds
> 
> EDIT: Fixed after removing `react-native-css-interop` dependency, and an associated patch-file, and doing a fresh install and `npx expo start --clear`.. Per [#1169 (comment)](https://github.com/nativewind/nativewind/issues/1169#issuecomment-2474883287)

+1 this. In my case downgrading `"nativewind": "^4.1.23"` to `"nativewind": "4.0.36"` and `"tailwindcss": "^3.4.15"` to `"tailwindcss": "3.4.1"` solved the issue. (I am not sure about the need of the later, but the component library which I use used these two versions.)

**Comment by akemihiga** [comment]
I fixed it by removing this dependency: **react-native-css-interop**.
and adding this to my .npmrc file: **node-linker=hoisted**


I'm using "nativewind": "^4.1.23" and "tailwindcss": "^3.4.15"

**Comment by Topiya** [comment]
Styles are not applying in bare react-native project. I am also using "nativewind": "^4.1.23" and "tailwindcss": "^3.4.15".

Can anyone please help me to solve this issue?

**Comment by delphinebugner** [comment]
I my case (monorepo PNPM with Next apps aside), going back to `node-linker=hoisted` was not an option. Also using NativeWind 4.1. 

Simply adding explicit declaration `"react-native-css-interop": "*"` in my mobile package.json did the trick though!

**Comment by jkuhs** [comment]
Ran into the same issue. Downgrading from `"nativewind": "^4.1.23"` to `"nativewind": "4.0.36"` fixed it. Definitely feels like a bug...

**Comment by cwoolum** [comment]
For me, with `nativewind@^4.2.1`, removing `react-native-css-interop` fixed my problems.
