### ISSUE TITLE
v4 cssInterop does not work with custom native component

### ISSUE THREAD

**Issue by ospfranco** [nativewind/nativewind#891]
**Describe the bug**
I'm trying to apply native wind styles to a native component, the component is very bare-bones:

```swift

@objc(BlurViewManager)
class BlurViewManager: RCTViewManager {
  override static func requiresMainQueueSetup() -> Bool {
    return true
  }

  override func view() -> NSView! {
    return BlurView()
  }
}

```

When I try to import it and apply `cssInterop` to it:

```jsx
import {requireNativeComponent, ViewStyle} from 'react-native'

import {cssInterop} from 'nativewind'

export const BlurView = requireNativeComponent<{
  children?: any
  onLayout?: (e: any) => void
  startColor?: string
  endColor?: string
  style?: ViewStyle
  cornerRadius?: number
  disabled?: boolean
  className?: string
}>('BlurView')

// export const BlurView = (...props: any) => <BlurViewNative {...props} />

cssInterop(BlurView, {
  className: 'style',
})
```

However on runtime I get the following error:

![Oscar Franco Screen 001343](https://github.com/marklawlor/nativewind/assets/1634213/69ebae4e-0b54-468c-a6e2-578b40422c83)

**Comment by ospfranco** [comment]
I managed to get this working, seems the `cssInterop` call is passing an array of props and not and object, therefore the destructuring is actually not working:

```tsx
import {requireNativeComponent, ViewStyle} from 'react-native'

import {cssInterop} from 'nativewind'

export const BlurViewNative = requireNativeComponent<{
  children?: any
  onLayout?: (e: any) => void
  startColor?: string
  endColor?: string
  style?: ViewStyle
  cornerRadius?: number
  disabled?: boolean
  className?: string
}>('BlurView')

export const BlurView = (props: any) => {
  return <BlurViewNative {...props} />
}

cssInterop(BlurView, {
  className: 'style',
})
```

Is this a bug? I'm not sure, maybe at least it needs to be documented properly

**Comment by danstepanov** [comment]
@ospfranco Is this still an issue for you?

**Comment by ospfranco** [comment]
Yeah, the last comment showed how i worked around it

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
