### ISSUE TITLE
V4: Not able to get text-color to work

### ISSUE THREAD

**Issue by austinm911** [nativewind/nativewind#892]
**Describe the bug**
I'm new to RN and expo. I init a new tabs template and added v4 Nativewind, but can't get text-color to work (see index.ts).

If i replace app with __app in the src folder, it works fine it seems (this is the example from the expo repo).

I'm not sure if there's a bunch of boilerplate code that comes with the tabs template that breaks certain tailwind classes with v4.

Reproduction 
https://github.com/austinm911/nativewindv4

**Comment by GustavoBonfimS** [comment]
I did this and it worked:

Install `nativewind@canary`
remove __app folder
in `src/app/_layout.tsx` replace import from css, from `import "@/global.css"` to `import '../global.css';`

**Comment by danstepanov** [comment]
@austinm911 Is this still an issue for you?

**Comment by decidev22** [comment]
I have similar issue, I can get text-[size] to work, but not text-[color] why is that? whenever I add text-[color] it just resets the size of the text as well.

**Comment by ashkanyadegari** [comment]
Make sure to import <Text> from react-native, you can apply text-color on those.

**Comment by phrl42** [comment]
can confirm the same issue

**Comment by CamTheWebGuy** [comment]
Same issue.

**Comment by beng970804** [comment]
Same issue

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by ali-farhad** [comment]
> Make sure to import from react-native, you can apply text-color on those.

this was the issue. boilerplate code from expo tabs was actually importing TEXT from `themedcomponents` and hence certain tailwind styles could not be applied to it due to specificity ig.

**Comment by magalenyo** [comment]
Still happening, "text-red" will not work but "text-red-600" will

**Comment by danstepanov** [comment]
> Still happening, "text-red" will not work but "text-red-600" will

`text-red` is not a valid Tailwind utility class
