### ISSUE TITLE
Shadow prop error in android

### ISSUE THREAD

**Issue by benomzn** [nativewind/nativewind#893]
Hi, I made a custom component, that receives the "className?: string" prop. This is the component:

```ts
import { cn } from "@/core/utils";
import { ActivityIndicator, Pressable, PressableProps } from "react-native";

interface ButtonPros {
  onPress: () => void,
  className?: string,
  children?: React.ReactNode,
  isLoading?: boolean
}

const Button = ({ onPress, className, children, isLoading = false, ...rest }: ButtonPros & PressableProps): JSX.Element => {
  return (
    <>
      <Pressable
        onPress={onPress}
        disabled={isLoading}
        className={cn("outline-none items-center justify-center shadow shadow-black rounded-full bg-slate-600 px-5 py-2 active:scale-95 active:opacity-80 transition-all", className)}
        {...rest}>
        {isLoading ? <ActivityIndicator size={15}/> : children}
      </Pressable>
    </>
  );
}
export default Button;
```

But in Android, I receive this error:

![image](https://github.com/marklawlor/nativewind/assets/87614390/9b872013-41b6-48cb-be1e-797c21dec3b3)

This only happens in the android emulator, it works fine on iOS. When I deleted "shadow shadow-black" from className prop in Pressable component, I stopped getting errors. Even if I get the warning, the shadow still works on ios and android, but I'm curious why I'm getting this message in the console.

Versions:
**"expo": "~50.0.14",
"nativewind": "^4.0.1",
"tailwindcss": "^3.4.3"**

**Comment by Malberee** [comment]
Hi. How did you solve this problem?

**Comment by benomzn** [comment]
> Hi. How did you solve this problem?

I didn't fix it, because the shadows were applied correctly, but I still get the error message on Android

**Comment by benomzn** [comment]
@Malberee I found that the problem is the "transition-all" property. This property is in experimental support, so I think is normal this errors.

**Comment by benomzn** [comment]
@Malberee  I found that the problem is the "transition-all" property. This property is in experimental support, so I think is normal this errors.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
