### ISSUE TITLE
[V4] Unable to resolve "react-native-css-interop"

### ISSUE THREAD

**Issue by DaveVaval** [nativewind/nativewind#894]
**Describe the bug**
When updating to the latest version, or anything passed  >4.0.13, I get this issue. After looking at passed issues it seemed like people were experiencing the same thing with pnpm, but in my case I am using NPM.

![image](https://github.com/marklawlor/nativewind/assets/62922293/cb024280-5186-4d29-8f62-e31771f49787)

**To Reproduce**
1. Expo 49.0.93
2. React Navigation 6
3. Tailwindcss 3.3.2
4. Using NPM

**Additional context**
My bable config:
![image](https://github.com/marklawlor/nativewind/assets/62922293/6319b011-6da8-4e67-a34b-7b2f2863b9ff)

and within my metro config I am requiring withNativeWind :
`const { withNativeWind } = require('nativewind/metro');`

and returning my config like so:
`return withNativeWind(config, { input: './global.css' });`

**Comment by bradleybernard** [comment]
Also getting the same with, with same looking babel config, but with Expo SDK 51 beta. Only seemed to hit me when I upgraded to SDK 51 beta... hm

**Comment by DaveVaval** [comment]
@bradleybernard in your case did it work using expo 50?

**Comment by bradleybernard** [comment]
Yep only with 51, I went back down to 50 and it works for some reason. No configs changed, just version changes in package file and lock file

**Comment by alxlion** [comment]
Forcing to 4.0.1 solved the issue

**Comment by DaveVaval** [comment]
> Forcing to 4.0.1 solved the issue

Yeah the problem is I can't use the latest version, alot of classes don't work in 4.0.1. It's a bummer but I'll have to put nativewind in standby and stick with stylesheets until a stable release

**Comment by GustavoBonfimS** [comment]
I'm using Expo 51 and nativewind@canary (4.0.36) and it's working. The canary release fixed several issues since 4.0.1. See if it works for you.

**Comment by danstepanov** [comment]
@DaveVaval Is this still an issue for you?

**Comment by r0bdiabl0** [comment]
I'm not sure if this is related but I just upgraded to Expo SDK 51 (51.0.9) and I'm getting this error after running `pnpm run dev:ios`. I wasn't getting this error prior to upgrading and updating the project:

```
tailwindcss(ios) rebuilding... /Users/adsfadsf/src/swplatform/node_modules/react-native-css-interop/dist/css-to-rn/index.js:24
    (0, lightningcss_1.transform)({
                                 ^

SyntaxError: Unexpected token Delim('*')
    at cssToReactNativeRuntime (/Users/adsfadsf/src/swplatform/node_modules/react-native-css-interop/src/css-to-rn/index.ts:76:15)

....

fileName: 'style.css',
  source: '@cssInterop set darkMode media;\n' +
    '\n' +
    '@cssInterop set nativewind;\n' +
    
....
```

Package versions:

Nativewind: 4.0.36
Tailwindcss: 3.4.3
React Native: 0.74.1

**Comment by DaveVaval** [comment]
> @DaveVaval Is this still an issue for you?

Yes still an issue for me, I put away nativewind for now and built my app with stylesheet, I'll wait for a stable v4 release!

**Comment by onurhan1337** [comment]
It's still the same issue. any advice?
![image](https://github.com/user-attachments/assets/ace04cd6-ce25-41de-8aee-77e36220e94a)

**Comment by sanny-io** [comment]
I am also getting this error. I get it even when using `4.0.13`

![IMG_FBD4A9C34662-1](https://github.com/user-attachments/assets/fe51360d-cb09-40fc-a1b3-7ce8dba53346)

```json
"expo": "51.0.31",
"nativewind": "4.0.36",
"react": "18.2.0",
"react-native": "0.74.5",
"tailwind-merge": "2.4.0",
"tailwindcss": "3.4.10"
```

**Comment by dmvvilela** [comment]
For me changing from pnpm to yarn worked.

**Comment by DaveVaval** [comment]
I tested v 4.1.1 with the latest expo version and I haven't had any issues

**Comment by sanny-io** [comment]
@danstepanov do you know what commit was supposed to resolve this? I am still getting this error with `4.1.4`

**Comment by harrisrobin** [comment]
also experiencing this :/

**Comment by billnye2** [comment]
@sanny-io I was able to move pass this error by directly running `npx expo install react-native-css-interop@next`. I believe that without this, `react-native-css-interop` is actually at `node_modules/nativewind/node_modules/react-native-css-interop` and somehow it causes this error? Not sure, but installing it directly adds it at `node_modules/react-native-css-interop`

**Comment by mauricior** [comment]
> @sanny-io I was able to move pass this error by directly running `npx expo install react-native-css-interop@next`. I believe that without this, `react-native-css-interop` is actually at `node_modules/nativewind/node_modules/react-native-css-interop` and somehow it causes this error? Not sure, but installing it directly adds it at `node_modules/react-native-css-interop`

this worked for me, thanks!

**Comment by yorvinlunawisky** [comment]
> @sanny-io I was able to move pass this error by directly running `npx expo install react-native-css-interop@next`. I believe that without this, `react-native-css-interop` is actually at `node_modules/nativewind/node_modules/react-native-css-interop` and somehow it causes this error? Not sure, but installing it directly adds it at `node_modules/react-native-css-interop`

Thank you very much!

**Comment by sanny-io** [comment]
> @sanny-io I was able to move pass this error by directly running `npx expo install react-native-css-interop@next`. I believe that without this, `react-native-css-interop` is actually at `node_modules/nativewind/node_modules/react-native-css-interop` and somehow it causes this error? Not sure, but installing it directly adds it at `node_modules/react-native-css-interop`

@billnye2 this fixed it for me. Good lookin out brother, I appreciate you 👍

**Comment by ospfranco** [comment]
I just tried installing native wind 4.1.21 and getting this error on a vanilla RN project. Any workaround or solution?

**Comment by aman08singh** [comment]
Just for testing purposes:
Uninstall the react-native-reanimated library.
Build the project.

**Comment by Aurelienbr96** [comment]
> I just tried installing native wind 4.1.21 and getting this error on a vanilla RN project. Any workaround or solution?

Got the same issue

**Comment by sanny-io** [comment]
@lbxa yes, it may not have necessarily been the install command. I believe I just went off of what he said regarding the location in `node_modules`, and I am using `node-linker=hoisted`

**Comment by Ricky-83** [comment]
> @sanny-io I was able to move pass this error by directly running `npx expo install react-native-css-interop@next`. I believe that without this, `react-native-css-interop` is actually at `node_modules/nativewind/node_modules/react-native-css-interop` and somehow it causes this error? Not sure, but installing it directly adds it at `node_modules/react-native-css-interop`

this worked for me, thanks!

**Comment by Niranjan-A-S** [comment]
I was using pnpm and faced this issue while configuring nativewind.
Tried switching back to yarn and now it's sorted 😎

**Comment by rishil-sh** [comment]
Any fix for the pnpm package manager?
I have a workspace with pnpm and it would be great if this issue can be fixed?

**Comment by danstepanov** [comment]
Hey y'all, until someone provides a minimal repro of this, I'm not gonna be able to look into it

**Comment by stilyng94** [comment]
> expo install react-native-css-interop@next

Works excellently
