### ISSUE TITLE
Project is on pause?

### ISSUE THREAD

**Issue by nuno** [nativewind/nativewind#895]
Just want to ask if the project is still active?
 I love working with this tool!
 The idea is to know if I can continue developing applications and not be surprised later. 

Excellent work btw!

**Comment by feledori** [comment]
The author of this library works for expo and I think they are currently hard at work for SDK 51. Probably just busy as this is not his main job.

**Comment by GustavoBonfimS** [comment]
I'm using Expo 51 and nativewind@canary (4.0.36) and it's working. The canary release fixed several issues since 4.0.1. See if it works for you.

**Comment by achtan** [comment]
duplicate https://github.com/marklawlor/nativewind/issues/867
