### ISSUE TITLE
Some utilities classes of tailwind not works in NativeWind V4

### ISSUE THREAD

**Issue by hamidradical** [nativewind/nativewind#898]
I am using latest version of expo with expo-router and due to expo router i had to installed nativewind for support of expo router.

And i also use react native paper. here below tailwind css not works.

`import { Card, TextInput, Button } from 'react-native-paper';

<Button
            // style={{ borderRadius: 4 }}
            className='bg-emerald-900 text-green-400 rounded-none'
            icon="login"
            mode="contained"
            onPress={() => router.push('/summary')}>
            LOGIN
          </Button>`
          
 this className='bg-emerald-900 text-green-400 rounded-none' style works on nativewind v2.0.x. 
 
 And your work for nativewind v4 is so great.

**Comment by verifund-admin** [comment]
I'm having the same issue. Can you check what your output file looks like at `./node_modules/.cache/nativewind/global.css`? I'm only seeing a handful of utility classes being defined. For example, I only have `py-3` utility class defined, therefore that's the only style that works when running locally.

When I deploy to prod, it seems to be working fine though.

**Comment by Darren120** [comment]
related? https://github.com/marklawlor/nativewind/issues/883

**Comment by danstepanov** [comment]
@hamidradical Is this still an issue for you?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
