### ISSUE TITLE
setColorScheme (Dark Mode) is broken

### ISSUE THREAD

**Issue by enchorb** [nativewind/nativewind#913]
Further described in this issue: https://github.com/marklawlor/nativewind/issues/866

Once either `dark` or `light` is set then further system settings changes what trigger an update

Setting `system` also doesn't work (if you toggle dark mode in device settings the app ui doesn't update).

Even if dark/light is set in `setColorScheme`, system (device) changes should still trigger.

**Comment by tarifalhasan** [comment]
I'm facing the same issue. did you fixed

**Comment by desiboli** [comment]
I was having problem with the dark mode functionality in my app as well and I found out that I by accident changed the .dark selector in global.css from `.dark:root` to `.dark`. Hopefully this can help someone else!

**Comment by danstepanov** [comment]
Closed as duplicate of #917

**Comment by enchorb** [comment]
@danstepanov condering both tickets are closed should a new ticket be opened to have Nativeiwnd work with the latest Tailwind release?

**Comment by danstepanov** [comment]
@enchorb That would be a separate concern, yes.
