### ISSUE TITLE
[v4] Eas Update Showing exporting...

### ISSUE THREAD

**Issue by 50UM3N** [nativewind/nativewind#915]
I created an expo app with expo router and NativeWind 4 I followed all the steps correctly, but when I do `eas update` it stuck at exporting.

Here is the terminal screenshot 
![image](https://github.com/marklawlor/nativewind/assets/30142639/3f271fab-ddb0-444e-98a2-95defc5772cb)

I am also providing the configs.

metro.config.js
```ts
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require("expo/metro-config");
const { withNativeWind } = require('nativewind/metro');

const config = getDefaultConfig(__dirname)

module.exports = withNativeWind(config, { input: './global.css' })
```
tailwind.config.js
```ts
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

babel.config.js
```ts
module.exports = function (api) {
	api.cache(true);
	return {
		presets: [
			["babel-preset-expo", { jsxImportSource: "nativewind" }],
			"nativewind/babel",
		],
	};
};
```
package.json
```json
{
    "expo": "~51.0.5",
    "expo-constants": "~16.0.1",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.12",
    "expo-status-bar": "~1.12.1",
    "expo-updates": "~0.25.11",
    "nativewind": "4.0.1",
    "react": "18.2.0",
    "react-native": "0.74.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.1",
    "react-native-screens": "3.31.1",
    "tailwindcss": "^3.4.3"
}
```

**Comment by SakuZN** [comment]
Make sure your project path structure does not contain any space.

**Comment by 50UM3N** [comment]
> Make sure your project path structure does not contain any space.

No, the path name is just `app`

**Comment by SakuZN** [comment]
This takes into account your entire project path, so if your full path is structured like "C:\Program Files\Projects\app" it will cause that error. Some of the PR has some solution to this problem but my fix for that error was making sure the entire project path does not contain any space.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
