### ISSUE TITLE
Dark mode modifier 

### ISSUE THREAD

**Issue by younes200** [nativewind/nativewind#917]
**Describe the bug**
`dark:` modifier broken on the last version for native apps : 

works fine with` ios:` `android:` : <View className="h-20 w-20 bg-primary ios:bg-destructive"/>
**To Reproduce**

1. Start project
2. Run :
```
import * as React from 'react';
import { View } from 'react-native';

export default function Screen() {

  return (
    <View className='flex-1'>
      <View className="h-20 w-20 bg-primary dark:bg-destructive"/>
    </View>
  );
}

```

**Expected behavior**

**Screenshots**

<img width="1599" alt="Screenshot 2024-05-13 at 20 17 52" src="https://github.com/marklawlor/nativewind/assets/198514/79f81eee-811d-40ef-8516-b47f2b7852f7">

**Platform (please complete the following information):**
 - Type: Browser, Simulator, Emulator, Device
 - OS: iOS, Android

**Additional context**
- Expo : ~50.0.17
- nativewind 4.0.36

**Comment by GustavoBonfimS** [comment]
Could you please try the canary version (4.0.36)? Several improvements have been made and maybe this issue has been fixed.

**Comment by alisherks** [comment]
What version of Tailwind are you using? Try version 3.4.1; version 3.4.2 introduced some changes to how dark mode styles are generated. I believe it is not handled by NativeWind right now.

**Comment by desiboli** [comment]
I was having problem with the dark mode functionality in my app as well and I found out that I by accident changed the .dark selector in global.css from `.dark:root` to `.dark`. Hopefully this can help someone else!
