### ISSUE TITLE
Rotate utility is not working as expected on Android platform

### ISSUE THREAD

**Issue by moritzlang** [nativewind/nativewind#918]
**Describe the bug**
When using `className="transform rotate-90"` I get an error
`Transform with key of "rotate" must be a string: {"rotate":0}`.

The rotate utility only works when using an arbitrary value like this:
`className="transform rotate-[90deg]"`

This only happens on the android platform for me.

**Expected behavior**
`rotate-90` can be used as well.

**Expo Snack**
I did not find a example snack for v4, therefore did not create one.

**Screenshots**
![Screenshot_1715687433](https://github.com/marklawlor/nativewind/assets/19893634/71dd2dd2-26e5-45cb-86f5-1e7a333ee6e5)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by makivlach** [comment]
This is still an issue.
