### ISSUE TITLE
Nativewind 4 and Material Top Tabs - Tab alignment issues

### ISSUE THREAD

**Issue by bhyoo99** [nativewind/nativewind#921]
### Discussed in https://github.com/marklawlor/nativewind/discussions/852

<div type='discussions-op-text'>

<sup>Originally posted by **foureight84** March 16, 2024</sup>
I just added Nativewind 4.0.36 to my Expo 50 project that's currently using Material Top Tabs and I am seeing that the tabs alignment are off. Not sure how to fix this issue.

 

https://github.com/marklawlor/nativewind/assets/1146028/17c96b8a-1d93-40f7-9af1-01cc46061e2c

</div>

## TEMP soloution

add
`tabBarContentContainerStyle: {
          flex: 1,
          flexDirection: 'row',
          justifyContent: 'space-around',
        },`

but still pressable area looks like this

<img width="487" alt="image" src="https://github.com/marklawlor/nativewind/assets/62757768/40a564bc-7078-4668-bea8-c3468def4dd4">

here is reproducible demo repo
https://github.com/bhyoo99/nativewind-material-top-tabs

**Comment by kwangjaeyoo** [comment]
Thanks you!

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
