### ISSUE TITLE
v4: custom font not working with TW classes, but does work with inline styles

### ISSUE THREAD

**Issue by tconroy** [nativewind/nativewind#923]
**Describe the bug**
A custom font (loaded using expo-fonts) is visible when using inline `style={{ fontfamily: 'Custom Font' }}` prop, but is not visible when using TW class name `className="font-customFont"`

other tailwind classes work as expected.

**To Reproduce**
**tailwind.config.js**
```ts
import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      fontFamily: {
        lexend: ["Lexend Deca"]
      },
    },
  },
} satisfies Config;
```

**FontsProvider**
```tsx
import {
  LexendDeca_100Thin,
  LexendDeca_200ExtraLight,
  LexendDeca_300Light,
  LexendDeca_400Regular,
  LexendDeca_500Medium,
  LexendDeca_600SemiBold,
  LexendDeca_700Bold,
  LexendDeca_800ExtraBold,
  LexendDeca_900Black,
  useFonts,
} from "@expo-google-fonts/lexend-deca";

interface Props {
  children?: React.ReactNode;
}

export default function FontProvider(props: Props) {
  const [fontsLoaded, error] = useFonts({
    LexendDeca_100Thin,
    LexendDeca_200ExtraLight,
    LexendDeca_300Light,
    LexendDeca_400Regular,
    LexendDeca_500Medium,
    LexendDeca_600SemiBold,
    LexendDeca_700Bold,
    LexendDeca_800ExtraBold,
    LexendDeca_900Black,
  });

  if (!fontsLoaded) {
    return null;
  }

  return <>{props.children}</>;
}
```

**RootLayout**
```tsx
import "../styles.css";

export default function RootLayout() {
  return (
    <FontProvider>
      <App />
    </FontProvider>
  );
}
```

** ✅ this works:**
```tsx
        <Text
          style={
            {
              fontFamily: "Lexend Deca",
            }
          }
        >
          test
        </Text>
```

**❌ this does not work**
```ts
        <Text
          className="font-lexend"
        >
          test
        </Text>
```

**Expected behavior**
Expect to see the same font as inline font.

**Comment by angelo-hub** [comment]
+1 also have this issue

**Comment by tyrauber** [comment]
Hey @tconroy, I believe you need to define each font-family weight individually in your tailwind config.

```
    extend: {
      fontFamily: {
        "lexend-thin": ["LexendDeca_100Thin"],
        "lexend-extrathin": ["LexendDeca_200ExtraLight"]
      },
    },
```
Technically they are different font files.

**Comment by AyoCodess** [comment]
> weight

This is the bitter truth i had to accept too.

**Comment by AyoCodess** [comment]
> Hey @tconroy, I believe you need to define each font-family weight individually in your tailwind config.
> 
> 
> 
> ```
> 
>     extend: {
> 
>       fontFamily: {
> 
>         "lexend-thin": ["LexendDeca_100Thin"],
> 
>         "lexend-extrathin": ["LexendDeca_200ExtraLight"]
> 
>       },
> 
>     },
> 
> ```
> 
> Technically they are different font files.

This is the bitter truth i had to accept too.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
