### ISSUE TITLE
Monospace font doesn't work on Android

### ISSUE THREAD

**Issue by mateossh** [nativewind/nativewind#925]
**Describe the bug**
When I try to use default monospace font with `font-mono` on Android it throws warning that font doesn't exist.

**To Reproduce**
1. Add className `font-mono` to Text element
2. See warning that "mono" is not a system font.

[Link to repo with reproduced bug](https://github.com/mateossh/nativewind-android-monofont)

**Expected behavior**
Monospace text to render correctly.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
