### ISSUE TITLE
Work With Tailwind 3.4.2+

### ISSUE THREAD

**Issue by enchorb** [nativewind/nativewind#931]
As mentioned here https://github.com/nativewind/nativewind/issues/917, Tailwind 3.4.2 introduced some changes to how dark mode styles are generated. Which is not handled by NativeWind right now.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
