### ISSUE TITLE
setColorScheme 'system' Does Not Work

### ISSUE THREAD

**Issue by enchorb** [nativewind/nativewind#932]
As the title says would expect `setColorScheme` `system` to change the color scheme based on system settings. This is not the case.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
