### ISSUE TITLE
No way to specify global color and fonts for project

### ISSUE THREAD

**Issue by udohjeremiah** [nativewind/nativewind#933]
I'm sorry if this is not a "bug" but rather not a feature of nativewind v4. However if it is, I am currently finding no way to provide a global color scheme or fonts that all the project can use for light and dark mode. Is there a way to do this, so I don't keep typing `text-black` or `bg-black` but instead just specify the defaults I want, and then only use those ones when I want a different thing?

Thanks anyways for your work on nativewind, honestly it's a big game changer for styling made-easy in RN.

**Comment by udohjeremiah** [comment]
> use can use css variable to create new color per scheme or event font :
> 
> global.css
> 
> ```css
> ...
> @layer base {
>  :root {
>      --mycolor: #b8cedc;
>   }
>   dark:root {
>     --mycolor: #333;
>   }
> }
> ```
> 
> tailwind.config.ts
> 
> ```ts
> ...
>  theme: {
>     extend: {
>         colors: {
>            mycolor: "(var(--mycolor))"
>       }
>     }  
> ```

I know, but this still requires I write `text-mycolor`. I mean how do I specify `myColor` as the default color for black and white in either light mode or dark mode?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
