### ISSUE TITLE
Layout Shift while rendering in NextJS with App router & Nativewind v4

### ISSUE THREAD

**Issue by SantiMNV** [nativewind/nativewind#934]
**Describe the bug**
As you can see in this video, when a component uses `<Text> or <View>` from React Native, at first shows a UI and then all the css classes are applied and it gets layout shifted.

It only happens with NextJS app router, not pages router.
https://www.loom.com/share/9a93a0352b944e92b93888edee8e1e0d

**To Reproduce**
1. Use NextJS 13 or 14 app router
2. Create a component with` <Text> or <View>` from react nativewind
3. Launch
4. Refresh
5. See error

**Expected behavior**
No layout shift.

**Additional context**
Solito documentation is for nativewind v2
https://solito.dev/tailwind

I searched and found this
https://github.com/nandorojo/solito/issues/448

I tried this, but it has nextjs pages router
https://github.com/mikevocalz/solito-nativewind-v4
I updated it to app router and everything works nice but this

Thanks!

**Comment by SantiMNV** [comment]
Solved it with

https://github.com/SantiMNV/solito-nativewind-v4-app-router

**Comment by SantiMNV** [comment]
Hi Shawn i have taken a look at your project
I see apps/sovoli.com/app/page.tsx line 21 you are using a button 
But in https://www.sovoli.com/ i don't see that button is that the problem? Have you fixed it?

BTW in my current project i am not using nextjs, i am using expo router, nativewind and react native reusables but still testing, everything is so new

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
