### ISSUE TITLE
install nativewind@4.0.24 Afterwards, react-native-css interop does not have version 0.0.23, Every time you run Yarn, you need to make a selection

### ISSUE THREAD

**Issue by SnakeLil** [nativewind/nativewind#938]
**Describe the bug**
install nativewind@4.0.24 afterwards, react-native-css-interop does not have version 0.0.23, Every time you run Yarn, you need to make a selection

**Expected behavior**
Install automatically

**Screenshots**
![image](https://github.com/nativewind/nativewind/assets/143258708/2b83942b-7675-4ff4-b631-3aa54ef30f53)

**Comment by SnakeLil** [comment]
I noticed that react native css interop seems to be missing a version of 0.0.23

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
