### ISSUE TITLE
NativeWind with EAS Expo Internal Distribution build not applying styles, but does for EAS Development Build on Simulator

### ISSUE THREAD

**Issue by alexwolf22** [nativewind/nativewind#939]
**Describe the bug**
So I am building an app using expo, react-native, and NativeWind. I have been developing locally and using EAS development build and the expo dev client.

Library versions ( can share full package.json libs if needed)
- `"expo": "^51.0.0",`
- `"nativewind": "2.0.11",`
- `"react": "18.2.0",`
- `"react-native": "0.74.2",`
- `"tailwindcss": "3.3.2",` (devDependencies)
- `"@babel/core": "^7.23.9",`

My app is working perfecting using an running an EAS development build on a simulator on my mac, and all all styles applied with `className` are being rendering on the simulator properly when the expo dev server runs.

I am now testing my app on real devices. I am able to build an internal distribution EAS build successfully with no errors. However, I noticed none of the styles applied to my react native components with `className=` are being applied when running the app on a real device over an EAS development build on simulator with expo dev client.

I am completely stuck trying to figure out why this is happening.

My project is structured like below with all my react native code which uses NativeWind in the `src` dir.
```
.
├── README.md
├── app.config.ts
├── app.d.ts
├── assets
├── babel.config.js
├── baseEas.json
├── eas.json
├── env
├── ios
├── metro.config.js
├── node_modules
├── package-lock.json
├── package.json
├── src
├── tailwind.config.js
└── tsconfig.json
```

My tailwind css config is as follows
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    .....
  },
  plugins: [],
};
```

And my Babel config I have
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: ['babel-preset-expo'],
    plugins: [
      [
        'module-resolver',
        {
          root: ['./src'],
          extensions: ['.ios.ts', '.android.ts', '.ts', '.ios.tsx', '.android.tsx', '.tsx', '.jsx', '.js', '.json'],
        },
      ],
      'nativewind/babel',
    ],
  };
};
```

For some reason when I run the EAS internal distribution build on a real IOS or Android device, none of the `className` styles are applied, but it works when I run it on a simulator with an EAS development build with expo dev client.

I noticed if I remove the content in the tailwind config to nothing  `content: [],` when running my development build with expo dev client on my mac, I get the same screen when running the app on a real physical device, which tells me NativeWind className styles aren't being applied when running on a real device.

Is there extra setup you need to do for nativewind when doing an EAS build and running the app on a real physical device?

Should I be using nativewind v4 instead of v2 which I'm using currently?

If anyone can point to the direction of a solution it would be very much appreciated. I've been stuck on this bug for days.

**To Reproduce**
1. Make app with nativewind using and run on simulator using EAS development build and expo dev client
2. After app is working on simulator, make a EAS internal distribution build
3. Download app onto iPhone or android
4. ERROR: Will see no nativewind styles applied.

**Expected behavior**
EAS internal distribution build styles rendered exactly like how it does on the EAS development build on simulator.

**Comment by cogell** [comment]
I'm experiencing the same issue with `"nativewind": "^4.0.36"`

**Comment by alexwolf22** [comment]
@cogell  @sajorahasan What Expo SDK version are you using? Is possible doesn't work with expo 51.

**Comment by coyksdev** [comment]
related? https://github.com/nativewind/nativewind/issues/924

**Comment by alexwolf22** [comment]
@coyksdev looks related

**Comment by alexwolf22** [comment]
Hey @coyksdev that issue is actually for V4 nativewind. I am posting about v2 nativewind

**Comment by alexwolf22** [comment]
Okay I figured out the issue!!!!! =)

I had for someone reason `tailwind.config.js` in my `.gitignore` file which expo uses for it's .expo ignore; I think the auto .gitignore lib I used added it there =/

So during the build process it wasn't on the expo server, and babel wasn't running for nativewind.
