### ISSUE TITLE
[v4] - Expressions that are identical in runtime produce different outcomes with Nativewind

### ISSUE THREAD

**Issue by asktree** [nativewind/nativewind#941]
I am experiencing situations where, for example:

```ts
const CIRCLE_SIZE = 900

// ....

 <View
        className={`width-[${CIRCLE_SIZE}]`} 
 />
 ```
 
 Will not apply any style during development (production not tested) (or will sometimes work, only for certain values where the style has already been generated someplace else), but
 ```ts
 <View
        className={`width-[${900}]`} 
 />
 ```
 does work. 
 
For me, this is not the type of developer experience that I expect. Is this a known issue / "working as intended"? If not, is there anywhere I can go to get help with this and other apparent bugs in a timely fashion? I can also upload all of my configuration files if this is an unexpected behavior.

**Comment by garygcchiu** [comment]
Yep, found this happening for me too. A common use-case would be trying to offset something by the height of some component, like the TabBar, header, etc. Setting a style with the variable does not work, but if I hard-code the same value, it works. e.g.:

```
const height = useBottomTabBarHeight();
...
<View className={`h-[${height}px]`} />
```

Does not work, but:

```
<View className="h-[32px]" />
```

Works.

**Comment by samlaycock** [comment]
[https://tailwindcss.com/docs/content-configuration#dynamic-class-names](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)

**Comment by asktree** [comment]
Closing given @samlaycock 's guidance

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
