### ISSUE TITLE
Dark styles override light/default ones

### ISSUE THREAD

**Issue by presedo93** [nativewind/nativewind#942]
**Describe the bug**
In an expo app, using `expo-router` when setting, for example, `className="text-black dark:text-white"` it doesn't matter the theme selected. It always shows the styles set on the `dark:` tag.

I've been using the [React Native Template Obytes](https://github.com/obytes/react-native-template-obytes) as an inspiration on how to set things with nativewind. So, I also get the themes from `@react-navigation/native` and set the `ThemeProvider` as they do [here](https://github.com/obytes/react-native-template-obytes/blob/master/src/app/_layout.tsx#L53).

The theme is correctly set, because I can see how the `StatusBar` changes but the UI components don't change... the only difference I've seen with this template or some examples on the internet is that I'm trying to use default tailwind styles and not setting mines. Can it be the issue?

I've followed all the steps on the [dark mode](https://www.nativewind.dev/v4/core-concepts/dark-mode) section and the [expo router](https://www.nativewind.dev/v4/getting-started/expo-router) one...

Thanks!!

**Expected behavior**
When setting `light` theme, styles should be the default ones and not those marked with `dark:`.

**Comment by presedo93** [comment]
In my case was the `tailwindcss` version. Instead of being the last one, I set it to `3.3.2` which I think is the dependency `nativewind` has!

**Comment by bhyoo99** [comment]
@presedo93 Can you reopen this issue? I having same issue 


`"tailwindcss": "3.3.2"`
`"nativewind": "4.0.36"`

**Comment by busybox11** [comment]
Had the same issue, updating `tailwindcss` to `^3.4.4` seemingly fixed it.

**Comment by busybox11** [comment]
Well.. Unfortunately I can't confirm this actually fixed anything.
It looks like my issue is related to fast refresh not loading all the styles for some reason?
I've seen that `clsx` / spreading classes props could interfere with this, as I am using React Native Reusables, this could be the culprit - if the root cause actually is fast refresh.

I am having trouble to debug this issue, as there apparently isn't any tool to debug those styles and behaviors easily. My styles are not always generated, but when I force it, it doesn't work everywhere either.

**Comment by busybox11** [comment]
From the (very) limited time I had to debug this, it does look like all the colors get generated - but it applies the dark one anyway. If I manually change the style's color prop to the first one that matches the correct version, it does show the correct color.

Don't have time to dig into Nativewind's codebase yet. This is all I can provide. I'll assume this is a bug from this project for now and move on while keeping those broken colors, just in case.

![image](https://github.com/nativewind/nativewind/assets/29630035/d205a59b-a190-480a-96d8-bf2632e4a018)

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
