### ISSUE TITLE
Dark mode dosen't work in expo-router "single" mode

### ISSUE THREAD

**Issue by bhyoo99** [nativewind/nativewind#945]
**To Reproduce**
1. make project "yarn create expo-app -e with-router-tailwind
2. change output mode "single" in app.json
3. add tailwind.config.js, and set darkmode "class"

**Expected behavior**
html classname should be "dark"

**Screenshots**
<img width="1208" alt="image" src="https://github.com/nativewind/nativewind/assets/62757768/96cf3e08-c799-4b7a-9c92-7928f732d0f5">

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
