### ISSUE TITLE
platform specific not applied correctly in 4.0.36

### ISSUE THREAD

**Issue by chhornponleu** [nativewind/nativewind#950]
**Describe the bug**
Platform specific like `web:pr-6` also applied to ios

**To Reproduce**
```
<View className="web:pr-6">
   <Text>Hello</Text
</View/>
```

**Expected behavior**
`web:pr-6` should only apply to only web platform, not other platforms like ios
  
**Additional context**

> expo 51 with app router
> nativewind 4.0.36

**Comment by bhyoo99** [comment]
same

**Comment by maxilie** [comment]
I'm having the opposite problem (using expo 51.0.20 and nativewind 4.0.36) where `web:pr-6` does NOT apply any padding on web.

**Comment by WKampel** [comment]
My platform styles don't apply at all.

**Comment by maxilie** [comment]
> My platform styles don't apply at all.

I couldn't get the Platform variants like "web:" to work either, but I haven't had any issues using `vars` for state-driven styles and `cn` for Platform-specific styles. Sometimes a property like padding won't work properly unless you provide one for each Platform:

- `className={cn("pr-0", Platform.OS === "web" && "pr-6")}` or
- `className={Platform.select({web: "pr-6", default: "pr-0"})}`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
