### ISSUE TITLE
SafeAreaView TW styles are not being applied when using react-native-safe-area-context

### ISSUE THREAD

**Issue by pitops** [nativewind/nativewind#951]
**Describe the bug**
Adding a className to said package is not doing any styling but it does for SafeAreaView built in react-native.

**To Reproduce**
Just add a className to SafeAreaView -> styles are not applied. 

I am using Nativewind 4.0.36, Expo 51, react-native-safe-area-context 4.10.1

**Expected behavior**
Styles to be applied

**Comment by eoisaac** [comment]
Same issue here.

- tailwindcss: `3.4.4`
- nativewind: `4.0.36`
- react-native-safe-area-context: `4.10.1`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by ScreamZ** [comment]
Look at my https://github.com/nativewind/nativewind/issues/628#issuecomment-2397695480
