### ISSUE TITLE
[v4] ring doesnt seem to work

### ISSUE THREAD

**Issue by asktree** [nativewind/nativewind#954]
Tailwind's `ring` class doesn't appear to do anything (when attached to a View, anyway). I checked and verified that the output.css contains the right classes. Is this a known issue?

**Comment by ceopaludetto** [comment]
Ring properties are marked as web-only in the docs https://www.nativewind.dev/v4/tailwind/borders/ring-width

**Comment by PetarMarijanovic** [comment]
Is there an equivalent?

**Comment by ceopaludetto** [comment]
> Is there an equivalent?

I don't think so, but @marklawlor or @danstepanov can answer better

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
