### ISSUE TITLE
Compilation breaks when key prop comes after a spread

### ISSUE THREAD

**Issue by firatoezcan** [nativewind/nativewind#956]
**Describe the bug**
When building with Vite the following error comes up:

```
Build failed in 2.99s

 >  NX   [commonjs--resolver] Expression expected in /home/firat/Projects/Freelancing/bace/frontend-mono/node_modules/react-native-css-interop/dist/doctor.js

   file: /home/firat/Projects/Freelancing/bace/frontend-mono/node_modules/nativewind/dist/index.js:13:11
   
   11: }
   12: function verifyJSX() {
   13:     return <react-native-css-interop-jsx-pragma-check /> === true;
                  ^
   14: }
   15: exports.verifyJSX = verifyJSX;
   
   Pass --verbose to see the stacktrace.
```

Previously this meant that I had an `import { cssInterop } from "nativewind";` which broke bundling (for a good reason, even though the error is hard to understand)

But the error still came up so when debugging further, I found that it always occurs whenever I have the following construct:

```js
<div {...{}} key="something" />
```

This instantly breaks the build for whatever reason, the solution there is to move the key before the destructure.

**To Reproduce**
- Probably just create a default vite project and add the `div` above into it. This should break it

**Expected behavior**
Dunno, I don't even know why that breaks it. At best it shouldnt crash, or a better error message telling where this happens would be good. Or just add this information into the Troubleshooting section

**Additional context**
This is my `vite.config.ts`

```ts
/// <reference types="vitest" />
import { nxViteTsPaths } from "@nx/vite/plugins/nx-tsconfig-paths.plugin";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

const isDevelopment = process.env.NODE_ENV === "development";
const extensions = [".web.tsx", ".tsx", ".web.ts", ".ts", ".web.jsx", ".jsx", ".web.js", ".js", ".css", ".json", ".mjs"];

export default defineConfig({
  root: __dirname,
  cacheDir: "../../node_modules/.vite/app",
  define: {
    __DEV__: JSON.stringify(isDevelopment),
  },

  server: {
    port: 4200,
    host: "localhost",
  },

  preview: {
    port: 4300,
    host: "localhost",
  },

  plugins: [react(), nxViteTsPaths()],

  build: {
    outDir: "../../dist/apps/app",
    reportCompressedSize: true,
    commonjsOptions: { transformMixedEsModules: true },
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ["react", "react-dom", "react-native-web", "react-native-css-interop"],
        },
      },
    },
  },

  resolve: {
    alias: {
      "react-native": "react-native-web",
    },
    extensions,
  },

  esbuild: {
    jsx: "automatic",
    jsxImportSource: "nativewind",
  },
  optimizeDeps: {
    include: ["react-native-css-interop", "nativewind"],
    esbuildOptions: {
      resolveExtensions: extensions,
      loader: { ".js": "jsx" },
    },
  },
  
});

```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
