### ISSUE TITLE
[v4] hairlineWidth() and platformSelect() not working

### ISSUE THREAD

**Issue by focux** [nativewind/nativewind#958]
**Describe the bug**
Using `hairlineWidth()` or `platformSelect()` on the tailwind config file doesn't work. Looks like it doesn't compute the function value and instead just use the function name as the css value (see below). It happens with both `hairlineWidth` and `platformSelect` but to be honest I haven't tested using the other functions so those might be broken as well.

<img width="322" alt="image" src="https://github.com/nativewind/nativewind/assets/3316818/06a10dca-cbc1-4dca-a631-aa5a26a33db0">

<details>
<summary>tailwind config file</summary>

```js
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./modules/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      fontFamily: {
        heading: ['"SF Pro Display"'],
        body: ['"SF Pro Text"'],
        mono: ['"SF Pro Text"'],
        rounded: ['"SF Pro Rounded"'],
      },
       borderWidth: {
        hairline: hairlineWidth(),
      },
      spacing: {
        hairline: hairlineWidth(),
      },
    },
  },
  plugins: [],
};
```
</details>

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
