### ISSUE TITLE
`rtl` and `ltr` doesn't work on nativewind4

### ISSUE THREAD

**Issue by ws-rush** [nativewind/nativewind#959]
**Describe the bug**
when use `ltr:` or `rtl:` in nativewind it should not apply calss unless direction as in prefix, but nativewind run classes without care about them 

**To Reproduce**
https://github.com/ws-rush/reactive-expo

- above project contain example in src/app/components/EditScreenInfo.tsx: `<Text className="ltr:text-green-500 rtl:text-red-500">{description}</Text>`, i tried it also as `<Text className="text-green-500 rtl:text-red-500">{description}</Text>` and other cominations
- the code change direction in `src/app/globals/i18n.ts`: 
```
  async set(value: string) {
    // load and activate locale
    const { messages, direction } = this.localesData[value];
    i18n.load(value, messages);
    i18n.activate(value);

    // reload app
    if (direction === 'rtl') {
      await I18nManager.allowRTL(true);
      await I18nManager.forceRTL(true);
    } else {
      await I18nManager.allowRTL(false);
      await I18nManager.forceRTL(false);
    }

    if ((await locale.loadLocale()) !== value) {
      // set app default lang done from app settings
      await AsyncStorage.setItem('locale', value);

      if (Platform.OS === 'ios' || Platform.OS === 'android') reloadAsync();
      else if (Platform.OS === 'web') window.location.reload();
    }
  },
```
- finally the app should run in dvelopment build not expo go to get direction changed correctly (get `I18nManager.isRTL` correct value)

**Expected behavior**
it should apply classes with direction prefix only if application run in this direction

**Screenshots**
middle text is always red, it doesnt respect direction
![image](https://github.com/nativewind/nativewind/assets/37883750/742f38eb-c876-45e0-a288-226f56606669)

**Additional context**
there is no

**Comment by ws-rush** [comment]
I solved this proble currently by add this template tomy project

```ts
import { I18nManager } from "react-native";

export function tw(strings: TemplateStringsArray, ...values: any[]) {
    // Combine the string literals and the values into a single string
    let combinedString = strings.reduce((result, string, i) => {
      return result + string + (values[i] || '');
    }, '');
  
    // Split the combined string into an array of classes
    let classes = combinedString.split(' ');
  
    // Filter out classes that start with "rtl:"
    let filteredClasses = classes.filter(cls => !cls.startsWith(I18nManager.isRTL ? 'ltr:' : 'rtl:'));
  
    // Join the filtered classes back into a single string
    return filteredClasses.join(' ');
}
```

then apply it as `<Text className={tw`ltr:text-green-500 rtl:text-red-500`}>{`solved ${description}`}</Text>`

**Comment by ws-rush** [comment]
direction modifiers work on react-native-web, so I edited my above template function as following 

```ts
import { I18nManager, Platform } from "react-native";

export function tw(strings: TemplateStringsArray, ...values: any[]) {
    // Combine the string literals and the values into a single string
    let combinedString = strings.reduce((result, string, i) => {
      return result + string + (values[i] || '');
    }, '');
  
    // Split the combined string into an array of classes
    let classes = combinedString.split(' ');
  
    // Filter out classes that start with "rtl:"
    let filteredClasses = classes.filter(cls => {
      if (Platform.OS !== 'web') return !cls.startsWith(I18nManager.isRTL ? 'ltr:' : 'rtl:')
      else return true
    });
  
    // Join the filtered classes back into a single string
    return filteredClasses.join(' ');
}
```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.

**Comment by thebiltheory** [comment]
@danstepanov this is still happening in 4.1. Any idea why?

**Comment by hamzaCarswitch** [comment]
@danstepanov this is still happening in newer version using v4.1.21

my icon gets rotate 180, in LTR as well

```
<Pressable onPress={handleBackPress}>
    <View className="rtl:rotate-180">
         <assets.icons.back height={24} width={24} />
    </View>
</Pressable>
```
