### ISSUE TITLE
Dark theme doesn't  change for elements.

### ISSUE THREAD

**Issue by shawnmclean** [nativewind/nativewind#960]
I've been trying to setup a mono repo with shared components.

So far I have nextjs being able to change the theme correctly.

But on expo, the RN elements are not updating or switching over to dark mode.

Does anyone know how this works? When themes are switched, what happens in react native? Top level style changes or all components rebuilds?

Repro:  https://github.com/shawnmclean/sovoli

**Comment by dominikwozniak** [comment]
Hi @shawnmclean Ive got the same problem you had. Is there a chance to contact you?

**Comment by dominikwozniak** [comment]
@shawnmclean I noticed that it is hard to find a contact to you ;)  Going back, I am working on the same stack as you. I have a problem with changing `darkMode: "class"`. The methods I've tried don't work, and Nativewind keeps saying that my darkMode is set to media :/ It looks like it's a cached value that I can't change or overwrite. My code is here https://github.com/dominikwozniak/expo-cf-worker/tree/feature/dark-mode-switch 

Surely you can see the similarity to your code - it's a coincidence :D But the problem still occurs, maybe I forgot something? If you prefer an email, we can contact you - wozniakdominik7312@gmail.com

**Comment by dominikwozniak** [comment]
@shawnmclean Thanks! I've added simple instruction. Branch: `feature/dark-mode-switch`
It is about the dark theme switch when you enter the application. Don't worry about other packages and server connection. For dev needs you don't need setup server packages.
