### ISSUE TITLE
[v4] Dark Mode broke on related Nativewind apps

### ISSUE THREAD

**Issue by ShaneKeney** [nativewind/nativewind#963]
**Describe the bug**
Dark Mode has seemed to stopped working in any of my projects.  I tend to take the same approach to setting up dark mode with Nativewind so I'm probably misunderstanding some issue in the configuration level.  

**To Reproduce**
1. Go to https://github.com/ShaneKeney/repro-example-3
2. Create custom dev simulator build with `bun eas:build:develop:ios:sim`.  You will need to tweak some values in `app.config.ts` to point at your eas environment.
3. Download app simulator build and run via `bun dev:client`
4. Pressing manual toggle in upper right corner will show correct dark mode styling but light mode styling does not take precedence when switched to light mode.

**Expected behavior**
When "dark mode" is enabled the `dark:*` utility classes should be what is represented in the UI.  When "dark mode" is disabled, the light mode color classes should be shown.

There are several locations where this is occurring in the app.  One isolated place is the `Typography` component.  Nativewind manual toggling of dark mode / light mode does not seem to be working as expected i..e

```
function Typography({ font, size, children, className, ...props }: Props) {
  console.log(`${variants({ font: font, size: size })} ${className}`);
  return (
    <Text className={`${variants({ font: font, size: size })} ${className}`} {...props}>
      {children}
    </Text>
  );
}
```

`className` here for "Welcome" header title for welcome tab is:

`color-text dark:color-text-dark font-geist-thin text-body-16 undefined`

This is working for dark mode where `dark:color-text-dark` is showing as "white" based on `tailwind.config.js` but the "light mode" variant `color-text` which is a "blackish" color is not represented when the app is manually toggled to "dark mode" via the switch.

**Screenshots**
Dark Mode (Works as expected)
<img width="440" alt="Screenshot 2024-07-03 at 4 55 33 PM" src="https://github.com/nativewind/nativewind/assets/53321733/ee4af4d3-a39d-40b9-8346-8b0a5752bdc1">

Light Mode (Does NOT work as expected)
<img width="433" alt="Screenshot 2024-07-03 at 4 56 11 PM" src="https://github.com/nativewind/nativewind/assets/53321733/3e7cc74c-ef9c-421a-a09f-2476cdfc57d3">

**Comment by ShaneKeney** [comment]
@danstepanov Was going to reach out to offer any help for testing Nativewind with production and related apps for upcoming July release of V4.  Didn't know how to get in contact with you directly.  Tagging you directly for one recent issue ran across with all of my projects related to dark mode.

**Comment by kimjoongwon** [comment]
i'm experiencing the same issue.
I am also experiencing it as an early expo project.

**Comment by mrzachnugent** [comment]
I had to specify the exact `3.3.5` version.

**Comment by FNG-2002** [comment]
The docs (https://tailwindcss.com/docs/dark-mode#toggling-dark-mode-manually) specify that the selector strategy replaced the class strategy in Tailwind CSS v3.4.1. But it doesn't work in my project with NativeWind V4. I had to go back to Tailwind v3.4.0 to make it work with the "class"-selector in the tailwind.config.js.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
