### ISSUE TITLE
After installing, I am unable to build the react native expo app to a apk.

### ISSUE THREAD

**Issue by SteelyxYT** [nativewind/nativewind#967]
I used the v4 docs for react native on how install it. It works fine in expo go but when I do `eas build -p android` it fails with a gradlew error.

```
Android Bundling failed 70150ms node_modules/expo-router/entry.js (1235 modules)
Error: Unable to resolve module /home/expo/workingdir/build/node_modules/.cache/nativewind/global.css from /home/expo/workingdir/build/global.css: 
None of these files exist:
  * node_modules/.cache/nativewind/global.css(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
  * node_modules/.cache/nativewind/global.css/index(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
> 1 | @tailwind base;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | @tailwind components;
  3 | @tailwind utilities;
Error: Unable to resolve module /home/expo/workingdir/build/node_modules/.cache/nativewind/global.css from /home/expo/workingdir/build/global.css: 
None of these files exist:
  * node_modules/.cache/nativewind/global.css(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
  * node_modules/.cache/nativewind/global.css/index(.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx|.android.mjs|.native.mjs|.mjs|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.cjs|.native.cjs|.cjs|.android.scss|.native.scss|.scss|.android.sass|.native.sass|.sass|.android.css|.native.css|.css|.android.css|.native.css|.css)
> 1 | @tailwind base;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  2 | @tailwind components;
  3 | @tailwind utilities;
    at ModuleResolver.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:112:15)
    at DependencyGraph.resolveDependency (/home/expo/workingdir/build/node_modules/metro/src/node-haste/DependencyGraph.js:231:43)
    at /home/expo/workingdir/build/node_modules/metro/src/lib/transformHelpers.js:156:21
    at resolveDependencies (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:42:25)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:83:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 2)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
    at async Promise.all (index 0)
    at visit (/home/expo/workingdir/build/node_modules/metro/src/DeltaBundler/buildSubgraph.js:92:5)
> Task :app:createBundleReleaseJsAndAssets FAILED
> Task :react-native-safe-area-context:generateReleaseLintModel
> Task :expo-modules-core:buildCMakeRelWithDebInfo[arm64-v8a]
> Task :react-native-reanimated:buildCMakeRelWithDebInfo[arm64-v8a]
FAILURE: Build failed with an exception.
* What went wrong:

Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
BUILD FAILED in 6m 27s
301 actionable tasks: 301 executed
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.
```

**Comment by SteelyxYT** [comment]
Changed to v2 and it works.

**Comment by Motter10** [comment]
Hi, did you find a solution?

**Comment by SteelyxYT** [comment]
> Hi, did you find a solution?

I switched to v2 and it worked

**Comment by thonyromes** [comment]
Experiencing similar issue with bare react-native 0.74.5 with gradle 8.7 and above

**Comment by Yuvaraja28** [comment]
```Android gradle plugin: 8.2.1
Gradle: 8.6
Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
WARNING: The specified Android SDK Build Tools version (33.0.0) is ignored, as it is below the minimum supported version (34.0.0) for Android Gradle Plugin 8.2.1.
Android SDK Build Tools 34.0.0 will be used.
To suppress this warning, remove "buildToolsVersion '33.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :app:createBundleReleaseJsAndAssets
(node:5768) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
debug Reading Metro config from <folder>\metro.config.js      
warning: the transform cache was reset.
                Welcome to Metro v0.80.11
              Fast - Scalable - Integrated


'<folder>' is not recognized as an internal or external command,
operable program or batch file.
error Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css
'<folder>' is not recognized as an internal or external command,
operable program or batch file.
.
Error: Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css                   
'<folder>' is not recognized as an internal or external command,
operable program or batch file.

    at genericNodeError (node:internal/errors:983:15)
    at wrappedFn (node:internal/errors:537:14)
    at checkExecSyncError (node:child_process:889:11)
    at execSync (node:child_process:961:15)
    at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\tailwind\v3\index.js:27:38)
    at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\index.js:22:24)
    at Object.getTransformOptions (<folder>\node_modules\react-native-css-interop\dist\metro\index.js:39:143)
    at async calcTransformerOptions (<folder>\node_modules\metro\src\lib\transformHelpers.js:70:25)
    at async Object.getTransformFn (<folder>\node_modules\metro\src\lib\transformHelpers.js:104:51)
    at async IncrementalBundler.buildGraphForEntries (<folder>\node_modules\metro\src\IncrementalBundler.js:60:18)

> Task :app:createBundleReleaseJsAndAssets FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> Process 'command 'cmd'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 1m 35s
31 actionable tasks: 26 executed, 5 up-to-date```

I'm also facing the same problem with Nativewind V4.1.6 and tailwindcss 3.4.10

Is there any fix available other than downgrading both tailwindcss and nativewind, because i've developed it fully with the latest tailwindcss and downgrading it to the lower tailwindcss version might break all the designs

Hope there is a fix for this issue without downgrading...

**Comment by thonyromes** [comment]
> ```
> Gradle: 8.6
> Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> WARNING: The specified Android SDK Build Tools version (33.0.0) is ignored, as it is below the minimum supported version (34.0.0) for Android Gradle Plugin 8.2.1.
> Android SDK Build Tools 34.0.0 will be used.
> To suppress this warning, remove "buildToolsVersion '33.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> 
> > Task :app:createBundleReleaseJsAndAssets
> (node:5768) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> (Use `node --trace-deprecation ...` to show where the warning was created)
> debug Reading Metro config from <folder>\metro.config.js      
> warning: the transform cache was reset.
>                 Welcome to Metro v0.80.11
>               Fast - Scalable - Integrated
> 
> 
> '<folder>' is not recognized as an internal or external command,
> operable program or batch file.
> error Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css
> '<folder>' is not recognized as an internal or external command,
> operable program or batch file.
> .
> Error: Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css                   
> '<folder>' is not recognized as an internal or external command,
> operable program or batch file.
> 
>     at genericNodeError (node:internal/errors:983:15)
>     at wrappedFn (node:internal/errors:537:14)
>     at checkExecSyncError (node:child_process:889:11)
>     at execSync (node:child_process:961:15)
>     at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\tailwind\v3\index.js:27:38)
>     at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\index.js:22:24)
>     at Object.getTransformOptions (<folder>\node_modules\react-native-css-interop\dist\metro\index.js:39:143)
>     at async calcTransformerOptions (<folder>\node_modules\metro\src\lib\transformHelpers.js:70:25)
>     at async Object.getTransformFn (<folder>\node_modules\metro\src\lib\transformHelpers.js:104:51)
>     at async IncrementalBundler.buildGraphForEntries (<folder>\node_modules\metro\src\IncrementalBundler.js:60:18)
> 
> > Task :app:createBundleReleaseJsAndAssets FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> > Process 'command 'cmd'' finished with non-zero exit value 1
> 
> * Try:
> > Run with --stacktrace option to get the stack trace.
> > Run with --info or --debug option to get more log output.
> > Run with --scan to get full insights.
> > Get more help at https://help.gradle.org.
> 
> BUILD FAILED in 1m 35s
> 31 actionable tasks: 26 executed, 5 up-to-date
> ```
> 
> I'm also facing the same problem with Nativewind V4.1.6 and tailwindcss 3.4.10
> 
> Is there any fix available other than downgrading both tailwindcss and nativewind, because i've developed it fully with the latest tailwindcss and downgrading it to the lower tailwindcss version might break all the designs
> 
> Hope there is a fix for this issue without downgrading...

I experienced this a lot on nativewind: 4.1.6. Currently, I had to downgrade nativewind to 4.036 to get it to work. Don’t forget to clean up all build folders, cache, gradle cache, node_modules, lock files etc.

**Comment by Yuvaraja28** [comment]
> > ```
> > Gradle: 8.6
> > Warning: SDK processing. This version only understands SDK XML versions up to 3 but an SDK XML file of version 4 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
> > WARNING: The specified Android SDK Build Tools version (33.0.0) is ignored, as it is below the minimum supported version (34.0.0) for Android Gradle Plugin 8.2.1.
> > Android SDK Build Tools 34.0.0 will be used.
> > To suppress this warning, remove "buildToolsVersion '33.0.0'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
> > 
> > > Task :app:createBundleReleaseJsAndAssets
> > (node:5768) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> > (Use `node --trace-deprecation ...` to show where the warning was created)
> > debug Reading Metro config from <folder>\metro.config.js      
> > warning: the transform cache was reset.
> >                 Welcome to Metro v0.80.11
> >               Fast - Scalable - Integrated
> > 
> > 
> > '<folder>' is not recognized as an internal or external command,
> > operable program or batch file.
> > error Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css
> > '<folder>' is not recognized as an internal or external command,
> > operable program or batch file.
> > .
> > Error: Command failed: <folder>\node_modules\tailwindcss\lib\cli.js --input <folder>\global.css --output <folder>\node_modules\nativewind\.cache\global.css.android.css                   
> > '<folder>' is not recognized as an internal or external command,
> > operable program or batch file.
> > 
> >     at genericNodeError (node:internal/errors:983:15)
> >     at wrappedFn (node:internal/errors:537:14)
> >     at checkExecSyncError (node:child_process:889:11)
> >     at execSync (node:child_process:961:15)
> >     at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\tailwind\v3\index.js:27:38)
> >     at Object.processPROD (<folder>\node_modules\nativewind\dist\metro\index.js:22:24)
> >     at Object.getTransformOptions (<folder>\node_modules\react-native-css-interop\dist\metro\index.js:39:143)
> >     at async calcTransformerOptions (<folder>\node_modules\metro\src\lib\transformHelpers.js:70:25)
> >     at async Object.getTransformFn (<folder>\node_modules\metro\src\lib\transformHelpers.js:104:51)
> >     at async IncrementalBundler.buildGraphForEntries (<folder>\node_modules\metro\src\IncrementalBundler.js:60:18)
> > 
> > > Task :app:createBundleReleaseJsAndAssets FAILED
> > 
> > FAILURE: Build failed with an exception.
> > 
> > * What went wrong:
> > Execution failed for task ':app:createBundleReleaseJsAndAssets'.
> > > Process 'command 'cmd'' finished with non-zero exit value 1
> > 
> > * Try:
> > > Run with --stacktrace option to get the stack trace.
> > > Run with --info or --debug option to get more log output.
> > > Run with --scan to get full insights.
> > > Get more help at https://help.gradle.org.
> > 
> > BUILD FAILED in 1m 35s
> > 31 actionable tasks: 26 executed, 5 up-to-date
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm also facing the same problem with Nativewind V4.1.6 and tailwindcss 3.4.10
> > Is there any fix available other than downgrading both tailwindcss and nativewind, because i've developed it fully with the latest tailwindcss and downgrading it to the lower tailwindcss version might break all the designs
> > Hope there is a fix for this issue without downgrading...
> 
> I experienced this a lot on nativewind: 4.1.6. Currently, I had to downgrade nativewind to 4.036 to get it to work. Don’t forget to clean up all build folders, cache, gradle cache, node_modules, lock files etc.

This Really worked like a charm, thanks for the information ✨✨✨
