### ISSUE TITLE
Generated react-native-stylesheet is overriding my tailwind classnames

### ISSUE THREAD

**Issue by shawnmclean** [nativewind/nativewind#968]
Can anyone explain how the generated css classnames work?

It is interfering with my tailwind styles.

For example:

```
<View className="m-2 p-4 border-2">
  <Text>Should have a border with padding</Text>
</View>
```

Is generating this:

```
<div class="css-view-175oi2r m-2 p-4 border-2">
    <div class="...">Should have a border with padding</div>
</div>
```

With the styles:

```
.css-view-175oi2r {
    align-items: stretch;
    background-color: rgba(0, 0, 0, 0.00);
    border: 0 solid black;
    box-sizing: border-box;
    display: flex;
    flex-basis: auto;
    flex-direction: column;
    flex-shrink: 0;
    list-style: none;
    margin: 0px;
    min-height: 0px;
    min-width: 0px;
    padding: 0px;
    position: relative;
    text-decoration: none;
    z-index: 0;
}
```

Where is this coming from?

If I manually remove the class, the styles are rendered properly.

This is with `important: 'html',` in tailwind.config.js.

This can be reproduced on any project, even the expo snack  on the main readme, you'll see this generated class thats overriding especially borders.

Repro: [here](https://github.com/shawnmclean/sovoli/blob/main/apps/sovoli.com/src/app/testbed/Component.tsx)
Can be seen [live here](https://www.sovoli.com/testbed).

**Comment by Topiya** [comment]
@shawnmclean 
Did you get any solution to stop getting css-view-175oi2r class ?
As I am also facing the same issue and my given class styles are not applying properly due to this class.
