### ISSUE TITLE
Intelligent prompt only with className propName

### ISSUE THREAD

**Issue by Manweill** [nativewind/nativewind#978]
**Describe the bug**
Intelligent prompt only for className propName. when i rename other propName like containerClassName, it not work.

How can i do support any [*]ClassName propName.

**To Reproduce**
version: 
 - "tailwindcss": "^3.4.4"
 - "nativewind": "4.0.36",

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
