### ISSUE TITLE
Error generating build android Expo(Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information)

### ISSUE THREAD

**Issue by vitorl1maa** [nativewind/nativewind#979]
I am trying to generate an Android build using React-native and Expo, but I have been encountering the following error:

`Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

`10 errors
> Task :app:compileDebugJavaWithJavac FAILED
> Task :react-native-quick-base64:configureCMakeDebug[armeabi-v7a]
C/C++: CMake Warning (dev) in CMakeLists.txt:
C/C++:   No project() command is present.  The top-level CMakeLists.txt file must
C/C++:   contain a literal, direct call to the project() command.  Add a line of
C/C++:   code such as
C/C++:     project(ProjectName)
C/C++:   near the top of the file, but after cmake_minimum_required().
C/C++:   CMake is pretending there is a "project(Project)" command on the first
C/C++:   line.
C/C++: This warning is for project developers.  Use -Wno-dev to suppress it.
> Task :expo-modules-core:buildCMakeDebug[arm64-v8a]
> Task :react-native-reanimated:buildCMakeDebug[arm64-v8a]
w: Detected multiple Kotlin daemon sessions at build/kotlin/sessions
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
612 actionable tasks: 612 executed
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
* Try:
> Run with --info option to get more log output.
> Run with --scan to get full insights.
BUILD FAILED in 7m 8s
Error: Gradle build failed with unknown error. See logs for the "Run gradlew" phase for more information.`

I ran the expo-doctor command, but as you can see, it didn't find any issues:
![A1xXgG8J](https://github.com/user-attachments/assets/fb20c2a6-797c-4fed-80f2-79edabeae164)

In the gradle-wrapper.properties file inside the gradle\wrapper directory, I changed the distribution version to 8.2 because I saw that it is the minimum version supported by Gradle.

`distributionUrl=https://services.gradle.org/distributions/gradle-8.2-all.zip`

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
