### ISSUE TITLE
[V4] Conditionally rendered elements in a component don't receive styles properly

### ISSUE THREAD

**Issue by asktree** [nativewind/nativewind#980]
For example, if you render 
```ts
<> {stateBool && <View className="h-12 w-12 bg-red-400 animate-spin" />}</>
```
...styles are applied either inconsistently or not at all. Moving the conditionally rendered JSX to its own component seems to fix this. 
Is this a known issue?

Edit: My solution involving "Moving the conditionally rendered JSX to its own component seems to fix this." stopped working for me today.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
