### ISSUE TITLE
[V4] jsxImportSource was not set to 'nativewind'.

### ISSUE THREAD

**Issue by goker-dev** [nativewind/nativewind#981]
**Describe the bug**

Uncaught Error
jsxImportSource was not set to 'nativewind'. Please refer to http://nativewind.dev/troubleshooting#jsxImportSource

_react-native@0.74.3_
_expo@51.0.22_ 
_nativewind@4.0.36_
_tailwindcss@3.4.6_

**To Reproduce**
1. Get Started from https://reactnative.dev/docs/environment-setup
2. Build a fresh repo by `npx create-expo-app@latest`.  It comes  with  _"expo-router": "~3.5.18"_.
3. Install _nativewind_ from _https://www.nativewind.dev/v4/getting-started/expo-router_ .
  a. npm install nativewind@^4.0.1 react-native-reanimated tailwindcss
  b. npx expo prebuild
  c. npx pod-install
  d. npx tailwindcss init
  e. npx expo customize metro.config.js
4. Add `../../global.css` to _app/(tabs)/_layout.tsx_
5. Call ` verifyInstallation();` from   _app/(tabs)/index.tsx_

**env**
node: v20.10.0
npm: 10.2.3

_metro.config.js_
```
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');
const { withNativeWind } = require('nativewind/metro');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);

module.exports = withNativeWind(config, { input: './global.css' })
```

_babel.config.js_
```
module.exports = function (api) {
  api.cache(true);
  return {
    presets: [
      ["babel-preset-expo", { jsxImportSource: "nativewind" }],
      "nativewind/babel",
    ],
  };
};
```

_tailwind.config.js_
```
/** @type {import('tailwindcss').Config} */
module.exports = {
  // NOTE: Update this to include the paths to all of your component files.
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
}
```

_package.json_
```
{
  "name": "kodkafa-mobile",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-navigation/native": "^6.0.2",
    "expo": "~51.0.22",
    "expo-constants": "~16.0.2",
    "expo-font": "~12.0.9",
    "expo-linking": "~6.3.1",
    "expo-router": "~3.5.18",
    "expo-splash-screen": "~0.27.5",
    "expo-status-bar": "~1.12.1",
    "expo-system-ui": "~3.0.7",
    "expo-web-browser": "~13.0.3",
    "nativewind": "^4.0.36",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-native": "0.74.3",
    "react-native-gesture-handler": "~2.16.1",
    "react-native-reanimated": "~3.10.1",
    "react-native-safe-area-context": "4.10.5",
    "react-native-screens": "3.31.1",
    "react-native-web": "~0.19.10",
    "tailwindcss": "^3.4.6"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.2.45",
    "@types/react-test-renderer": "^18.0.7",
    "jest": "^29.2.1",
    "jest-expo": "~51.0.3",
    "react-test-renderer": "18.2.0",
    "typescript": "~5.3.3"
  },
  "private": true
}
```

**Comment by mathis-kdio** [comment]
I have the same issue. I have read the V4 troubleshooting documentation https://www.nativewind.dev/v4/troubleshooting#jsxImportSource
How can I determine which preset or plugin is overriding the jsxImportSource ?

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
