### ISSUE TITLE
react native CLI - nativewind configuration for IOS APP

### ISSUE THREAD

**Issue by preetypun82** [nativewind/nativewind#982]
**Describe the bug**

I am trying to setup the project on a  MacBook pro using CLI and installed latest version on nativewind 4, but all I receive is an error for bable configurations. I am using instructions for here https://www.nativewind.dev/quick-starts/react-native-cli

babel.config.js

module.exports = {
  presets: ['module:@react-native/babel-preset'],
  plugins: ["nativewind/babel"],
};

<img width="339" alt="Screenshot 2024-07-26 at 1 34 57 PM" src="https://github.com/user-attachments/assets/bc38337f-aba0-4841-8f85-090521906e09">

I have only followed the installation manual and tried to run the default app. A help fix this issue will be great. Thank you in advance.

**To Reproduce**

**Expected behavior**

**Expo Snack**
If applicable, add a link to an Expo snack demonstrating the issue. There are multiple example snacks available at nativewind.dev.

**Screenshots**

**Additional context**

**Comment by oneilsoftware-brandonmiller** [comment]
set up for v4 is different than the example you need to go to the beta docs for v4

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
