### ISSUE TITLE
[v4] group-{modifier} does not respect "disabled" on web

### ISSUE THREAD

**Issue by jimmi-joensson** [nativewind/nativewind#985]
**Describe the bug**
Group-{modifiers} like `group-hover` and `group-active` does not respect `disabled` prop on supported React Native components like `<Pressable disabled />` on web.

**To Reproduce**
1. Setup new expo project using: `npx create-expo-app -e with-router-tailwind`
2. Use the Button demo from the code shared at section "Additonal context"
3. Run project on native and web
4. See difference

**Expected behavior**
I expect the elements styled using `group-hover/button:` and `group-active/button:` not to apply when group component is set to disabled crossplatform.

**Screenshots**

![image](https://github.com/user-attachments/assets/4e37e07b-2505-452b-a82a-aa7fd3a1f06c)

*Screen recording:*
https://github.com/user-attachments/assets/c969edb7-9f71-4347-9c2a-1de9dfe35712

**Additional context**
```
        <View>
          <Text className="mb-2">Default:</Text>
          <Pressable className="group/button flex-row items-center gap-2 rounded-full bg-blue-500 p-2 opacity-100 transition-colors hover:bg-blue-600 active:bg-blue-300 disabled:opacity-50">
            <View className="transisition-colors h-4 w-4 rounded-full bg-slate-100 group-hover/button:bg-slate-200 group-active/button:bg-slate-600 group-disabled/button:bg-slate-100" />
            <Text className="text-slate-100 group-hover/button:text-slate-200 group-active/button:text-slate-600 group-disabled/button:text-slate-100">
              {'Test group-{modifiers}'}
            </Text>
          </Pressable>
          <Text className="mb-2 mt-8">Disabled:</Text>
          <Pressable
            disabled
            className="group/button flex-row items-center gap-2 rounded-full bg-blue-500 p-2 opacity-100 transition-colors hover:bg-blue-600 active:bg-blue-300 disabled:opacity-50"
          >
            <View className="transisition-colors h-4 w-4 rounded-full bg-slate-100 group-hover/button:bg-slate-200 group-active/button:bg-slate-600 group-disabled/button:bg-slate-100" />
            <Text className="text-slate-100 group-hover/button:text-slate-200 group-active/button:text-slate-600 group-disabled/button:text-slate-100">
              {'Test group-{modifiers}'}
            </Text>
          </Pressable>
        </View>
```

**Comment by mo9a7i** [comment]
shouldn't u use `group/button-hover:` `group/button-active` sine you named the group group/button ?

I'm not sure if group/button is working option in tailwind, but double check here.

**Comment by jimmi-joensson** [comment]
> shouldn't u use `group/button-hover:` `group/button-active` sine you named the group group/button ?
> 
> I'm not sure if group/button is working option in tailwind, but double check here.

@mo9a7i It should be the legit syntax according to the official [Tailwindcss documentation](https://tailwindcss.com/docs/hover-focus-and-other-states#differentiating-nested-groups)

Also as you can see in my example it works on native, just not on the web.

**Comment by marklawlor** [comment]
This is a bug with React Native Web not disabling pointer events when a pressable is disabled. You can replicate this behaviour without NativeWind by testing with your own custom className

```
<Pressable
  disabled
  style={[{ $$css: true, className: "my-classname" }]}
>

.my-classname: hover {
  // styles
}
```
