### ISSUE TITLE
Classes not applying after rebuild

### ISSUE THREAD

**Issue by guiqis** [nativewind/nativewind#986]
Hi guys,

I'm having a problem and I'm not sure if you have any idea of how I can fix it.

Some classes, after I'm using them in my app, simply don't work when I restart/rebuild my app. Example: m-3. The component acts as it has no class. Once I change it to m-2 or m-4 it applies. The only way that I can find to see it working is, when the app is loaded, change the name of any page function. Then the app does a hot reload and everything works fine.

I'm using className, not styles.

**Comment by WilliamWelsh** [comment]
Almost always a cache issue or missing something something in `content` in `tailwind.config.ts`

**Comment by Pandazaur** [comment]
Following the tutorial, I have the same issue.
At the first launch (when I'm in dev mode), no classes applied. When the hot reload does the job, the classes are applied

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
