### ISSUE TITLE
v4: next.js - Cannot access displayName.toString on the server

### ISSUE THREAD

**Issue by johnf** [nativewind/nativewind#987]
**Describe the bug**
I'm using a monorepo setup with react-native-web and next.js. I've gone through the v4 setup but I am seeing this error.

```
⨯ Error: Cannot access displayName.toString on the server. You cannot dot into a client module from a server component. You can only pass the imported name through.
    at __webpack_require__ (/home/johnf/work/gladly/mobile/packages/web/.next/server/webpack-runtime.js:33:43)
    at RootLayout (./src/app/layout.tsx:43:97)
    at stringify (<anonymous>)
digest: "2698290890"
```

**My investigation**

I tracked down the issue to https://github.com/nativewind/nativewind/blob/main/packages/react-native-css-interop/src/runtime/web/api.ts#L79-L81. Although, I suspect all the displayName references in https://github.com/nativewind/nativewind/blob/main/packages/react-native-css-interop/src/runtime/native/render-component.ts might cause issues if I was using anything Animated/

This change solves my issue
```diff
- interopComponent.displayName = `CssInterop.${baseComponent.name ?? "unknown"}`;
+ interopComponent.displayName = `CssInterop.${baseComponent.displayName ?? baseComponent.name ?? "unknown"}`;
```

No idea if this has side effects other than what things are called in devtools.

**To Reproduce**
* If needed, I can create a repo that replicates the behaviour.

**Expected behavior**
No error, everything renders fine

**Expo Snack**
N/A

**Screenshots**
N/A

**Additional context**

**Comment by danstepanov** [comment]
Please provide a repro in v4.1
https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue

**Comment by johnf** [comment]
@danstepanov Check out https://github.com/johnf/nativewind-nextjs for a repro
The main branch is a broken app
The fix branch applies a patch to react-native-css-interop
My fix is purely a workaround I doubt it's the correct approach :)

**Comment by mrzachnugent** [comment]
Hey @johnf, you can check out https://github.com/mrzachnugent/react-native-reusables-nextjs-demo as a reference for getting NativeWind to work with Nextjs

**Comment by johnf** [comment]
@mrzachnugent I upgrade all the packages in my repro and the problem seems to go away so something has changed since to resolve it. Thanks
