### ISSUE TITLE
Button bug

### ISSUE THREAD

**Issue by ImamJanjua** [nativewind/nativewind#990]
When using only expo api routes, the active state effect on the will not go away

https://github.com/user-attachments/assets/4b9a4ca0-32ed-45c3-96e2-6a24abe5561c

https://github.com/ImamJanjua/button-bug

**Comment by badalsaibo** [comment]
Always mention the Nativewind version on the title

**Comment by ImamJanjua** [comment]
@badalsaibo v4

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
