### ISSUE TITLE
spin animation not works

### ISSUE THREAD

**Issue by ImamJanjua** [nativewind/nativewind#991]
So I have this code, The Icons is a is a spinner icon, I want  that to rotate but the animation will not work

```typescript
import { Icons } from "@/components/Icons";
import { cn } from "@/lib/utils";
import { SvgProps } from "react-native-svg";

export const LoadingSpinner: React.FC<SvgProps> = ({ className, ...props }) => {
  return <Icons.spinner className={cn("animate-spin", className)} {...props} />;
};

```

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
