### ISSUE TITLE
 nativewind v4 not working on vite

### ISSUE THREAD

**Issue by yyuunn922** [nativewind/nativewind#992]
**Describe the bug**
I love the nativewind project, it's such a fascinating, great project.
There was a problem introducing react-native-web, and I've been struggling with this problem for several weeks.

When using vite and v4 in react-native-web, it works well in the mobile environment, but the class is not created on the web.

It is not an expo project

**To Reproduce**

This is an example project with the necessary libraries installed.

https://github.com/yyuunn922/react-native-web-vite

- how to reproduce the problem
1. git clone https://github.com/yyuunn922/react-native-web-vite
2. npm install

-  good work in mobile
3. react-native start --reset-cache
4. react-native run-android

- not work in web
3. run vite

**Expected behavior**
in mobile good working of nativewind but web not working.
It seems that the className of the native tag is not replicated to the web tag class.

<img width="503" alt="스크린샷 2024-08-09 오전 11 29 14" src="https://github.com/user-attachments/assets/7a34f3cd-1fd4-4691-931f-c2acba9d0dd0">

<img width="467" alt="스크린샷 2024-08-09 오전 11 29 55" src="https://github.com/user-attachments/assets/c27191b1-6e92-48ef-99e8-275111c65639">

<img width="598" alt="스크린샷 2024-08-09 오전 11 30 18" src="https://github.com/user-attachments/assets/c293f15f-6148-4497-860c-1b45eb162c99">

**Methods attempted to solve**
```// vite.config.ts
  import {defineConfig} from 'vite';
import react from '@vitejs/plugin-react';

const extensions = [
  '.web.tsx',
  '.tsx',
  '.web.ts',
  '.ts',
  '.web.jsx',
  '.jsx',
  '.web.js',
  '.js',
  '.css',
  '.json',
  '.mjs',
];

export default defineConfig({
  clearScreen: true,
  plugins: [
    react({
      babel: {       // <<<<<<<<<<     I added this line 
        plugins: [['nativewind/babel', {mode: 'transformOnly'}]],
      }, //
    }),
  ],
  resolve: {
    extensions: extensions,
    alias: {
      'react-native': 'react-native-web',
    },
  },
});
```

However, it is not resolved and the following error occurs.

```
11:36:10 AM [vite] Pre-transform error: [BABEL] /Users/Test/WebstormProjects/react-native-web-vite/index.js: .plugins is not a valid Plugin property
11:36:10 AM [vite] Internal server error: [BABEL] /Users/Test/WebstormProjects/react-native-web-vite/index.js: .plugins is not a valid Plugin property
  Plugin: vite:react-babel
  File: /Users/Test/WebstormProjects/react-native-web-vite/index.js
      at /Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/validation/plugins.js:58:42
      at Array.forEach (<anonymous>)
      at validatePluginObject (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/validation/plugins.js:48:20)
      at /Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/full.js:222:55
      at Generator.next (<anonymous>)
      at Function.<anonymous> (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
      at Generator.next (<anonymous>)
      at step (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:261:32)
      at evaluateAsync (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:291:5)
      at Function.errback (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:113:7)
      at errback (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/gensync-utils/async.js:65:18)
      at async (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:188:17)
      at onFirstPause (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:216:13)
      at Generator.next (<anonymous>)
      at cachedFunction (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/caching.js:52:46)
      at cachedFunction.next (<anonymous>)
      at loadPluginDescriptor (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/full.js:259:17)
      at loadPluginDescriptor.next (<anonymous>)
      at loadPluginDescriptors (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/full.js:129:33)
      at loadPluginDescriptors.next (<anonymous>)
      at /Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/full.js:156:21
      at Generator.next (<anonymous>)
      at loadFullConfig (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/config/full.js:141:5)
      at loadFullConfig.next (<anonymous>)
      at transform (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/transform.js:20:44)
      at transform.next (<anonymous>)
      at step (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:269:25)
      at evaluateAsync (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:291:5)
      at /Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:93:9
      at new Promise (<anonymous>)
      at async (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/gensync/index.js:92:14)
      at stopHiding - secret - don't use this - v1 (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/errors/rewrite-stack-trace.js:47:12)
      at Module.transformAsync (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@babel/core/lib/transform.js:45:77)
      at TransformPluginContext.transform (/Users/Test/WebstormProjects/react-native-web-vite/node_modules/@vitejs/plugin-react/dist/index.cjs:189:35)
      at async PluginContainer.transform (file:///Users/Test/WebstormProjects/react-native-web-vite/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:48786:18)
      at async loadAndTransform (file:///Users/Test/WebstormProjects/react-native-web-vite/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:51608:27)
      at async viteTransformMiddleware (file:///Users/Test/WebstormProjects/react-native-web-vite/node_modules/vite/dist/node/chunks/dep-mCdpKltl.js:61557:24)

```

I want to solve this problem and develop with my beloved nativewind! help!

**Comment by danstepanov** [comment]
we don't support vite

**Comment by Snotax** [comment]
@danstepanov  Are you planning on supporting vite someday ? 
And secondly, do you think it doesn't work at all or do you just don't support it ?

**Comment by dannyhw** [comment]
you can try this
https://github.com/dannyhw/vite-rnw-example

**Comment by dannyhw** [comment]
I was able to get vite working for react native web + nativewind +storybook 
https://github.com/dannyhw/vite-rnw-example

though I've not tried using it for an actual vite site, I had to set the `    "jsxImportSource": "nativewind",` in the tsconfig not just in the vite react plugin

**Comment by danstepanov** [comment]
> @danstepanov Are you planning on supporting vite someday ? And secondly, do you think it doesn't work at all or do you just don't support it ?

you can get it working and plenty of people have, we don't have any plans to support it as bundler work (outside of metro) isn't in the scope of what we are trying to do atm.

When people get nativewind working with Vite, it serves as a good tech demo for basic apps. However, when it comes to maintaining it and getting into more advanced usage, it tends to fall apart and people look to us to fix it. We just don't have the time/desire. If you and/or others want to make a community-driven effort to support it, please go ahead 🙂

**Comment by natew** [comment]
Heads up that Nativewind and Tailwind work out of the box now with [One](https://onestack.dev).

Feel free to message me if anything breaks.

**Comment by imdbere** [comment]
@dannyhw I tried your method and many others and all of them work in dev mode, but once i run vite build and serve the files, the tailwind classes are missing from the html. Has anyone actually got this to work in build mode?

**Comment by dannyhw** [comment]
Try adding the commonjs plugin.


I don't really use the vite-react-native-plugin.

I applied a lot of workarounds on storybook's react native web vite. Maybe you can find some ideas there.

**Comment by natew** [comment]
@VivekDahiya06 we have a "Minimal Tailwind" template if you just run `npx one`, lmk if it's working well.

**Comment by VivekDahiya06** [comment]
@natew There are a no. of warnings that are coming when the installation command is run like this
 :-
 
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm warn deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm warn deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm warn deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm warn deprecated rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
npm warn deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm warn deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated glob@7.1.6: Glob versions prior to v9 are no longer supported
npm warn deprecated sudo-prompt@9.1.1: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated sudo-prompt@8.2.5: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm warn deprecated @xmldom/xmldom@0.7.13: this version is no longer supported, please update to at least 0.8.*
WARNING: UNSUPPORTED OS - It appears you’re using Windows, which is currently not supported. You may experience unexpected issues.

**Comment by imdbere** [comment]
In case anybody else is having the same issue as me with nativewind styles working in dev mode but not once bundled, i managed to fix it by downgrading from Vite version `6.x` to `5.x`.
Its obviously not an ideal solution but maybe its helpful to somebody :)

**Comment by david-mart** [comment]
this is how I got it to work (yarn, vite 6, storybook 8.6)

```ts
// .storybook/main.ts
import type { StorybookConfig } from '@storybook/react-vite';
import type { UserConfig } from 'vite';

import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import { mergeConfig } from 'vite';
import react from '@vitejs/plugin-react';
const config: StorybookConfig = {
  stories: [
    '../src/app/**/*.@(mdx|stories.@(js|jsx|ts|tsx))',
    '../../libs/cho-kit/src/**/*.stories.@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',

  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },

  viteFinal: async (config: UserConfig) =>
    mergeConfig(config, {
      define: {
        global: 'window',
      },
      resolve: {
        extensions: [
          '.mjs',
          '.web.tsx',
          '.tsx',
          '.web.ts',
          '.ts',
          '.web.jsx',
          '.jsx',
          '.web.js',
          '.js',
          '.css',
          '.json',
          ...(config.resolve?.extensions ?? []),
        ],
        alias: {
          'react-native': 'react-native-web',
        },
      },

      plugins: [react({
        jsxImportSource: 'nativewind',
        jsxRuntime: 'automatic',
      }), nxViteTsPaths()],
      optimizeDeps: {
        esbuildOptions: {
          resolveExtensions: ['.web.js', '.js', '.ts'],
          loader: {
            '.js': 'jsx',
          },
        },
        exclude: ['react-native'],
      },
    } as UserConfig),
};

export default config;

// To customize your Vite configuration you can use the viteFinal field.
// Check https://storybook.js.org/docs/react/builders/vite#configuration
// and https://nx.dev/recipes/storybook/custom-builder-configs
```

**Comment by jtomaszewski** [comment]
@david-mart unfortunately your config doesn't fix styles not seen once bundled (even though they're seen in dev server mode).

FYI I created a repro for this and an issue here: https://github.com/storybookjs/storybook/issues/31165 .

**Comment by ethwell** [comment]
> In case anybody else is having the same issue as me with nativewind styles working in dev mode but not once bundled, i managed to fix it by downgrading from Vite version `6.x` to `5.x`. Its obviously not an ideal solution but maybe its helpful to somebody :)

@jtomaszewski Have you considered downgrading the Vite version? In my case, downgrading to 5.4.19 resolved the issue.
