### ISSUE TITLE
Error: polyfill:environment-variables

### ISSUE THREAD

**Issue by tanmayvaij** [nativewind/nativewind#993]
- Just wanted to add nativewind in my expo typescript app
- followed the instructions given on the website
- Stop and restarted the expo server with a -c flag for clearing the cache ( yarn start -c )
- The app got crashed giving the following error message :- 
  error: polyfill:environment-variables: D:\Projects\bluedive\polyfill:environment-variables: The argument 'path' must be a string, Uint8Array, or URL without null bytes. Received 'D:\\Projects\\bluedive\\\x00polyfill:environment-variables'

**Comment by tanmayvaij** [comment]
Also just noticed that the app works fine with v4 but the app crashes when i tried with v2

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
