### ISSUE TITLE
[V4] Missing support for transforming third party libraries

### ISSUE THREAD

**Issue by frederik-oestergaard** [nativewind/nativewind#997]
**Describe the bug**
We have a monorepo setup where we publish some shared packages to be consumed by different RN apps. 
The apps use Expo. 
One of these shared packages uses NativeWind and the app consuming it uses NativeWind as well. With NativeWind V2 it just worked out of the box after adjusting the tailwind config in the app to include the package (by specifying the path to the specific node module). 

With V4 we can observe the styles inside `node_modules/.cache/..` are getting generated correctly for the classes used in the library. But the styles are not getting applied to any of the components imported from the library. 

So it's as if V4 is missing the instruction to also apply it's transforms to the "third party library". 

See this discussion for example of similar issue but about V2: https://github.com/callstack/react-native-builder-bob/discussions/395

**To Reproduce**
Here is the example using V2, 
Switching the example to V4 and doing the needed adjustments to the configs results in the app running but bug as described is happening.
https://github.com/atlj/builder-bob-nativewind-example

**Expected behavior**
The transform should automatically be applied also to thirdparties that are included in the content prop of the tailwind config. Or we should have a way to explicitly tell NativeWind to include a certain package. 

**Additional context**

```JSON
"tailwindcss": "3.4.1"
"nativewind": "4.0.36",
"react": "18.2.0",
"react-native": "0.74.3",
"expo": "~51.0.24",
```

```js
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    `./node_modules/@our-scope/ui-library-react-native/lib/module/**/*.{js,jsx,ts,tsx}`,
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {},
  },
  plugins: [],
};
```

**Comment by marklawlor** [comment]
This is detailed in the migration guide to v4, but NativeWind now only transforms the React Native primitives (View, Text, etc). It is expected for 3rd party components to pass the `className` prop down to these components. If they do not, then you need to use the `cssInterop` function to tell NativeWind to also transform these components.
