### ISSUE TITLE
Platform specific styles not applying

### ISSUE THREAD

**Issue by WKampel** [nativewind/nativewind#998]
I'm running the latest version of Nativewind (4.0.36) with Expo (51.0.28).

The platform specifiers (web:, android:, ios:, native:) don't work. Any styles with those specifiers just don't apply.

**Comment by danstepanov** [comment]
We are closing all pre-v4.1 issues now that v4.1 is released. If the problem is still happening with the latest v4.1, [please open a new issue](https://github.com/nativewind/nativewind/blob/next/contributing.md#opening-an-issue) and reference this one in the description.
