### ISSUE TITLE
stuck on rebuilding... done

### ISSUE THREAD

**Issue by Puyodead1** [nativewind/nativewind#999]
I am trying to switch an existing vite react native project to use nativewind, I am only developing for android, and when trying to build and test it gets stuck at `tailwindcss(native) rebuilding... done`. I have tried letting sit for over an hour now and it's not doing anything different.

metro.config.js
```
const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
const MetroSymlinksResolver = require('@rnx-kit/metro-resolver-symlinks');
const {withNativeWind} = require('nativewind/metro');

const config = mergeConfig(getDefaultConfig(__dirname), {
  resolver: {
    resolveRequest: MetroSymlinksResolver(),
  },
});

module.exports = withNativeWind(config, {input: './src/global.css'});

```

components.json
```
{
  "platforms": "native-only",
  "aliases": {
    "components": "@/components",
    "lib": "@/lib"
  }
}
```

index.js
```
import {AppRegistry} from 'react-native';
import {name as appName} from './app.json';
import App from './src/App';
import './src/global.css';

AppRegistry.registerComponent(appName, () => App);

```

tsconfig.json
```
{
  "extends": "@react-native/typescript-config/tsconfig.json",
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  }
}

```

global.css is in ./src and is copied straight from the docs

![image](https://github.com/user-attachments/assets/21a5e524-36c2-4d28-bb2e-2a72879f89bf)

React Native: 0.75.1
Nativewind: 4.0.1

**Comment by Puyodead1** [comment]
I've found that it seems to only be when including global.css, even if its empty

**Comment by danstepanov** [comment]
we don't support vite
